import type { ComponentVariantCompiler } from "../ComponentVariantCompiler";
import { contentButton, contentColumn, contentContainer, contentGutter, contentHeading, contentId, contentIntent, contentSeed, contentSpacing, contentText, finalizeContentCompilation, mutedSurface, resolveContentCtaPlacement, resolveContentDensity, surface } from "./contentCompilerPrimitives";

export const CourseCataloguePreviewCompiler: ComponentVariantCompiler = Object.freeze({ variantId:"CourseCataloguePreview01", compile(context){
  const ns="catalogue",root=contentId(context,"container.course-catalogue"),intro=contentId(context,"column.catalogue-intro"),catalogue=contentId(context,"column.programme-catalogue"),list=contentId(context,"container.programme-list"),enquiry=contentId(context,"column.enquiry-action");
  const density=resolveContentDensity(context,["courses","programmes","programs","offerings"],4),ctaPlacement=resolveContentCtaPlacement(context),count=density.itemCount,rows=Array.from({length:count},(_,i)=>contentId(context,`column.programme-row-${i+1}`)),spacing=contentSpacing(context),rootChildren=[intro,catalogue,...(ctaPlacement==="after-content"?[enquiry]:[])],introChildren=[contentId(context,"text.eyebrow"),contentId(context,"heading.headline"),contentId(context,"text.description"),...(ctaPlacement==="intro"?[contentId(context,"button.enquiry_cta")]:[])];
  const nodes=[contentSeed(context,{id:context.sectionNodeId,type:"section",name:"Course catalogue preview",parentId:"page.root",children:[root],props:{role:"catalogue",semanticRole:"course-catalogue-preview",purpose:context.section.purpose,componentVariant:"CourseCataloguePreview01",...contentIntent(context,{density,ctaPlacement})},style:{paddingTop:{desktop:spacing,tablet:Math.round(spacing*.76),mobile:Math.round(spacing*.56)},paddingBottom:{desktop:spacing,tablet:Math.round(spacing*.76),mobile:Math.round(spacing*.56)},backgroundColor:surface(context)}}),
  contentSeed(context,{id:root,type:"container",name:`${density.densityLevel} course catalogue`,parentId:context.sectionNodeId,children:rootChildren,props:{semanticRole:density.densityLevel==="sparse"?"featured-programmes":"programme-catalogue"},style:{display:"grid",width:"100%",maxWidth:context.input.designResult?.layoutProfile.maxWidth??"1180px",margin:"0 auto",paddingLeft:{desktop:contentGutter(context),tablet:20,mobile:16},paddingRight:{desktop:contentGutter(context),tablet:20,mobile:16},gridTemplateColumns:{desktop:density.densityLevel==="sparse"?"1fr":".7fr 1.3fr",tablet:"1fr",mobile:"1fr"},gap:{desktop:42,tablet:28,mobile:22},alignItems:"start"}}),
  contentColumn(context,"column.catalogue-intro",root,introChildren,{gap:14,maxWidth:density.densityLevel==="sparse"?760:560}),contentText(context,ns,intro,"eyebrow","eyebrow"),contentHeading(context,ns,intro,"headline","h2"),contentText(context,ns,intro,"description"),...(ctaPlacement==="intro"?[contentButton(context,ns,intro,"enquiry_cta")]:[]),contentColumn(context,"column.programme-catalogue",root,[list]),
  contentContainer(context,"container.programme-list",catalogue,rows,{display:"grid",gridTemplateColumns:{desktop:density.densityLevel==="sparse"?`repeat(${count}, minmax(0, 1fr))`:density.densityLevel==="dense"?"1fr":"1fr 1fr",tablet:density.densityLevel==="dense"?"1fr":"1fr 1fr",mobile:"1fr"},gap:density.densityLevel==="dense"?10:16})];
  rows.forEach((rowId,i)=>{const role=`programme_${i+1}`;nodes.push(contentColumn(context,`column.programme-row-${i+1}`,list,[contentId(context,`heading.${role}_name`),contentId(context,`text.${role}_summary`)],{display:density.densityLevel==="dense"?"grid":"flex",...(density.densityLevel==="dense"?{gridTemplateColumns:{desktop:".55fr 1fr",tablet:".55fr 1fr",mobile:"1fr"}}:{}),gap:9,padding:{desktop:density.densityLevel==="sparse"?26:18,tablet:18,mobile:16},border:`1px solid ${mutedSurface(context)}`}),contentHeading(context,ns,rowId,`${role}_name`,`h3`),contentText(context,ns,rowId,`${role}_summary`));});
  if(ctaPlacement==="after-content")nodes.push(contentColumn(context,"column.enquiry-action",root,[contentId(context,"text.factual_caution"),contentId(context,"button.enquiry_cta")],{gridColumn:{desktop:"1 / -1",tablet:"auto",mobile:"auto"},display:"grid",gridTemplateColumns:{desktop:"1fr auto",tablet:"1fr auto",mobile:"1fr"},gap:16,alignItems:"center",padding:{desktop:20,tablet:18,mobile:16},backgroundColor:mutedSurface(context)}),contentText(context,ns,enquiry,"factual_caution","microcopy"),contentButton(context,ns,enquiry,"enquiry_cta"));return finalizeContentCompilation(nodes);
} });
