import type { ComponentVariantCompiler } from "../ComponentVariantCompiler";
import { contentButton, contentColumn, contentContainer, contentGutter, contentHeading, contentId, contentImage, contentIntent, contentSeed, contentSpacing, contentText, finalizeContentCompilation, mutedSurface, resolveContentCtaPlacement, resolveContentDensity, surface } from "./contentCompilerPrimitives";

export const MenuPreviewCardsCompiler: ComponentVariantCompiler = Object.freeze({ variantId:"MenuPreviewCards01", compile(context){
  const ns="menu",root=contentId(context,"container.menu-preview"),intro=contentId(context,"column.menu-intro"),headingRow=contentId(context,"container.menu-heading-row"),body=contentId(context,"column.menu-body"),categories=contentId(context,"container.menu-categories"),action=contentId(context,"column.menu-action"); const density=resolveContentDensity(context,["menuItems","menu","offerings"],6),ctaPlacement=resolveContentCtaPlacement(context),categoryCount=density.densityLevel==="dense"?3:2,categoryIds=Array.from({length:categoryCount},(_,i)=>contentId(context,`column.menu-category-${i+1}`)); const spacing=contentSpacing(context),rootChildren=[intro,body,...(ctaPlacement==="after-content"?[action]:[])],headingChildren=[contentId(context,"heading.headline"),contentId(context,"text.description"),...(ctaPlacement==="intro"?[contentId(context,"button.reservation_cta")]:[])];
  const nodes=[contentSeed(context,{id:context.sectionNodeId,type:"section",name:"Menu preview",parentId:"page.root",children:[root],props:{role:"menu",semanticRole:"menu-preview",purpose:context.section.purpose,componentVariant:"MenuPreviewCards01",...contentIntent(context,{density,ctaPlacement})},style:{paddingTop:{desktop:spacing,tablet:Math.round(spacing*.76),mobile:Math.round(spacing*.56)},paddingBottom:{desktop:spacing,tablet:Math.round(spacing*.76),mobile:Math.round(spacing*.56)},backgroundColor:surface(context)}}),
  contentSeed(context,{id:root,type:"container",name:"Editorial menu frame",parentId:context.sectionNodeId,children:rootChildren,props:{semanticRole:"editorial-menu-frame"},style:{display:"flex",flexDirection:"column",width:"100%",maxWidth:context.input.designResult?.layoutProfile.maxWidth??"1180px",margin:"0 auto",paddingLeft:{desktop:contentGutter(context),tablet:20,mobile:16},paddingRight:{desktop:contentGutter(context),tablet:20,mobile:16},gap:{desktop:36,tablet:28,mobile:22}}}),
  contentColumn(context,"column.menu-intro",root,[contentId(context,"text.eyebrow"),headingRow],{gap:14}),contentText(context,ns,intro,"eyebrow","eyebrow"),contentContainer(context,"container.menu-heading-row",intro,headingChildren,{display:"grid",gridTemplateColumns:{desktop:"1fr 1fr auto",tablet:"1fr 1fr",mobile:"1fr"},gap:16,alignItems:"end"}),contentHeading(context,ns,headingRow,"headline","h2"),contentText(context,ns,headingRow,"description"),...(ctaPlacement==="intro"?[contentButton(context,ns,headingRow,"reservation_cta")]:[]),
  contentColumn(context,"column.menu-body",root,[categories]),contentContainer(context,"container.menu-categories",body,categoryIds,{display:"grid",gridTemplateColumns:{desktop:`repeat(${categoryCount}, minmax(0, 1fr))`,tablet:"1fr 1fr",mobile:"1fr"},gap:{desktop:28,tablet:20,mobile:16}})];
  categoryIds.forEach((categoryId,i)=>{const list=contentId(context,`container.menu-list-${i+1}`),per=Math.ceil(density.itemCount/categoryCount),items=Array.from({length:per},(_,j)=>contentId(context,`column.menu-${i+1}-item-${j+1}`));nodes.push(contentColumn(context,`column.menu-category-${i+1}`,categories,[contentId(context,`image.category_${i+1}_image`),contentId(context,`heading.category_${i+1}_label`),list],{gap:14}),contentImage(context,ns,categoryId,`category_${i+1}_image`,`16 / 7`),contentHeading(context,ns,categoryId,`category_${i+1}_label`,`h3`),contentContainer(context,`container.menu-list-${i+1}`,categoryId,items,{display:"flex",flexDirection:"column",gap:0}));items.forEach((itemId,j)=>{const role=`category_${i+1}_item_${j+1}`;nodes.push(contentColumn(context,`column.menu-${i+1}-item-${j+1}`,list,[contentId(context,`heading.${role}_name`),contentId(context,`text.${role}_description`),contentId(context,`text.${role}_price_caution`)],{gap:6,padding:{desktop:16,tablet:14,mobile:12},border:`1px solid ${mutedSurface(context)}`}),contentHeading(context,ns,itemId,`${role}_name`,`h4`),contentText(context,ns,itemId,`${role}_description`),contentText(context,ns,itemId,`${role}_price_caution`,`microcopy`));});});if(ctaPlacement==="after-content")nodes.push(contentColumn(context,"column.menu-action",root,[contentId(context,"text.experience_note"),contentId(context,"button.reservation_cta")],{display:"grid",gridTemplateColumns:{desktop:"1fr auto",tablet:"1fr auto",mobile:"1fr"},gap:16,alignItems:"center",padding:{desktop:20,tablet:18,mobile:16},backgroundColor:mutedSurface(context)}),contentText(context,ns,action,"experience_note","microcopy"),contentButton(context,ns,action,"reservation_cta"));return finalizeContentCompilation(nodes);
} });
