import type { ComponentVariantCompiler } from "../ComponentVariantCompiler";
import { contentButton, contentColumn, contentContainer, contentGutter, contentHeading, contentId, contentImage, contentIntent, contentSeed, contentSpacing, contentText, finalizeContentCompilation, mutedSurface, resolveContentCtaPlacement, resolveContentDensity, resolveContentMediaMode, surface } from "./contentCompilerPrimitives";

export const ProductFeatureStackCompiler: ComponentVariantCompiler = Object.freeze({ variantId:"ProductFeatureStack01", compile(context){
  const ns="product",root=contentId(context,"container.product-features"),intro=contentId(context,"column.product-intro"),stage=contentId(context,"column.feature-stage"),action=contentId(context,"column.product-action");
  const density=resolveContentDensity(context,["features","productFeatures","offerings"],3),mediaMode=resolveContentMediaMode(context),ctaPlacement=resolveContentCtaPlacement(context),featureCount=Math.min(density.itemCount,mediaMode==="multiple"?6:4),rows=Array.from({length:featureCount},(_,i)=>contentId(context,`container.feature-row-${i+1}`)),featuredImage=contentId(context,"image.featured_product"),spacing=contentSpacing(context);
  const stageChildren=[...(mediaMode==="single"?[featuredImage]:[]),...rows],rootChildren=[intro,stage,...(ctaPlacement==="after-content"?[action]:[])],introChildren=[contentId(context,"text.eyebrow"),contentId(context,"heading.headline"),contentId(context,"text.description"),...(ctaPlacement==="intro"?[contentId(context,"button.product_cta")]:[])];
  const nodes=[contentSeed(context,{id:context.sectionNodeId,type:"section",name:"Product feature stack",parentId:"page.root",children:[root],props:{role:"product",semanticRole:"product-feature-stack",purpose:context.section.purpose,componentVariant:"ProductFeatureStack01",...contentIntent(context,{density,mediaMode,ctaPlacement})},style:{paddingTop:{desktop:spacing,tablet:Math.round(spacing*.74),mobile:Math.round(spacing*.54)},paddingBottom:{desktop:spacing,tablet:Math.round(spacing*.74),mobile:Math.round(spacing*.54)},backgroundColor:surface(context)}}),
  contentSeed(context,{id:root,type:"container",name:`${mediaMode} product narrative`,parentId:context.sectionNodeId,children:rootChildren,props:{semanticRole:mediaMode==="none"?"typography-first-product":"editorial-product-story"},style:{display:"grid",width:"100%",maxWidth:context.input.designResult?.layoutProfile.maxWidth??"1180px",margin:"0 auto",paddingLeft:{desktop:contentGutter(context),tablet:20,mobile:16},paddingRight:{desktop:contentGutter(context),tablet:20,mobile:16},gridTemplateColumns:{desktop:mediaMode==="none"?".72fr 1.28fr":".62fr 1.38fr",tablet:".85fr 1.15fr",mobile:"1fr"},gap:{desktop:52,tablet:32,mobile:24},alignItems:"start"}}),
  contentColumn(context,"column.product-intro",root,introChildren,{gap:14}),contentText(context,ns,intro,"eyebrow","eyebrow"),contentHeading(context,ns,intro,"headline","h2"),contentText(context,ns,intro,"description"),...(ctaPlacement==="intro"?[contentButton(context,ns,intro,"product_cta")]:[]),contentColumn(context,"column.feature-stage",root,stageChildren,{gap:18})];
  if(mediaMode==="single")nodes.push(contentImage(context,ns,stage,"featured_product","16 / 9"));
  rows.forEach((rowId,i)=>{const role=`feature_${i+1}`,withMedia=mediaMode==="multiple",children=[...(withMedia?[contentId(context,`image.${role}_media`)]:[]),contentId(context,`heading.${role}_title`),contentId(context,`text.${role}_description`),contentId(context,`text.${role}_proof_caution`)];nodes.push(contentContainer(context,`container.feature-row-${i+1}`,stage,children,{display:"grid",gridTemplateColumns:{desktop:withMedia?(i%2?"1fr .72fr":".72fr 1fr"):".65fr 1fr",tablet:"1fr",mobile:"1fr"},gap:{desktop:18,tablet:10,mobile:8},padding:{desktop:28,tablet:22,mobile:18},backgroundColor:i%2?mutedSurface(context):"transparent",border:`1px solid ${mutedSurface(context)}`}),...(withMedia?[contentImage(context,ns,rowId,`${role}_media`,`4 / 3`)]:[]),contentHeading(context,ns,rowId,`${role}_title`,`h3`),contentText(context,ns,rowId,`${role}_description`),contentText(context,ns,rowId,`${role}_proof_caution`,`microcopy`));});
  if(ctaPlacement==="after-content")nodes.push(contentColumn(context,"column.product-action",root,[contentId(context,"button.product_cta")],{gridColumn:{desktop:"1 / -1",tablet:"1 / -1",mobile:"auto"},alignItems:"flex-start"}),contentButton(context,ns,action,"product_cta"));return finalizeContentCompilation(nodes);
} });
