export interface GoogleFontItem {
  family: string;
  variants?: string[];
  category?: string;
}

export const SYSTEM_FONT_OPTIONS: GoogleFontItem[] = [
  { family: "system-ui", category: "system" },
  { family: "Arial", category: "system" },
  { family: "Helvetica", category: "system" },
  { family: "Georgia", category: "system" },
  { family: "Times New Roman", category: "system" },
  { family: "Courier New", category: "system" },
];

export const FALLBACK_GOOGLE_FONTS: GoogleFontItem[] = [
  { family: "Roboto", category: "sans-serif" },
  { family: "Open Sans", category: "sans-serif" },
  { family: "Lato", category: "sans-serif" },
  { family: "Montserrat", category: "sans-serif" },
  { family: "Poppins", category: "sans-serif" },
  { family: "Inter", category: "sans-serif" },
  { family: "Roboto Condensed", category: "sans-serif" },
  { family: "Oswald", category: "sans-serif" },
  { family: "Source Sans 3", category: "sans-serif" },
  { family: "Noto Sans", category: "sans-serif" },
  { family: "Raleway", category: "sans-serif" },
  { family: "Ubuntu", category: "sans-serif" },
  { family: "Nunito", category: "sans-serif" },
  { family: "Merriweather", category: "serif" },
  { family: "Playfair Display", category: "serif" },
  { family: "Roboto Slab", category: "serif" },
  { family: "PT Sans", category: "sans-serif" },
  { family: "Noto Serif", category: "serif" },
  { family: "Nunito Sans", category: "sans-serif" },
  { family: "Work Sans", category: "sans-serif" },
  { family: "Quicksand", category: "sans-serif" },
  { family: "Rubik", category: "sans-serif" },
  { family: "Mukta", category: "sans-serif" },
  { family: "Fira Sans", category: "sans-serif" },
  { family: "Barlow", category: "sans-serif" },
  { family: "Inconsolata", category: "monospace" },
  { family: "Libre Franklin", category: "sans-serif" },
  { family: "Karla", category: "sans-serif" },
  { family: "Josefin Sans", category: "sans-serif" },
  { family: "Cabin", category: "sans-serif" },
  { family: "Arimo", category: "sans-serif" },
  { family: "Bitter", category: "serif" },
  { family: "Hind Siliguri", category: "sans-serif" },
  { family: "Dosis", category: "sans-serif" },
  { family: "Hind", category: "sans-serif" },
  { family: "Anton", category: "sans-serif" },
  { family: "Libre Baskerville", category: "serif" },
  { family: "Manrope", category: "sans-serif" },
  { family: "Heebo", category: "sans-serif" },
  { family: "Crimson Text", category: "serif" },
  { family: "Titillium Web", category: "sans-serif" },
  { family: "IBM Plex Sans", category: "sans-serif" },
  { family: "Mulish", category: "sans-serif" },
  { family: "Noto Sans JP", category: "sans-serif" },
  { family: "Archivo", category: "sans-serif" },
  { family: "DM Sans", category: "sans-serif" },
  { family: "Space Grotesk", category: "sans-serif" },
  { family: "Plus Jakarta Sans", category: "sans-serif" },
  { family: "Outfit", category: "sans-serif" },
  { family: "Lexend", category: "sans-serif" },
  { family: "Sora", category: "sans-serif" },
  { family: "Urbanist", category: "sans-serif" },
  { family: "Public Sans", category: "sans-serif" },
  { family: "Epilogue", category: "sans-serif" },
  { family: "Bricolage Grotesque", category: "sans-serif" },
  { family: "Instrument Sans", category: "sans-serif" },
  { family: "Fraunces", category: "serif" },
  { family: "Cormorant Garamond", category: "serif" },
  { family: "Lora", category: "serif" },
  { family: "EB Garamond", category: "serif" },
  { family: "Spectral", category: "serif" },
  { family: "Alegreya", category: "serif" },
  { family: "Source Serif 4", category: "serif" },
  { family: "IBM Plex Serif", category: "serif" },
  { family: "JetBrains Mono", category: "monospace" },
  { family: "Roboto Mono", category: "monospace" },
  { family: "Source Code Pro", category: "monospace" },
  { family: "Fira Code", category: "monospace" },
  { family: "IBM Plex Mono", category: "monospace" },
  { family: "Caveat", category: "handwriting" },
  { family: "Pacifico", category: "handwriting" },
  { family: "Dancing Script", category: "handwriting" },
  { family: "Shadows Into Light", category: "handwriting" },
  { family: "Permanent Marker", category: "display" },
  { family: "Bebas Neue", category: "display" },
  { family: "Abril Fatface", category: "display" },
  { family: "Cinzel", category: "serif" },
  { family: "Righteous", category: "display" },
  { family: "Exo 2", category: "sans-serif" },
  { family: "Rajdhani", category: "sans-serif" },
  { family: "Teko", category: "sans-serif" },
  { family: "Prompt", category: "sans-serif" },
  { family: "Kanit", category: "sans-serif" },
  { family: "Jost", category: "sans-serif" },
  { family: "Red Hat Display", category: "sans-serif" },
  { family: "Red Hat Text", category: "sans-serif" },
  { family: "Noto Sans KR", category: "sans-serif" },
  { family: "Noto Sans TC", category: "sans-serif" },
  { family: "Noto Sans SC", category: "sans-serif" },
  { family: "Noto Sans Devanagari", category: "sans-serif" },
  { family: "Noto Sans Arabic", category: "sans-serif" },
  { family: "Noto Sans Hebrew", category: "sans-serif" },
  { family: "Noto Sans Thai", category: "sans-serif" },
];

export const FONT_OPTIONS: GoogleFontItem[] = [
  ...SYSTEM_FONT_OPTIONS,
  ...FALLBACK_GOOGLE_FONTS,
];

export function isSystemFont(family: string) {
  return SYSTEM_FONT_OPTIONS.some((font) => font.family === family);
}

export function normalizeGoogleFontFamily(family: string) {
  return family.trim().replace(/^['"]|['"]$/g, "");
}
