packages:
  - apps/*
  - packages/*

allowBuilds:
  '@ffmpeg-installer/darwin-arm64': false
  '@ffprobe-installer/darwin-arm64': false
  '@firebase/util': true
  '@prisma/client': true
  '@prisma/engines': true
  esbuild: true
  prisma: true
  protobufjs: true
  sharp: true
  unrs-resolver: true

ignoredBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - '@firebase/util'
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
  - protobufjs
