import assert from "node:assert/strict";
import { describe,it } from "node:test";
import type { BuilderBlueprint,BuilderNode,NodeType } from "../../types/blueprint";
import { createPrimitiveBlueprint } from "../fixtures/testBlueprintFixtures";
import { enforceNativeWidgetPopulationGate,runNativeWidgetPopulationGate } from "../../website-engine/builder-blueprint/widget-population";

function withWidget(type:NodeType,props:Record<string,unknown>):BuilderBlueprint{const base=createPrimitiveBlueprint();const id=`widget.${type}`;const node:BuilderNode={id,type,name:type,parentId:"test-section",children:[],props,style:{}};return {...base,nodes:{...base.nodes,"test-section":{...base.nodes["test-section"],children:[...base.nodes["test-section"].children,id]},[id]:node}};}
const heroProps={eyebrow:"A considered introduction",title:"A distinct opening statement",body:"Specific supporting context for the intended audience.",primaryCta:"Begin consultation",secondaryCta:"Explore details",items:["First priority clarified","A meaningful proof point"],variant:"editorial",motionPreset:"none",generationCapability:"hero",media:{id:"hero-media",src:"https://cdn.example.test/hero.jpg",prompt:"Descriptive editorial architecture",alt:"Contemporary architecture in landscape",role:"dominant"}};

describe("RC-3.5D native widget population gate",()=>{
  it("passes only a complete, persisted, non-demo native widget",()=>{const gate=runNativeWidgetPopulationGate({blueprint:withWidget("hero",heroProps),businessContext:{businessFamily:"architecture_interiors"},knownFacts:{}});assert.equal(gate.passed,true,JSON.stringify(gate.failures));assert.equal(gate.fullyPopulatedWidgets,1);assert.equal(gate.persistenceExact,true);});
  it("is non-compensating for required media",()=>{const blueprint=withWidget("hero",{...heroProps,media:{...(heroProps.media as object),src:""}});const gate=runNativeWidgetPopulationGate({blueprint});assert.equal(gate.passed,false);assert.deepEqual(gate.widgetsWithMissingRequiredMedia,["widget.hero"]);});
  it("rejects registered defaults and repeated unrelated headlines",()=>{const first=withWidget("hero",heroProps);const second:BuilderNode={id:"widget.cta",type:"cta",name:"CTA",parentId:"test-section",children:[],props:{eyebrow:"Decision",title:heroProps.title,body:"Different context",primaryCta:"Contact",secondaryCta:"Review",items:["Action"],variant:"conversion"},style:{}};const blueprint={...first,nodes:{...first.nodes,"test-section":{...first.nodes["test-section"],children:[...first.nodes["test-section"].children,second.id]},[second.id]:second}};const gate=runNativeWidgetPopulationGate({blueprint});assert.equal(gate.passed,false);assert.equal(gate.widgetsWithDuplicateCopy.length,2);});
  it("omits an optional unresolved media section but never omits a required hero",()=>{const gallery=withWidget("galleryLightbox",{eyebrow:"Collection",title:"A distinct collection",body:"Visual context",primaryCta:"View",secondaryCta:"",items:["One","Two","Three","Four"],variant:"default",galleryItems:Array.from({length:4},(_,index)=>({id:`g${index}`,title:`Image ${index}`,caption:`Caption ${index}`,src:"",prompt:`Prompt ${index}`,alt:`Alt ${index}`}))});const optional=enforceNativeWidgetPopulationGate({blueprint:gallery});assert.equal(optional.omittedSections.length,1);assert.equal(optional.gate.passed,true);const hero=enforceNativeWidgetPopulationGate({blueprint:withWidget("hero",{...heroProps,media:{...heroProps.media,src:""}})});assert.equal(hero.omittedSections.length,0);assert.equal(hero.gate.passed,false);});
  it("rejects a contact capability without a verified destination",()=>{const props={eyebrow:"Contact",title:"Continue the conversation",body:"Choose a verified contact route.",primaryCta:"Contact",secondaryCta:"",items:["Contact"],variant:"default"};const gate=runNativeWidgetPopulationGate({blueprint:withWidget("floatingWhatsApp",props),knownFacts:{}});assert.equal(gate.passed,false);assert.equal(gate.unsafeFactualWidgets.includes("widget.floatingWhatsApp"),true);});
  it("replaces unsafe WhatsApp with a role-correct standard CTA without inventing a destination",()=>{const props={eyebrow:"Contact",title:"Continue the conversation",body:"Choose a verified contact route.",primaryCta:"Contact",secondaryCta:"",items:["Contact"],variant:"default"};const result=enforceNativeWidgetPopulationGate({blueprint:withWidget("floatingWhatsApp",props),knownFacts:{}});assert.equal(result.replacementAttempts,1);assert.equal(result.blueprint.nodes["widget.floatingWhatsApp"].type,"cta");assert.equal("whatsappNumber" in result.blueprint.nodes["widget.floatingWhatsApp"].props,false);assert.equal(result.gate.passed,true,JSON.stringify(result.gate.failures));});
});
