import type { ElementCatalogItem } from "./types";

export const firstPartyElements: ElementCatalogItem[] = [
  {
    id: "core.page",
    type: "page",
    name: "Page",
    description: "The root document node for a builder page.",
    source: "first-party",
    category: "layout",
    tier: "default",
    requiredFeature: "core_widgets",
    allowedPlans: ["free", "pro", "business"],
    marketplaceCategory: "Document",
    tags: ["root", "document"],
    industryTags: ["all"],
    styleTags: ["all"],
    aiUseCases: ["Create the editable root of every generated page."],
    ai: {
      canGenerate: false,
      guidance: "Use once as the root node. Do not create nested page nodes.",
    },
  },
  {
    id: "layout.section",
    type: "section",
    name: "Section",
    description: "A full-width page band that groups related content.",
    source: "first-party",
    category: "layout",
    tier: "default",
    requiredFeature: "core_widgets",
    allowedPlans: ["free", "pro", "business"],
    marketplaceCategory: "Layout",
    tags: ["layout", "band", "group"],
    industryTags: ["all"],
    styleTags: ["minimal", "editorial", "corporate", "bold"],
    aiUseCases: ["Separate page intent into editable content bands."],
    ai: {
      canGenerate: true,
      guidance: "Use sections as the top-level building blocks inside a page.",
    },
  },
  {
    id: "layout.container",
    type: "container",
    name: "Container",
    description: "A layout wrapper for rows, columns, cards, and content groups.",
    source: "first-party",
    category: "layout",
    tier: "default",
    requiredFeature: "core_widgets",
    allowedPlans: ["free", "pro", "business"],
    marketplaceCategory: "Layout",
    tags: ["layout", "wrapper", "flex", "grid"],
    industryTags: ["all"],
    styleTags: ["minimal", "editorial", "corporate", "bold"],
    aiUseCases: ["Group child widgets with consistent spacing and width."],
    ai: {
      canGenerate: true,
      guidance: "Use containers to organize child widgets. Prefer theme tokens for spacing.",
    },
  },
  {
    id: "layout.column",
    type: "column",
    name: "Column",
    description: "A child layout region inside row or grid compositions.",
    source: "first-party",
    category: "layout",
    tier: "default",
    requiredFeature: "core_widgets",
    allowedPlans: ["free", "pro", "business"],
    marketplaceCategory: "Layout",
    tags: ["layout", "column"],
    industryTags: ["all"],
    styleTags: ["minimal", "editorial", "corporate", "bold"],
    aiUseCases: ["Build split hero, feature, and comparison layouts."],
    ai: {
      canGenerate: true,
      guidance: "Use columns for split layouts and multi-column sections.",
    },
  },
  {
    id: "content.heading",
    type: "heading",
    name: "Heading",
    description: "A semantic heading with editable text and level.",
    source: "first-party",
    category: "content",
    tier: "default",
    requiredFeature: "core_widgets",
    allowedPlans: ["free", "pro", "business"],
    marketplaceCategory: "Content",
    tags: ["text", "title", "seo"],
    industryTags: ["all"],
    styleTags: ["minimal", "editorial", "corporate", "bold"],
    aiUseCases: ["Create page, section, card, and CTA titles."],
    ai: {
      canGenerate: true,
      guidance: "Use for section titles and preserve sensible heading hierarchy.",
    },
  },
  {
    id: "content.text",
    type: "text",
    name: "Text",
    description: "Editable rich text for body copy, labels, and supporting content.",
    source: "first-party",
    category: "content",
    tier: "default",
    requiredFeature: "core_widgets",
    allowedPlans: ["free", "pro", "business"],
    marketplaceCategory: "Content",
    tags: ["copy", "paragraph", "rich-text"],
    industryTags: ["all"],
    styleTags: ["minimal", "editorial", "corporate", "bold"],
    aiUseCases: ["Write supporting page copy, descriptions, and explanatory text."],
    ai: {
      canGenerate: true,
      guidance: "Use concise, business-specific copy. Avoid placeholder wording.",
    },
  },
  {
    id: "conversion.button",
    type: "button",
    name: "Button",
    description: "A call-to-action link or button.",
    source: "first-party",
    category: "conversion",
    tier: "default",
    requiredFeature: "core_widgets",
    allowedPlans: ["free", "pro", "business"],
    marketplaceCategory: "Conversion",
    tags: ["cta", "link", "action"],
    industryTags: ["all"],
    styleTags: ["minimal", "corporate", "bold"],
    aiUseCases: ["Add primary and secondary conversion actions."],
    ai: {
      canGenerate: true,
      guidance: "Use clear action labels and theme-level button styles.",
    },
  },
  {
    id: "media.image",
    type: "image",
    name: "Image",
    description: "An editable image with alt text and optional AI image prompt.",
    source: "first-party",
    category: "media",
    tier: "default",
    requiredFeature: "core_widgets",
    allowedPlans: ["free", "pro", "business"],
    marketplaceCategory: "Media",
    tags: ["media", "photo", "illustration"],
    industryTags: ["all"],
    styleTags: ["minimal", "editorial", "premium", "bold"],
    aiUseCases: ["Place brand, product, team, or generated visual assets."],
    ai: {
      canGenerate: true,
      guidance: "Use meaningful alt text and store generated-image intent in props.aiPrompt.",
    },
  },
  {
    id: "media.video",
    type: "video",
    name: "Video",
    description: "An embedded or uploaded video block.",
    source: "first-party",
    category: "media",
    tier: "default",
    requiredFeature: "core_widgets",
    allowedPlans: ["free", "pro", "business"],
    marketplaceCategory: "Media",
    tags: ["media", "video"],
    industryTags: ["education", "saas", "creator", "real-estate"],
    styleTags: ["editorial", "premium", "bold"],
    aiUseCases: ["Add demos, walkthroughs, or video-led storytelling sections."],
    ai: {
      canGenerate: true,
      guidance: "Use only when the prompt asks for video or a demo section.",
    },
  },
  {
    id: "content.icon",
    type: "icon",
    name: "Icon",
    description: "A small symbolic visual for features and UI accents.",
    source: "first-party",
    category: "content",
    tier: "default",
    requiredFeature: "core_widgets",
    allowedPlans: ["free", "pro", "business"],
    marketplaceCategory: "Content",
    tags: ["symbol", "feature", "visual"],
    industryTags: ["all"],
    styleTags: ["minimal", "corporate", "bold"],
    aiUseCases: ["Support feature cards, stats, and compact benefit lists."],
    ai: {
      canGenerate: true,
      guidance: "Use sparingly to support feature cards or compact lists.",
    },
  },
  {
    id: "layout.divider",
    type: "divider",
    name: "Divider",
    description: "A visual separator between content groups.",
    source: "first-party",
    category: "layout",
    tier: "default",
    requiredFeature: "core_widgets",
    allowedPlans: ["free", "pro", "business"],
    marketplaceCategory: "Layout",
    tags: ["separator", "rule"],
    industryTags: ["all"],
    styleTags: ["minimal", "editorial", "corporate"],
    aiUseCases: ["Separate dense content groups when spacing is not enough."],
    ai: {
      canGenerate: true,
      guidance: "Use only when it improves scanning.",
    },
  },
  {
    id: "layout.spacer",
    type: "spacer",
    name: "Spacer",
    description: "A controlled spacing element.",
    source: "first-party",
    category: "layout",
    tier: "default",
    requiredFeature: "core_widgets",
    allowedPlans: ["free", "pro", "business"],
    marketplaceCategory: "Layout",
    tags: ["spacing", "layout"],
    industryTags: ["all"],
    styleTags: ["all"],
    aiUseCases: ["Fine-tune edge-case spacing after layout tokens are applied."],
    ai: {
      canGenerate: false,
      guidance: "Prefer section/container gap and padding tokens instead of spacer nodes.",
    },
  },
  {
    id: "premium.navigation.header",
    type: "smartHeader",
    name: "Smart Header",
    description: "Responsive navigation with logo, menus, CTA, and mobile drawer behavior.",
    source: "marketplace",
    category: "conversion",
    tier: "premium",
    requiredFeature: "premium_widgets",
    allowedPlans: ["pro", "business"],
    marketplaceCategory: "Header and navigation",
    tags: ["nav", "menu", "header", "cta"],
    industryTags: ["all"],
    styleTags: ["minimal", "corporate", "premium", "bold"],
    aiUseCases: ["Create branded site navigation with conversion-focused primary actions."],
    ai: {
      canGenerate: true,
      guidance: "Use when a generated page needs production navigation and mobile menu behavior.",
    },
  },
  {
    id: "premium.hero.conversion",
    type: "hero",
    name: "Conversion Hero",
    description: "Hero section with headline, proof points, CTA group, and media slot.",
    source: "marketplace",
    category: "conversion",
    tier: "premium",
    requiredFeature: "premium_widgets",
    allowedPlans: ["pro", "business"],
    marketplaceCategory: "Hero",
    tags: ["hero", "cta", "proof", "above-the-fold"],
    industryTags: ["saas", "services", "startup", "agency"],
    styleTags: ["minimal", "corporate", "premium", "bold"],
    aiUseCases: ["Generate high-impact above-the-fold sections for landing pages."],
    ai: {
      canGenerate: true,
      guidance: "Use for landing pages where the first viewport must explain offer, trust, and action.",
    },
  },
  {
    id: "premium.forms.lead-capture",
    type: "leadForm",
    name: "Lead Capture Form",
    description: "Validated form block for contact, quote, appointment, or waitlist flows.",
    source: "marketplace",
    category: "conversion",
    tier: "premium",
    requiredFeature: "premium_widgets",
    allowedPlans: ["pro", "business"],
    marketplaceCategory: "Forms",
    tags: ["form", "lead", "contact", "validation"],
    industryTags: ["services", "healthcare", "real-estate", "education", "saas"],
    styleTags: ["minimal", "corporate", "premium"],
    aiUseCases: ["Add the right fields for quote requests, bookings, inquiries, and signups."],
    ai: {
      canGenerate: true,
      guidance: "Use when a page needs user input, validation, and submission intent.",
    },
  },
  {
    id: "premium.content.card-grid",
    type: "cardGrid",
    name: "Feature Card Grid",
    description: "Structured card grid for services, benefits, programs, or feature sets.",
    source: "marketplace",
    category: "content",
    tier: "premium",
    requiredFeature: "premium_widgets",
    allowedPlans: ["pro", "business"],
    marketplaceCategory: "Cards",
    tags: ["cards", "features", "services", "grid"],
    industryTags: ["all"],
    styleTags: ["minimal", "corporate", "editorial", "bold"],
    aiUseCases: ["Turn a business offer into scannable benefit or service cards."],
    ai: {
      canGenerate: true,
      guidance: "Use for pages with repeatable benefits, services, or product capabilities.",
    },
  },
  {
    id: "premium.media.gallery-lightbox",
    type: "galleryLightbox",
    name: "Gallery Lightbox",
    description: "Responsive gallery with categories, captions, and immersive lightbox viewing.",
    source: "marketplace",
    category: "media",
    tier: "premium",
    requiredFeature: "premium_widgets",
    allowedPlans: ["pro", "business"],
    marketplaceCategory: "Gallery",
    tags: ["gallery", "lightbox", "portfolio", "media"],
    industryTags: ["real-estate", "hospitality", "portfolio", "events", "retail"],
    styleTags: ["editorial", "premium", "minimal"],
    aiUseCases: ["Showcase properties, venues, work samples, products, and visual proof."],
    ai: {
      canGenerate: true,
      guidance: "Use when visual browsing is central to conversion or trust.",
    },
  },
  {
    id: "premium.content.faq-accordion",
    type: "faq",
    name: "FAQ Accordion",
    description: "Expandable FAQ section with editable questions, answers, and schema intent.",
    source: "marketplace",
    category: "content",
    tier: "premium",
    requiredFeature: "premium_widgets",
    allowedPlans: ["pro", "business"],
    marketplaceCategory: "FAQ",
    tags: ["faq", "accordion", "seo", "support"],
    industryTags: ["all"],
    styleTags: ["minimal", "corporate", "premium"],
    aiUseCases: ["Answer common objections, reduce support load, and improve SEO coverage."],
    ai: {
      canGenerate: true,
      guidance: "Use near conversion points or on pages with complex offers.",
    },
  },
  {
    id: "premium.social.testimonials",
    type: "testimonials",
    name: "Testimonials",
    description: "Review and testimonial layouts with quotes, ratings, logos, and avatars.",
    source: "marketplace",
    category: "conversion",
    tier: "premium",
    requiredFeature: "premium_widgets",
    allowedPlans: ["pro", "business"],
    marketplaceCategory: "Testimonials",
    tags: ["reviews", "quotes", "social-proof", "ratings"],
    industryTags: ["all"],
    styleTags: ["minimal", "corporate", "editorial", "premium"],
    aiUseCases: ["Add trust-building proof with customer quotes and outcomes."],
    ai: {
      canGenerate: true,
      guidance: "Use on conversion pages after offer or feature sections.",
    },
  },
  {
    id: "premium.pricing.plans",
    type: "pricing",
    name: "Pricing Table",
    description: "Plan comparison section with features, highlights, and CTA routing.",
    source: "marketplace",
    category: "commerce",
    tier: "premium",
    requiredFeature: "commerce_widgets",
    allowedPlans: ["business"],
    marketplaceCategory: "Pricing",
    tags: ["pricing", "plans", "comparison", "checkout"],
    industryTags: ["saas", "membership", "services", "education"],
    styleTags: ["minimal", "corporate", "premium"],
    aiUseCases: ["Present packages, subscriptions, or service tiers with clear comparison."],
    ai: {
      canGenerate: true,
      guidance: "Use when the business sells packages, plans, or subscription tiers.",
    },
  },
  {
    id: "premium.commerce.offer-grid",
    type: "offerGrid",
    name: "Product or Offer Grid",
    description: "Merchandising grid for products, offers, programs, or property listings.",
    source: "marketplace",
    category: "commerce",
    tier: "premium",
    requiredFeature: "commerce_widgets",
    allowedPlans: ["business"],
    marketplaceCategory: "Product or offer grid",
    tags: ["products", "offers", "catalog", "listings"],
    industryTags: ["retail", "real-estate", "education", "hospitality", "services"],
    styleTags: ["minimal", "editorial", "premium", "bold"],
    aiUseCases: ["Create scannable product, package, course, or listing catalogs."],
    ai: {
      canGenerate: true,
      guidance: "Use when the prompt requires multiple sellable or browsable items.",
    },
  },
  {
    id: "premium.contact.floating-whatsapp",
    type: "floatingWhatsApp",
    name: "Floating WhatsApp",
    description: "Persistent WhatsApp contact action with mobile-first placement controls.",
    source: "marketplace",
    category: "conversion",
    tier: "premium",
    requiredFeature: "premium_widgets",
    allowedPlans: ["pro", "business"],
    marketplaceCategory: "WhatsApp button",
    tags: ["whatsapp", "contact", "chat", "floating"],
    industryTags: ["services", "retail", "hospitality", "real-estate", "healthcare"],
    styleTags: ["minimal", "corporate", "premium"],
    aiUseCases: ["Add instant-contact conversion for service and local business websites."],
    ai: {
      canGenerate: true,
      guidance: "Use when direct chat is a key conversion path.",
    },
  },
  {
    id: "premium.location.map",
    type: "locationMap",
    name: "Location Map",
    description: "Map section with address, opening hours, contact details, and route CTA.",
    source: "marketplace",
    category: "data",
    tier: "premium",
    requiredFeature: "premium_widgets",
    allowedPlans: ["pro", "business"],
    marketplaceCategory: "Map",
    tags: ["map", "location", "directions", "local"],
    industryTags: ["restaurant", "retail", "healthcare", "hospitality", "local-services"],
    styleTags: ["minimal", "corporate", "premium"],
    aiUseCases: ["Help local visitors find, contact, or route to a physical business."],
    ai: {
      canGenerate: true,
      guidance: "Use when a business has a physical location or service area.",
    },
  },
  {
    id: "premium.site.footer",
    type: "smartFooter",
    name: "Smart Footer",
    description: "Footer system with link columns, legal links, social links, and newsletter slot.",
    source: "marketplace",
    category: "layout",
    tier: "premium",
    requiredFeature: "premium_widgets",
    allowedPlans: ["pro", "business"],
    marketplaceCategory: "Footer",
    tags: ["footer", "navigation", "legal", "links"],
    industryTags: ["all"],
    styleTags: ["minimal", "corporate", "editorial", "premium"],
    aiUseCases: ["Close generated pages with useful navigation, contact, and compliance links."],
    ai: {
      canGenerate: true,
      guidance: "Use as the final site-wide section for navigation and trust details.",
    },
  },
];
