import { buildEditableMappingIntent } from "./editableMappingIntent";
import { COMPONENT_ENGINE_VERSION_STRING } from "./version";
import type { ComponentVariant } from "./componentVariant";

function variant(input: Omit<ComponentVariant, "version">): ComponentVariant {
  return Object.freeze({ ...input, version: COMPONENT_ENGINE_VERSION_STRING });
}

/**
 * Builds the local metadata-only component variant catalog.
 *
 * @example
 * const catalog = buildComponentCatalog();
 */
export function buildComponentCatalog(): ComponentVariant[] {
  return [
    variant({ id: "HeroEditorialSplit01", label: "Editorial Split Hero", family: "hero", category: "hero", patternIds: ["editorial_hero"], metadata: { reusable: true, compatibleFamilies: ["real_estate", "hospitality", "architecture_interiors", "education", "creative_portfolio"], compatibleArchetypes: ["lead_generation", "brochure", "portfolio", "property_showcase", "hotel_resort"], tags: ["editorial", "premium"], antiPatterns: ["generic SaaS hero"], accessibilityRules: ["clear h1", "visible primary action"], responsiveBehavior: ["media stacks below copy on mobile"] }, requiredFacts: ["primary promise"], requiredAssets: ["hero media if available"], editableMappingIntent: buildEditableMappingIntent("hero", ["eyebrow", "headline", "supportingCopy", "primaryCta", "secondaryCta"], ["heroMedia"]) }),
    variant({ id: "HeroProductValue01", label: "Product Value Hero", family: "hero", category: "hero", patternIds: ["product_value_hero"], metadata: { reusable: true, compatibleFamilies: ["ecommerce_d2c", "technology_saas", "manufacturing_industrial"], compatibleArchetypes: ["ecommerce", "product_launch", "saas", "catalogue"], tags: ["product", "commerce"], antiPatterns: ["unsupported product claims"], accessibilityRules: ["text value proposition"], responsiveBehavior: ["product media remains secondary to CTA"] }, requiredFacts: ["product value proposition"], requiredAssets: ["product imagery if available"], editableMappingIntent: buildEditableMappingIntent("hero", ["headline", "supportingCopy", "primaryCta", "proofText"], ["productMedia"]) }),
    variant({ id: "HeroBookingFocused01", label: "Booking Focused Hero", family: "booking", category: "booking", patternIds: ["booking_hero"], metadata: { reusable: true, compatibleFamilies: ["hospitality", "food_and_beverage", "travel", "automotive"], compatibleArchetypes: ["booking", "hotel_resort", "restaurant_menu", "lead_generation"], tags: ["booking"], antiPatterns: ["fake availability"], accessibilityRules: ["reachable booking action"], responsiveBehavior: ["booking CTA appears early on mobile"] }, requiredFacts: ["booking method"], requiredAssets: [], editableMappingIntent: buildEditableMappingIntent("booking", ["headline", "bookingCta", "availabilityCaution", "supportingCopy"]) }),
    variant({ id: "HeroAppointmentFocused01", label: "Appointment Focused Hero", family: "booking", category: "appointment", patternIds: ["appointment_hero"], metadata: { reusable: true, compatibleFamilies: ["healthcare", "beauty_wellness", "fitness", "professional_services", "legal_finance", "automotive"], compatibleArchetypes: ["appointment", "booking", "lead_generation"], tags: ["appointment"], antiPatterns: ["over-asking before trust"], accessibilityRules: ["clear appointment CTA"], responsiveBehavior: ["appointment action reachable early"] }, requiredFacts: ["appointment process"], requiredAssets: [], editableMappingIntent: buildEditableMappingIntent("appointment", ["headline", "appointmentCta", "supportingCopy", "trustNote"]) }),
    variant({ id: "TrustBandInline01", label: "Inline Trust Band", family: "trust", category: "trust-band", patternIds: ["trust_band"], metadata: { reusable: true, compatibleFamilies: ["healthcare", "real_estate", "education", "automotive", "professional_services", "technology_saas"], compatibleArchetypes: ["lead_generation", "brochure", "appointment", "booking", "catalogue"], tags: ["trust"], antiPatterns: ["fake certifications"], accessibilityRules: ["proof labels readable"], responsiveBehavior: ["compact wrap on mobile"] }, requiredFacts: ["trust signals"], requiredAssets: [], editableMappingIntent: buildEditableMappingIntent("trust-band", ["trustItems", "sourceLabels"]) }),
    variant({ id: "ProofStackCards01", label: "Proof Stack Cards", family: "proof", category: "proof", patternIds: ["proof_stack"], metadata: { reusable: true, compatibleFamilies: ["healthcare", "education", "automotive", "technology_saas", "professional_services", "ngo_community"], compatibleArchetypes: ["lead_generation", "brochure", "appointment", "saas"], tags: ["proof"], antiPatterns: ["fake stats"], accessibilityRules: ["proof hierarchy readable"], responsiveBehavior: ["cards stack cleanly"] }, requiredFacts: ["proof points"], requiredAssets: [], editableMappingIntent: buildEditableMappingIntent("proof", ["proofItems", "sourceLabels"]) }),
    variant({ id: "GalleryMasonryEditorial01", label: "Editorial Masonry Gallery", family: "gallery", category: "gallery", patternIds: ["lifestyle_gallery", "portfolio_showcase"], metadata: { reusable: true, compatibleFamilies: ["real_estate", "hospitality", "food_and_beverage", "architecture_interiors", "creative_portfolio"], compatibleArchetypes: ["portfolio", "property_showcase", "hotel_resort", "restaurant_menu", "brochure"], tags: ["gallery", "editorial"], antiPatterns: ["placeholder imagery"], accessibilityRules: ["meaningful alt text later"], responsiveBehavior: ["avoid burying CTA"] }, requiredFacts: [], requiredAssets: ["gallery images"], editableMappingIntent: buildEditableMappingIntent("gallery", ["caption", "galleryItems"], ["galleryImages"]) }),
    variant({ id: "GalleryLifestyleRail01", label: "Lifestyle Gallery Rail", family: "gallery", category: "gallery", patternIds: ["lifestyle_gallery"], metadata: { reusable: true, compatibleFamilies: ["food_and_beverage", "hospitality", "ecommerce_d2c", "real_estate"], compatibleArchetypes: ["booking", "restaurant_menu", "hotel_resort", "ecommerce"], tags: ["lifestyle"], antiPatterns: ["stock as proof"], accessibilityRules: ["image labels"], responsiveBehavior: ["horizontal rail becomes swipe-safe list"] }, requiredFacts: [], requiredAssets: ["lifestyle images"], editableMappingIntent: buildEditableMappingIntent("gallery", ["galleryItems"], ["lifestyleImages"]) }),
    variant({ id: "ServiceMatrixCards01", label: "Service Matrix Cards", family: "service", category: "service", patternIds: ["service_matrix"], metadata: { reusable: true, compatibleFamilies: ["healthcare", "automotive", "professional_services", "beauty_wellness", "fitness", "construction"], compatibleArchetypes: ["brochure", "appointment", "lead_generation", "catalogue"], tags: ["service"], antiPatterns: ["three consecutive card grids"], accessibilityRules: ["card headings"], responsiveBehavior: ["two-column max on mobile"] }, requiredFacts: ["service list"], requiredAssets: [], editableMappingIntent: buildEditableMappingIntent("service", ["services", "serviceDescriptions", "serviceCtas"]) }),
    variant({ id: "MenuPreviewCards01", label: "Menu Preview Cards", family: "content", category: "menu", patternIds: ["menu_preview"], metadata: { reusable: true, compatibleFamilies: ["food_and_beverage", "hospitality"], compatibleArchetypes: ["restaurant_menu", "booking", "brochure"], tags: ["menu"], antiPatterns: ["invented prices"], accessibilityRules: ["menu text not image-only"], responsiveBehavior: ["short preview before booking CTA"] }, requiredFacts: ["menu items"], requiredAssets: ["food imagery if available"], editableMappingIntent: buildEditableMappingIntent("menu", ["menuItems", "priceCautions", "categoryLabels"], ["foodImages"]) }),
    variant({ id: "CourseCataloguePreview01", label: "Course Catalogue Preview", family: "content", category: "catalogue", patternIds: ["course_catalogue_preview"], metadata: { reusable: true, compatibleFamilies: ["education"], compatibleArchetypes: ["catalogue", "brochure", "lead_generation"], tags: ["education"], antiPatterns: ["fake outcomes"], accessibilityRules: ["course cards scannable"], responsiveBehavior: ["course list before enquiry"] }, requiredFacts: ["programs or courses"], requiredAssets: [], editableMappingIntent: buildEditableMappingIntent("catalogue", ["courses", "courseSummaries", "enquiryCta"]) }),
    variant({ id: "VehicleServiceMatrix01", label: "Vehicle Service Matrix", family: "service", category: "service", patternIds: ["vehicle_service_matrix"], metadata: { reusable: true, compatibleFamilies: ["automotive"], compatibleArchetypes: ["catalogue", "booking", "lead_generation"], tags: ["automotive"], antiPatterns: ["invented inventory"], accessibilityRules: ["terms visible"], responsiveBehavior: ["quick service scan"] }, requiredFacts: ["vehicle services or inventory"], requiredAssets: [], editableMappingIntent: buildEditableMappingIntent("service", ["serviceItems", "termsCaution", "bookingCta"]) }),
    variant({ id: "ProjectShowcaseEditorial01", label: "Editorial Project Showcase", family: "gallery", category: "portfolio", patternIds: ["project_showcase"], metadata: { reusable: true, compatibleFamilies: ["real_estate", "architecture_interiors", "construction"], compatibleArchetypes: ["property_showcase", "portfolio", "lead_generation"], tags: ["project"], antiPatterns: ["fake availability"], accessibilityRules: ["project captions"], responsiveBehavior: ["highlights before CTA"] }, requiredFacts: ["project facts"], requiredAssets: ["project media"], editableMappingIntent: buildEditableMappingIntent("portfolio", ["projectItems", "projectFacts", "cta"], ["projectMedia"]) }),
    variant({ id: "ProductFeatureStack01", label: "Product Feature Stack", family: "commerce", category: "product", patternIds: ["product_feature_stack"], metadata: { reusable: true, compatibleFamilies: ["ecommerce_d2c", "technology_saas", "manufacturing_industrial"], compatibleArchetypes: ["ecommerce", "product_launch", "saas", "catalogue"], tags: ["product"], antiPatterns: ["unsupported feature claims"], accessibilityRules: ["features text-readable"], responsiveBehavior: ["short feature chunks"] }, requiredFacts: ["product features"], requiredAssets: [], editableMappingIntent: buildEditableMappingIntent("product", ["features", "proofNotes", "productCta"]) }),
    variant({ id: "FAQObjectionAccordion01", label: "FAQ Objection Accordion", family: "content", category: "FAQ", patternIds: ["faq_objection_handling"], metadata: { reusable: true, compatibleFamilies: ["healthcare", "real_estate", "food_and_beverage", "education", "automotive", "ecommerce_d2c", "hospitality", "architecture_interiors"], compatibleArchetypes: ["lead_generation", "booking", "appointment", "catalogue", "brochure"], tags: ["faq"], antiPatterns: ["invented answers"], accessibilityRules: ["keyboard-accessible accordion later"], responsiveBehavior: ["near conversion"] }, requiredFacts: ["objections"], requiredAssets: [], editableMappingIntent: buildEditableMappingIntent("FAQ", ["faqItems"]) }),
    variant({ id: "FinalConversionBlock01", label: "Final Conversion Block", family: "conversion", category: "conversion-block", patternIds: ["final_conversion_block"], metadata: { reusable: true, compatibleFamilies: ["healthcare", "real_estate", "food_and_beverage", "education", "automotive", "ecommerce_d2c", "hospitality", "architecture_interiors", "professional_services"], compatibleArchetypes: ["lead_generation", "booking", "appointment", "ecommerce", "brochure"], tags: ["conversion"], antiPatterns: ["aggressive unsupported CTA"], accessibilityRules: ["clear CTA"], responsiveBehavior: ["final action not hidden"] }, requiredFacts: ["primary conversion goal"], requiredAssets: [], editableMappingIntent: buildEditableMappingIntent("conversion-block", ["headline", "supportingCopy", "primaryCta"]) }),
    variant({ id: "StickyMobileCTA01", label: "Sticky Mobile CTA", family: "conversion", category: "sticky-action", patternIds: ["sticky_mobile_cta"], metadata: { reusable: true, compatibleFamilies: ["healthcare", "real_estate", "food_and_beverage", "automotive", "hospitality", "education", "ecommerce_d2c"], compatibleArchetypes: ["lead_generation", "booking", "appointment", "ecommerce", "restaurant_menu"], tags: ["mobile"], antiPatterns: ["obscures content"], accessibilityRules: ["does not trap focus"], responsiveBehavior: ["mobile only intent"] }, requiredFacts: ["primary CTA"], requiredAssets: [], editableMappingIntent: buildEditableMappingIntent("sticky-action", ["ctaLabel", "ctaTarget", "supportingMicrocopy"]) }),
    variant({ id: "FounderStorySplit01", label: "Founder Story Split", family: "content", category: "team", patternIds: ["founder_story"], metadata: { reusable: true, compatibleFamilies: ["architecture_interiors", "creative_portfolio", "ecommerce_d2c", "professional_services", "ngo_community", "education"], compatibleArchetypes: ["portfolio", "brochure", "lead_generation", "product_launch"], tags: ["story"], antiPatterns: ["invented biography"], accessibilityRules: ["readable text"], responsiveBehavior: ["short story before CTA"] }, requiredFacts: ["founder or studio facts"], requiredAssets: ["portrait if provided"], editableMappingIntent: buildEditableMappingIntent("team", ["name", "story", "credentialsCaution"], ["portrait"]) }),
    variant({ id: "ProcessTimeline01", label: "Process Timeline", family: "content", category: "process", patternIds: ["process_timeline"], metadata: { reusable: true, compatibleFamilies: ["architecture_interiors", "professional_services", "education", "construction", "healthcare", "automotive"], compatibleArchetypes: ["brochure", "lead_generation", "appointment"], tags: ["process"], antiPatterns: ["invented process steps"], accessibilityRules: ["linear-readable timeline"], responsiveBehavior: ["steps stack cleanly"] }, requiredFacts: ["process steps"], requiredAssets: [], editableMappingIntent: buildEditableMappingIntent("process", ["steps", "stepDescriptions"]) }),
    variant({ id: "PortfolioShowcaseGrid01", label: "Portfolio Showcase Grid", family: "gallery", category: "portfolio", patternIds: ["portfolio_showcase"], metadata: { reusable: true, compatibleFamilies: ["architecture_interiors", "creative_portfolio", "construction", "professional_services"], compatibleArchetypes: ["portfolio", "brochure", "lead_generation"], tags: ["portfolio"], antiPatterns: ["invented projects"], accessibilityRules: ["captions required later"], responsiveBehavior: ["short highlights"] }, requiredFacts: ["portfolio items"], requiredAssets: ["portfolio media"], editableMappingIntent: buildEditableMappingIntent("portfolio", ["portfolioItems", "captions"], ["portfolioMedia"]) }),
    variant({ id: "ComparisonTableSimple01", label: "Simple Comparison Table", family: "content", category: "comparison", patternIds: ["comparison_section"], metadata: { reusable: true, compatibleFamilies: ["ecommerce_d2c", "automotive", "technology_saas", "education", "manufacturing_industrial"], compatibleArchetypes: ["catalogue", "ecommerce", "saas", "lead_generation"], tags: ["comparison"], antiPatterns: ["invented competitors or specs"], accessibilityRules: ["table semantics later"], responsiveBehavior: ["mobile-readable comparison"] }, requiredFacts: ["comparable options"], requiredAssets: [], editableMappingIntent: buildEditableMappingIntent("comparison", ["comparisonRows", "comparisonColumns", "caveats"]) }),
    variant({ id: "ReviewProofBlock01", label: "Review Proof Block", family: "proof", category: "testimonial", patternIds: ["review_proof_block"], metadata: { reusable: true, compatibleFamilies: ["food_and_beverage", "hospitality", "ecommerce_d2c", "automotive", "professional_services"], compatibleArchetypes: ["booking", "ecommerce", "brochure", "lead_generation"], tags: ["review"], antiPatterns: ["fake testimonials"], accessibilityRules: ["quotes need attribution later"], responsiveBehavior: ["short proof snippets"] }, requiredFacts: ["reviews or testimonials"], requiredAssets: [], editableMappingIntent: buildEditableMappingIntent("testimonial", ["reviews", "attribution", "sourceCaution"]) }),
    variant({ id: "ContactLeadCaptureForm01", label: "Contact Lead Capture Form", family: "conversion", category: "form", patternIds: ["contact_lead_capture"], metadata: { reusable: true, compatibleFamilies: ["healthcare", "real_estate", "education", "automotive", "professional_services", "architecture_interiors"], compatibleArchetypes: ["lead_generation", "appointment", "booking"], tags: ["lead"], antiPatterns: ["too early without trust"], accessibilityRules: ["form labels required later"], responsiveBehavior: ["short mobile form"] }, requiredFacts: ["contact path"], requiredAssets: [], editableMappingIntent: buildEditableMappingIntent("form", ["fields", "privacyNote", "submitLabel"]) }),
    variant({ id: "FooterTrustClosure01", label: "Footer Trust Closure", family: "closure", category: "footer", patternIds: ["footer_trust_closure"], metadata: { reusable: true, compatibleFamilies: ["healthcare", "real_estate", "food_and_beverage", "education", "automotive", "ecommerce_d2c", "hospitality", "architecture_interiors", "technology_saas", "ngo_community"], compatibleArchetypes: ["lead_generation", "brochure", "booking", "appointment", "ecommerce", "portfolio"], tags: ["footer"], antiPatterns: ["invented legal or policy facts"], accessibilityRules: ["navigation landmarks later"], responsiveBehavior: ["compact closure"] }, requiredFacts: ["contact or trust closure facts"], requiredAssets: [], editableMappingIntent: buildEditableMappingIntent("footer", ["contact", "links", "trustNotes", "policyLinks"]) }),
  ];
}
