import type { ComponentVariantCompiler } from "../ComponentVariantCompiler";
import { contentButton, contentColumn, contentContainer, contentGutter, contentHeading, contentId, contentIntent, contentSeed, contentSpacing, contentText, finalizeContentCompilation, mutedSurface, resolveContentCtaPlacement, resolveContentDensity, surface } from "./contentCompilerPrimitives";

export const ServiceMatrixCardsCompiler: ComponentVariantCompiler = Object.freeze({ variantId: "ServiceMatrixCards01", compile(context) {
  const ns = "services", root = contentId(context, "container.service-matrix"), intro = contentId(context, "column.service-intro"), matrixWrap = contentId(context, "column.service-matrix-wrap"), matrix = contentId(context, "container.service-cards"), closing = contentId(context, "column.service-action");
  const density = resolveContentDensity(context, ["services", "serviceItems", "offerings"], 3), ctaPlacement = resolveContentCtaPlacement(context), spacing = contentSpacing(context);
  const rootChildren = [intro, matrixWrap, ...(ctaPlacement === "after-content" ? [closing] : [])];
  const introChildren = [contentId(context,"text.eyebrow"),contentId(context,"heading.headline"),contentId(context,"text.description"),...(ctaPlacement === "intro" ? [contentId(context,"button.services_cta")] : [])];
  const nodes = [
    contentSeed(context,{id:context.sectionNodeId,type:"section",name:"Service matrix",parentId:"page.root",children:[root],props:{role:"services",semanticRole:"service-matrix",purpose:context.section.purpose,componentVariant:"ServiceMatrixCards01",...contentIntent(context,{density,ctaPlacement})},style:{paddingTop:{desktop:spacing,tablet:Math.round(spacing*.75),mobile:Math.round(spacing*.55)},paddingBottom:{desktop:spacing,tablet:Math.round(spacing*.75),mobile:Math.round(spacing*.55)},backgroundColor:surface(context)}}),
    contentSeed(context,{id:root,type:"container",name:`${density.densityLevel} service frame`,parentId:context.sectionNodeId,children:rootChildren,props:{semanticRole:`service-${density.recommendedLayout}`},style:{display:"flex",flexDirection:"column",width:"100%",maxWidth:context.input.designResult?.layoutProfile.maxWidth??"1180px",margin:"0 auto",paddingLeft:{desktop:contentGutter(context),tablet:20,mobile:16},paddingRight:{desktop:contentGutter(context),tablet:20,mobile:16},gap:{desktop:density.densityLevel==="sparse"?48:36,tablet:30,mobile:24}}}),
    contentColumn(context,"column.service-intro",root,introChildren,{gap:14,maxWidth:density.densityLevel==="sparse"?820:720}),contentText(context,ns,intro,"eyebrow","eyebrow"),contentHeading(context,ns,intro,"headline","h2"),contentText(context,ns,intro,"description"),
    ...(ctaPlacement === "intro" ? [contentButton(context,ns,intro,"services_cta")] : []),contentColumn(context,"column.service-matrix-wrap",root,[matrix]),
  ];
  if (density.densityLevel === "dense") {
    const groupCount = 3, groupIds = Array.from({length:groupCount},(_,i)=>contentId(context,`column.service-group-${i+1}`));
    nodes.push(contentContainer(context,"container.service-cards",matrixWrap,groupIds,{display:"grid",gridTemplateColumns:{desktop:"repeat(3, minmax(0, 1fr))",tablet:"1fr 1fr",mobile:"1fr"},gap:20}));
    groupIds.forEach((groupId,groupIndex)=>{const indexes=Array.from({length:Math.ceil((density.itemCount-groupIndex)/groupCount)},(_,i)=>groupIndex+1+i*groupCount).filter(i=>i<=density.itemCount),items=indexes.map(i=>contentId(context,`column.service-item-${i}`));nodes.push(contentColumn(context,`column.service-group-${groupIndex+1}`,matrix,items,{gap:12,padding:{desktop:16,tablet:14,mobile:12},backgroundColor:mutedSurface(context)}));indexes.forEach((itemIndex,i)=>{const role=`item_${itemIndex}`,itemId=items[i];nodes.push(contentColumn(context,`column.service-item-${itemIndex}`,groupId,[contentId(context,`heading.${role}_title`),contentId(context,`text.${role}_description`)],{gap:7,padding:{desktop:14,tablet:12,mobile:10},backgroundColor:surface(context)}),contentHeading(context,ns,itemId,`${role}_title`,`h3`),contentText(context,ns,itemId,`${role}_description`));});});
  } else {
    const count=density.itemCount,items=Array.from({length:count},(_,i)=>contentId(context,`column.service-item-${i+1}`)),columns=density.densityLevel==="sparse"?`repeat(${count}, minmax(0, 1fr))`:"repeat(3, minmax(0, 1fr))";
    nodes.push(contentContainer(context,"container.service-cards",matrixWrap,items,{display:"grid",gridTemplateColumns:{desktop:columns,tablet:"repeat(2, minmax(0, 1fr))",mobile:"1fr"},gap:{desktop:density.densityLevel==="sparse"?28:22,tablet:18,mobile:14}}));items.forEach((itemId,i)=>{const role=`item_${i+1}`;nodes.push(contentColumn(context,`column.service-item-${i+1}`,matrix,[contentId(context,`heading.${role}_title`),contentId(context,`text.${role}_description`)],{gap:10,padding:{desktop:density.densityLevel==="sparse"?32:24,tablet:20,mobile:18},border:`1px solid ${mutedSurface(context)}`,borderRadius:context.input.designResult?.themeProfile.radius??14}),contentHeading(context,ns,itemId,`${role}_title`,`h3`),contentText(context,ns,itemId,`${role}_description`));});
  }
  if(ctaPlacement==="after-content")nodes.push(contentColumn(context,"column.service-action",root,[contentId(context,"button.services_cta")],{alignItems:"flex-start"}),contentButton(context,ns,closing,"services_cta")); return finalizeContentCompilation(nodes);
} });
