import type { ComponentVariantCompiler } from "../ComponentVariantCompiler";
import { contentButton, contentColumn, contentContainer, contentGutter, contentHeading, contentId, contentIntent, contentSeed, contentSpacing, contentText, finalizeContentCompilation, mutedSurface, resolveContentCtaPlacement, resolveContentDensity, surface } from "./contentCompilerPrimitives";

export const VehicleServiceMatrixCompiler: ComponentVariantCompiler = Object.freeze({ variantId:"VehicleServiceMatrix01", compile(context){
  const ns="vehicle_services",root=contentId(context,"container.vehicle-services"),intro=contentId(context,"column.vehicle-intro"),action=contentId(context,"column.booking-action"),groupsWrap=contentId(context,"column.service-groups-wrap"),groups=contentId(context,"container.service-groups"),caution=contentId(context,"column.service-caution");
  const density=resolveContentDensity(context,["vehicleServices","serviceItems","services","offerings"],6),ctaPlacement=resolveContentCtaPlacement(context),spacing=contentSpacing(context),rootChildren=[intro,...(ctaPlacement==="intro"?[action]:[]),groupsWrap,caution,...(ctaPlacement==="after-content"?[action]:[])];
  const nodes=[contentSeed(context,{id:context.sectionNodeId,type:"section",name:"Vehicle service matrix",parentId:"page.root",children:[root],props:{role:"services",semanticRole:"vehicle-service-matrix",purpose:context.section.purpose,componentVariant:"VehicleServiceMatrix01",...contentIntent(context,{density,ctaPlacement})},style:{paddingTop:{desktop:Math.round(spacing*.82),tablet:Math.round(spacing*.68),mobile:Math.round(spacing*.5)},paddingBottom:{desktop:Math.round(spacing*.82),tablet:Math.round(spacing*.68),mobile:Math.round(spacing*.5)},backgroundColor:surface(context)}}),
  contentSeed(context,{id:root,type:"container",name:`${density.densityLevel} vehicle services frame`,parentId:context.sectionNodeId,children:rootChildren,props:{semanticRole:density.densityLevel==="sparse"?"premium-service-selector":"categorized-service-groups"},style:{display:"grid",width:"100%",maxWidth:context.input.designResult?.layoutProfile.maxWidth??"1180px",margin:"0 auto",paddingLeft:{desktop:contentGutter(context),tablet:20,mobile:16},paddingRight:{desktop:contentGutter(context),tablet:20,mobile:16},gridTemplateColumns:{desktop:"1.25fr .75fr",tablet:"1fr 1fr",mobile:"1fr"},gap:{desktop:24,tablet:20,mobile:16},alignItems:"start"}}),
  contentColumn(context,"column.vehicle-intro",root,[contentId(context,"heading.headline"),contentId(context,"text.description")],{gap:14}),contentHeading(context,ns,intro,"headline","h2"),contentText(context,ns,intro,"description"),
  contentColumn(context,"column.booking-action",root,[contentId(context,"text.booking_microcopy"),contentId(context,"button.booking_cta")],{gap:12,padding:{desktop:22,tablet:18,mobile:16},backgroundColor:mutedSurface(context),borderRadius:context.input.designResult?.themeProfile.radius??12}),contentText(context,ns,action,"booking_microcopy","microcopy"),contentButton(context,ns,action,"booking_cta"),
  contentColumn(context,"column.service-groups-wrap",root,[groups],{gridColumn:{desktop:"1 / -1",tablet:"1 / -1",mobile:"auto"}}),
  contentColumn(context,"column.service-caution",root,[contentId(context,"text.terms_caution")],{gridColumn:{desktop:"1 / -1",tablet:"1 / -1",mobile:"auto"},padding:{desktop:18,tablet:16,mobile:14},border:`1px solid ${mutedSurface(context)}`}),contentText(context,ns,caution,"terms_caution","microcopy")];
  if(density.densityLevel==="sparse"){
    const items=Array.from({length:density.itemCount},(_,i)=>contentId(context,`column.service-selector-${i+1}`));nodes.push(contentContainer(context,"container.service-groups",groupsWrap,items,{display:"grid",gridTemplateColumns:{desktop:`repeat(${density.itemCount}, minmax(0, 1fr))`,tablet:"repeat(2, minmax(0, 1fr))",mobile:"1fr"},gap:16}));items.forEach((itemId,i)=>{const role=`service_${i+1}`;nodes.push(contentColumn(context,`column.service-selector-${i+1}`,groups,[contentId(context,`heading.${role}_title`),contentId(context,`text.${role}_scope`)],{gap:8,padding:{desktop:24,tablet:18,mobile:16},border:`1px solid ${mutedSurface(context)}`}),contentHeading(context,ns,itemId,`${role}_title`,`h3`),contentText(context,ns,itemId,`${role}_scope`,`microcopy`));});
  }else{
    const groupCount=density.densityLevel==="dense"?3:2,groupIds=Array.from({length:groupCount},(_,i)=>contentId(context,`column.service-group-${i+1}`));nodes.push(contentContainer(context,"container.service-groups",groupsWrap,groupIds,{display:"grid",gridTemplateColumns:{desktop:`repeat(${groupCount}, minmax(0, 1fr))`,tablet:"1fr 1fr",mobile:"1fr"},gap:18}));groupIds.forEach((groupId,i)=>{const per=Math.ceil(density.itemCount/groupCount),children=[contentId(context,`heading.group_${i+1}_title`),...Array.from({length:per},(_,j)=>contentId(context,`text.group_${i+1}_service_${j+1}`))];nodes.push(contentColumn(context,`column.service-group-${i+1}`,groups,children,{gap:10,padding:{desktop:22,tablet:18,mobile:16},border:`1px solid ${mutedSurface(context)}`}),contentHeading(context,ns,groupId,`group_${i+1}_title`,`h3`),...Array.from({length:per},(_,j)=>contentText(context,ns,groupId,`group_${i+1}_service_${j+1}`)));});
  } return finalizeContentCompilation(nodes);
} });
