"use client";
import Link from "next/link";
import { ArrowRight, Globe2, Plus, Sparkles, Users, WandSparkles } from "lucide-react";
import { useWorkspace } from "../components/WorkspaceContext";
import CopilotPromptCard from "../components/CopilotPromptCard";

export default function GlobalDashboardPage() {
 const {websites,loading}=useWorkspace();
 return <div className="mx-auto max-w-[1450px] pb-12">
  <div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="flex items-center gap-2 text-sm dashboard-muted"><Sparkles size={14}/> Workspace overview</p><h1 className="mt-1 text-2xl font-semibold tracking-tight">Welcome back</h1><p className="mt-1 text-sm dashboard-muted">Manage your websites and start something new.</p></div><Link href="/app/onboarding" className="flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-medium text-white hover:bg-blue-500"><Plus size={16}/> New website</Link></div>
  <section className="grid gap-4 sm:grid-cols-3"><Summary tone="blue" icon={Globe2} value={String(websites.length)} label="Active websites"/><Summary tone="cyan" icon={Users} value="2.4k" label="Total visitors"/><Summary tone="amber" icon={WandSparkles} value="38" label="AI generations"/></section>
  <section className="mt-5 grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><CopilotPromptCard/><div className="dashboard-card rounded-2xl p-5 sm:p-6"><div className="flex items-center gap-2"><Sparkles size={17} className="text-blue-500"/><h2 className="font-semibold">Quick start</h2></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><Quick title="Create with AI" text="Describe your business and generate a complete site."/><Quick title="Choose a template" text="Start with a professionally designed layout."/><Quick title="Import a website" text="Bring an existing site into your workspace."/><Quick title="Invite your team" text="Collaborate with editors and designers."/></div></div></section>
  <section className="mt-8"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-lg font-semibold">Your websites</h2><p className="mt-1 text-xs dashboard-muted">Recently edited projects</p></div><Link href="/app/workspace/websites" className="text-xs font-medium text-blue-600 dark:text-blue-400">View all</Link></div>
  {loading?<p className="text-sm dashboard-muted">Loading websites…</p>:websites.length===0?<div className="dashboard-card rounded-2xl p-10 text-center"><Globe2 className="mx-auto dashboard-faint"/><h3 className="mt-3 font-medium">No websites yet</h3><p className="mt-1 text-sm dashboard-muted">Create your first website with AI or a template.</p><Link href="/app/onboarding" className="mt-5 inline-flex rounded-xl bg-blue-600 px-4 py-2 text-sm text-white">Create website</Link></div>:<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{websites.map((site:any)=><Link key={site.id} href={`/app/${site.slug}/dashboard`} className="dashboard-card group overflow-hidden rounded-2xl"><div className="flex h-36 items-center justify-center bg-gradient-to-br from-blue-500/10 via-indigo-500/5 to-transparent"><Globe2 className="h-9 w-9 text-blue-500/60"/></div><div className="flex items-center p-4"><div><h3 className="font-medium">{site.name}</h3><p className="mt-1 text-xs dashboard-muted">{site.slug}.buildez.site</p></div><ArrowRight className="ml-auto h-4 w-4 dashboard-faint transition group-hover:translate-x-1"/></div></Link>)}</div>}</section>
 </div>
}
function Summary({icon:Icon,value,label,tone}:{icon:any;value:string;label:string;tone:string}){return <div className={`dashboard-card workspace-summary workspace-summary-${tone} flex items-center gap-4 rounded-2xl p-5`}><span className="workspace-summary-icon flex h-10 w-10 items-center justify-center rounded-xl"><Icon size={18}/></span><div><p className="text-xl font-semibold">{value}</p><p className="text-xs dashboard-muted">{label}</p></div></div>}
function Quick({title,text}:{title:string;text:string}){return <button className="dashboard-control rounded-xl border dashboard-border p-4 text-left dashboard-hover"><p className="text-sm font-semibold">{title}</p><p className="mt-1 text-xs leading-5 dashboard-muted">{text}</p></button>}
