import type { CreativeFragmentFamily } from "./creativeFragment";

export const CREATIVE_FRAGMENT_FAMILIES: CreativeFragmentFamily[] = [
  "layout",
  "grid",
  "spacing",
  "typography",
  "background",
  "media",
  "cta",
  "motion",
  "interaction",
  "scroll",
  "card",
  "navigation",
  "proof",
  "form",
  "footer",
  "responsive",
  "accessibility",
];

export const MINIMUM_FRAGMENT_FAMILY_COUNTS: Record<CreativeFragmentFamily, number> = Object.freeze({
  layout: 20,
  grid: 10,
  spacing: 20,
  typography: 20,
  background: 20,
  media: 20,
  cta: 20,
  motion: 20,
  interaction: 10,
  scroll: 10,
  card: 10,
  navigation: 10,
  proof: 10,
  form: 10,
  footer: 10,
  responsive: 10,
  accessibility: 10,
});
