export function createBuilderRuntimeScript(sessionId: string) {
  return `(() => {
  "use strict";
  const VERSION=1, SESSION=${JSON.stringify(sessionId)}, SELECTOR="[data-buildez-id]";
  const parentOriginParam=new URLSearchParams(location.search).get("__buildez_parent_origin");
  const referrerOrigin=document.referrer?new URL(document.referrer).origin:"";
  const PARENT_ORIGIN=parentOriginParam&&/^https?:\\/\\//.test(parentOriginParam)?new URL(parentOriginParam).origin:referrerOrigin;
  let edit=false, hovered=null, selected=null, editing=null,refreshFrame=0,lastBounds="";
  const markerStyle=document.createElement("style");markerStyle.dataset.buildezOverlay="markers";markerStyle.textContent='html[data-buildez-mode="edit"] [data-buildez-selected="true"]{outline:2px solid #2563eb!important;outline-offset:-2px!important}html[data-buildez-mode="edit"] [data-buildez-parent-selected="true"]{outline:1px dashed #8b5cf6!important;outline-offset:-3px!important}html[data-buildez-mode="edit"] [data-buildez-hovered="true"]:not([data-buildez-selected="true"]){outline:1px solid #60a5fa!important;outline-offset:-1px!important}';document.head.append(markerStyle);
  const hoverBox=box("hover"), parentBox=box("parent"), selectedBox=box("selected");
  function box(kind){const selectedKind=kind==="selected",parentKind=kind==="parent";const el=document.createElement("div");el.dataset.buildezOverlay=kind;Object.assign(el.style,{position:"fixed",zIndex:selectedKind?"2147483646":parentKind?"2147483644":"2147483645",pointerEvents:"none",display:"none",border:selectedKind?"2px solid #3b82f6":parentKind?"1px dashed #a78bfa":"1px solid #60a5fa",background:parentKind?"rgba(139,92,246,.035)":"transparent",boxShadow:selectedKind?"0 0 0 1px rgba(255,255,255,.85)":""});const label=document.createElement("span");Object.assign(label.style,{position:"absolute",left:"-1px",top:"-22px",padding:"3px 7px",borderRadius:"4px 4px 0 0",background:parentKind?"#7c3aed":"#2563eb",color:"#fff",font:"600 11px/16px ui-sans-serif,system-ui",whiteSpace:"nowrap"});el.append(label);document.documentElement.append(el);return el}
  function post(type,payload={}){if(PARENT_ORIGIN)parent.postMessage({version:VERSION,sessionId:SESSION,type,payload},PARENT_ORIGIN)}
  function target(value){return value instanceof Element?value.closest(SELECTOR):null}
  function bounds(el){const r=el.getBoundingClientRect();return {top:r.top,left:r.left,width:r.width,height:r.height}}
  function data(el){const parent=el.parentElement&&el.parentElement.closest(SELECTOR),style=getComputedStyle(el);const styleNames=["display","position","width","height","minWidth","maxWidth","minHeight","maxHeight","marginTop","marginRight","marginBottom","marginLeft","paddingTop","paddingRight","paddingBottom","paddingLeft","gap","flexDirection","alignItems","justifyContent","fontFamily","fontSize","fontWeight","lineHeight","letterSpacing","textAlign","color","backgroundColor","borderColor","borderWidth","borderStyle","borderRadius","boxShadow","opacity","overflow","zIndex"];const computedStyleSummary=Object.fromEntries(styleNames.map(name=>[name,style[name]||""]));return {elementId:el.dataset.buildezId,kind:el.dataset.buildezKind||"element",tagName:el.tagName.toLowerCase(),sourceFile:el.dataset.buildezSourceFile,sourceAnchor:el.dataset.buildezSourceAnchor,parentElementId:parent?.dataset.buildezId,textContent:(el.innerText||"").slice(0,2000),className:typeof el.className==="string"?el.className:"",attributes:{id:el.id||"",src:el.getAttribute("src")||"",alt:el.getAttribute("alt")||"",href:el.getAttribute("href")||"","data-buildez-source":el.getAttribute("data-buildez-source")||"","data-buildez-source-id":el.getAttribute("data-buildez-source-id")||"","data-buildez-presentation":el.getAttribute("data-buildez-presentation")||"","data-buildez-limit":el.getAttribute("data-buildez-limit")||"","data-buildez-field":el.getAttribute("data-buildez-field")||""},computedStyleSummary,editableCapabilities:(el.dataset.buildezCapabilities||"").split(",").filter(Boolean),projectRevision:Number(el.dataset.buildezRevision||0),bounds:bounds(el)}}
  function mark(name,el){document.querySelectorAll("["+name+'="true"]').forEach(node=>node.removeAttribute(name));if(edit&&el)el.setAttribute(name,"true")}
  function syncMarkers(){const parentElement=selected?.parentElement?.closest(SELECTOR)||null;mark("data-buildez-hovered",hovered);mark("data-buildez-parent-selected",parentElement);mark("data-buildez-selected",selected)}
  function paint(box,el,labelPrefix=""){if(!edit||!el||!document.contains(el)){box.style.display="none";return}const r=el.getBoundingClientRect();Object.assign(box.style,{display:"block",transform:"translate("+r.left+"px,"+r.top+"px)",width:r.width+"px",height:r.height+"px"});box.firstElementChild.textContent=labelPrefix+el.tagName.toLowerCase()}
  function refresh(){refreshFrame=0;syncMarkers();paint(hoverBox,hovered);const parentElement=selected?.parentElement?.closest(SELECTOR)||null;paint(parentBox,parentElement,"parent · ");paint(selectedBox,selected);if(selected){const payload=data(selected),signature=JSON.stringify(payload.bounds);if(signature!==lastBounds){lastBounds=signature;post("BUILDEZ_ELEMENT_BOUNDS_CHANGED",payload)}}else lastBounds=""}
  function scheduleRefresh(){if(!refreshFrame)refreshFrame=requestAnimationFrame(refresh)}
  document.addEventListener("pointerover",e=>{if(!edit||editing)return;const next=target(e.target);if(next===hovered)return;hovered=next;scheduleRefresh();if(next)post("BUILDEZ_ELEMENT_HOVERED",data(next))},true);
  document.addEventListener("pointerout",e=>{if(!edit)return;if(target(e.relatedTarget)===hovered)return;hovered=null;scheduleRefresh()},true);
  document.addEventListener("click",e=>{if(!edit)return;const next=target(e.target);if(!next)return;e.preventDefault();e.stopPropagation();selected=next;scheduleRefresh();post("BUILDEZ_ELEMENT_SELECTED",data(selected))},true);
  document.addEventListener("dblclick",e=>{if(!edit)return;const next=target(e.target);if(!next||(next.dataset.buildezCapabilities||"").split(",").indexOf("text")<0)return;e.preventDefault();editing=next;next.contentEditable="true";next.focus();document.execCommand("selectAll",false);},true);
  document.addEventListener("keydown",e=>{if(e.key==="Escape"&&editing){editing.textContent=editing.dataset.buildezOriginal||editing.textContent;finish(false)}if((e.metaKey||e.ctrlKey)&&e.key==="Enter"&&editing)finish(true)},true);
  document.addEventListener("focusin",e=>{if(editing===e.target)editing.dataset.buildezOriginal=editing.textContent||""},true);
  document.addEventListener("focusout",e=>{if(editing===e.target)finish(true)},true);
  function finish(commit){if(!editing)return;const el=editing;el.contentEditable="false";editing=null;if(commit)post("BUILDEZ_INLINE_EDIT_COMMITTED",{...data(el),value:el.textContent||""})}
  addEventListener("message",e=>{if(!PARENT_ORIGIN||e.origin!==PARENT_ORIGIN||e.source!==parent)return;const m=e.data;if(!m||m.version!==VERSION||m.sessionId!==SESSION)return;
    if(m.type==="BUILDEZ_EDIT_MODE_CHANGED"){edit=m.payload?.mode==="edit";document.documentElement.dataset.buildezMode=edit?"edit":"preview";if(!edit){hovered=null;selected=null}scheduleRefresh()}
    else if(m.type==="BUILDEZ_REQUEST_PARENT_SELECTION"&&selected){const p=selected.parentElement?.closest(SELECTOR);if(p){selected=p;scheduleRefresh();post("BUILDEZ_ELEMENT_SELECTED",data(p))}}
    else if(m.type==="BUILDEZ_SELECTION_CLEARED"){selected=null;scheduleRefresh();post("BUILDEZ_SELECTION_CLEARED",{})}
    else if(m.type==="BUILDEZ_SCROLL_TO_ELEMENT"&&selected)selected.scrollIntoView({behavior:"smooth",block:"center"})
  });
  new ResizeObserver(scheduleRefresh).observe(document.documentElement);
  new MutationObserver(records=>{if(records.some(record=>!(record.target instanceof Element)||!record.target.closest("[data-buildez-overlay]")))scheduleRefresh()}).observe(document.documentElement,{subtree:true,childList:true,attributes:true,attributeFilter:["class","src","hidden"]});
  addEventListener("scroll",scheduleRefresh,true);addEventListener("resize",scheduleRefresh);
  post("BUILDEZ_PREVIEW_READY",{route:location.pathname});post("BUILDEZ_ROUTE_CHANGED",{route:location.pathname});
})();`;
}
