import type { BuilderBlueprint, BuilderNode } from "../../../types/blueprint";
import { deserializeBlueprint, serializeBlueprint } from "../../../core/serialization";
import { PremiumWidgetDefinitions } from "../../../widgets/premium";
import { discoverNativeWidgetMediaSlots } from "../../../ai-v10/media/nativeWidgetMediaSlots";
import { policyFor } from "./industryRolePolicies";
import { WidgetPopulationRegistry } from "./WidgetPopulationRegistry";

export type NativeWidgetPopulationFailure = Readonly<{ widgetId:string;widgetType:string;sectionId:string;code:string;message:string;requiredPath?:string;observedValue:unknown;recoveryAttempted:boolean;recoveryOutcome:string }>;
export type NativeWidgetPopulationGateResult = Readonly<{
  totalWidgets:number;fullyPopulatedWidgets:number;partiallyPopulatedWidgets:number;defaultDrivenWidgets:string[];widgetsWithMissingRequiredProps:string[];widgetsWithMissingRequiredMedia:string[];widgetsWithDuplicateCopy:string[];industryIncompatibleWidgets:string[];roleIncompatibleWidgets:string[];unsafeFactualWidgets:string[];widgetsWithRendererShapeMismatch:string[];failures:readonly NativeWidgetPopulationFailure[];passed:boolean;persistenceExact:boolean;
}>;
export type NativeWidgetPopulationGateInput = Readonly<{ blueprint:BuilderBlueprint; populationProvenance?:unknown; hydrationDiagnostics?:unknown; mediaAssignmentDiagnostics?:unknown; businessContext?:Readonly<Record<string,unknown>>; knownFacts?:Readonly<Record<string,unknown>>; missingFacts?:readonly unknown[] }>;

const empty=(value:unknown)=>value===undefined||value===null||value===""||(Array.isArray(value)&&!value.length);
const demo=/my first site|your company|first item|second item|lorem ipsum|placeholder|add a clear|describe this step|see it in action|ready to customize/i;
const strings=(value:unknown):string[]=>typeof value==="string"?[value]:Array.isArray(value)?value.flatMap(strings):value&&typeof value==="object"?Object.values(value as Record<string,unknown>).flatMap(strings):[];
const push=(failures:NativeWidgetPopulationFailure[],node:BuilderNode,code:string,message:string,requiredPath?:string,observedValue:unknown=node.props)=>failures.push({widgetId:node.id,widgetType:node.type,sectionId:node.parentId??"",code,message,requiredPath,observedValue,recoveryAttempted:false,recoveryOutcome:"not-attempted"});
const normalized=(value:string)=>value.toLowerCase().normalize("NFKD").replace(/[^a-z0-9\s]/g," ").replace(/\s+/g," ").trim();
const unavoidable=new Set(["contact","learn more","submit"]);
function majorCopy(node:BuilderNode){const props=node.props??{};const values:Array<{path:string;value:string}>=[];const add=(path:string,value:unknown)=>{if(typeof value!=="string")return;const fingerprint=normalized(value);if(fingerprint&&fingerprint.length>=4&&!unavoidable.has(fingerprint))values.push({path,value});};add("props.title",props.title);if(["hero","cta"].includes(node.type))add("props.primaryCta",props.primaryCta);if(node.type==="smartFooter")add("props.body",props.body);for(const [key,field] of [["slides","title"],["steps","title"],["questions","question"]] as const){const collection=props[key];if(Array.isArray(collection))collection.forEach((item,index)=>add(`props.${key}[${index}].${field}`,item&&typeof item==="object"?(item as Record<string,unknown>)[field]:undefined));}return values;}

function persistenceExact(blueprint:BuilderBlueprint){const saved=serializeBlueprint(blueprint);if(!saved.ok)return false;const loaded=deserializeBlueprint(saved.value);if(!loaded.ok)return false;return Object.values(blueprint.nodes).filter((node)=>WidgetPopulationRegistry.has(node.type)).every((node)=>JSON.stringify(loaded.value.nodes[node.id]?.props)===JSON.stringify(node.props));}

export function runNativeWidgetPopulationGate(input:NativeWidgetPopulationGateInput):NativeWidgetPopulationGateResult {
  const widgets=Object.values(input.blueprint.nodes).filter((node)=>WidgetPopulationRegistry.has(node.type)); const failures:NativeWidgetPopulationFailure[]=[];
  const defaults=new Map(PremiumWidgetDefinitions.map((definition)=>[definition.type,definition.defaultNode.props]));
  const defaultDriven=new Set<string>(),missingProps=new Set<string>(),missingMedia=new Set<string>(),duplicates=new Set<string>(),industry=new Set<string>(),role=new Set<string>(),unsafe=new Set<string>(),shape=new Set<string>();
  const family=String((input.businessContext?.businessFamily??input.businessContext?.industry??"unknown")); const policy=policyFor(family); const known=input.knownFacts??{};
  for(const node of widgets){const contract=WidgetPopulationRegistry.get(node.type)!;const props=node.props??{};
    for(const path of contract.requiredProps)if(empty(props[path])){missingProps.add(node.id);push(failures,node,"missing-required-prop",`${path} is required.`,`props.${path}`,props[path]);}
    for(const path of contract.rendererPropShape.filter((path)=>contract.requiredProps.includes(path)))if(!(path in props)){shape.add(node.id);push(failures,node,"renderer-shape-mismatch",`Renderer-required ${path} is absent.`,`props.${path}`,undefined);}
    const registered=defaults.get(node.type)??{};for(const [key,value] of Object.entries(props))if(JSON.stringify(value)===JSON.stringify(registered[key])||strings(value).some((text)=>demo.test(text))){defaultDriven.add(node.id);push(failures,node,"default-or-demo-driven",`${key} contains registered default or demo content.`,`props.${key}`,value);break;}
    for(const fact of contract.requiredVerifiedFacts)if(empty(known[fact])){unsafe.add(node.id);push(failures,node,"verified-fact-missing",`${fact} is required and may not be fabricated.`,`knownFacts.${fact}`,known[fact]);}
    if(policy.forbid.includes(node.type)||contract.disallowedBusinessFamilies.includes(family)){industry.add(node.id);push(failures,node,"industry-incompatible",`${node.type} is forbidden for ${family}.`,"businessContext.businessFamily",family);}
  }
  for(const slot of discoverNativeWidgetMediaSlots(input.blueprint))if(slot.required&&slot.assignmentStatus!=="assigned"){missingMedia.add(slot.widgetId);const node=input.blueprint.nodes[slot.widgetId];if(node)push(failures,node,"required-media-missing",`${slot.slotPath} is unresolved.`,slot.slotPath,"");}
  const copyUses=new Map<string,Array<{widgetId:string;path:string;value:string}>>();for(const node of widgets)for(const item of majorCopy(node)){const fingerprint=normalized(item.value);copyUses.set(fingerprint,[...(copyUses.get(fingerprint)??[]),{widgetId:node.id,path:item.path,value:item.value}]);}for(const [fingerprint,uses] of copyUses){const ids=[...new Set(uses.map((use)=>use.widgetId))];if(ids.length<2)continue;ids.forEach((id)=>duplicates.add(id));for(const id of ids){const node=input.blueprint.nodes[id];const use=uses.find((item)=>item.widgetId===id);if(node&&use)push(failures,node,"duplicate-major-copy",`Major copy conflicts across unrelated widgets: ${ids.join(", ")}.`,use.path,{normalizedFingerprint:fingerprint,conflictingWidgetIds:ids,originalValue:use.value});}}
  const persisted=persistenceExact(input.blueprint);if(!persisted)failures.push({widgetId:"blueprint",widgetType:"blueprint",sectionId:"",code:"persistence-mismatch",message:"Nested props do not survive serialization/reload exactly.",requiredPath:"nodes.*.props",observedValue:"round-trip mismatch",recoveryAttempted:false,recoveryOutcome:"hard-failure"});
  const failedIds=new Set(failures.filter((failure)=>failure.widgetId!=="blueprint").map((failure)=>failure.widgetId));
  return Object.freeze({totalWidgets:widgets.length,fullyPopulatedWidgets:widgets.length-failedIds.size,partiallyPopulatedWidgets:failedIds.size,defaultDrivenWidgets:[...defaultDriven],widgetsWithMissingRequiredProps:[...missingProps],widgetsWithMissingRequiredMedia:[...missingMedia],widgetsWithDuplicateCopy:[...duplicates],industryIncompatibleWidgets:[...industry],roleIncompatibleWidgets:[...role],unsafeFactualWidgets:[...unsafe],widgetsWithRendererShapeMismatch:[...shape],failures:Object.freeze(failures),passed:failures.length===0,persistenceExact:persisted});
}

export function enforceNativeWidgetPopulationGate(input:NativeWidgetPopulationGateInput){
  const initial=runNativeWidgetPopulationGate(input);if(initial.passed)return {blueprint:input.blueprint,gate:initial,diagnostics:{...initial,eligibleWidgets:initial.totalWidgets,omittedOptionalWidgets:[],replacementAttempts:0,repopulationAttempts:0},replacedWidgets:[],omittedSections:[],repopulationAttempts:0,replacementAttempts:0};
  const nodes={...input.blueprint.nodes};const replacements:Array<{widgetId:string;from:string;to:string;reason:string}>=[];for(const failure of initial.failures){if(failure.code!=="verified-fact-missing"||failure.widgetType!=="floatingWhatsApp")continue;const node=nodes[failure.widgetId];if(!node)continue;const {whatsappNumber:_,...props}=node.props??{};nodes[node.id]={...node,type:"cta",name:"Contact CTA",props:{...props,variant:"conversion",generationCapability:"cta"}};replacements.push({widgetId:node.id,from:"floatingWhatsApp",to:"cta",reason:"Verified WhatsApp destination is unavailable; preserve the contact purpose without a fabricated destination."});}
  const replacedIds=new Set(replacements.map((item)=>item.widgetId));const essential=new Set(["hero","leadForm","cta","smartFooter","smartHeader"]);const removable=new Set(initial.failures.filter((failure)=>["verified-fact-missing","required-media-missing"].includes(failure.code)&&!essential.has(failure.widgetType)&&!replacedIds.has(failure.widgetId)).map((failure)=>failure.widgetId));
  const omittedSections:string[]=[];const omittedWidgets:string[]=[];const removeTree=(id:string)=>{const node=nodes[id];if(!node)return;node.children.forEach(removeTree);delete nodes[id];};for(const widgetId of removable){const widget=nodes[widgetId];const section=widget?.parentId?nodes[widget.parentId]:undefined;if(!widget||!section||section.type!=="section")continue;const parent=section.parentId?nodes[section.parentId]:undefined;removeTree(section.id);if(parent)nodes[parent.id]={...parent,children:parent.children.filter((id)=>id!==section.id)};omittedSections.push(section.id);omittedWidgets.push(widgetId);}
  const blueprint={...input.blueprint,nodes};const gate=runNativeWidgetPopulationGate({...input,blueprint});const recovered=new Set([...omittedWidgets,...replacedIds]);const failures=[...gate.failures,...initial.failures.filter((failure)=>recovered.has(failure.widgetId)).map((failure)=>({...failure,recoveryAttempted:true,recoveryOutcome:replacedIds.has(failure.widgetId)?"role-correct-replacement:cta":"optional-section-omitted"}))];const diagnostics={...gate,totalWidgets:initial.totalWidgets,eligibleWidgets:initial.totalWidgets,omittedOptionalWidgets:omittedWidgets,replacementAttempts:replacements.length,repopulationAttempts:0,failures,passed:gate.passed};return {blueprint,gate:{...gate,failures:gate.failures},diagnostics,replacedWidgets:replacements,omittedSections,repopulationAttempts:0,replacementAttempts:replacements.length};
}
