import type { BuilderBlueprint, BuilderNode } from "../../types/blueprint";

export type RenderedViewport = "desktop" | "tablet" | "mobile";
export type RenderedScreenshot = Readonly<{ viewport: RenderedViewport; width: number; height: number; pixels: Uint8Array; pixelFormat: "rgba"; source?: string }>;
export type RenderedVisualIssueCategory = "composition" | "typography" | "imagery" | "hierarchy" | "originality" | "responsive";
export type RenderedVisualIssue = Readonly<{ id: string; category: RenderedVisualIssueCategory; severity: "low" | "medium" | "high"; message: string; viewport?: RenderedViewport; affectedNodeIds: readonly string[] }>;
export type RenderedVisualRepairActionType = "increase_hero_scale" | "replace_repetitive_grid" | "change_section_archetype" | "increase_whitespace" | "adjust_media_dominance" | "improve_typography_hierarchy";
export type RenderedVisualRepairAction = Readonly<{ id: string; type: RenderedVisualRepairActionType; sectionId?: string; nodeIds: readonly string[]; instruction: string; expectedScoreGain: number; deterministic: true }>;
export type RenderedVisualEvaluation = Readonly<{ compositionScore:number;typographyScore:number;imageryScore:number;hierarchyScore:number;originalityScore:number;responsiveScore:number;issues:readonly RenderedVisualIssue[];repairActions:readonly RenderedVisualRepairAction[];passed:boolean;pixelInspected:true;viewports:readonly RenderedViewport[] }>;

const clamp=(value:number)=>Math.max(0,Math.min(100,Math.round(value)));
function nodes(blueprint:BuilderBlueprint,type?:BuilderNode["type"]){const values=Object.values(blueprint.nodes);return type?values.filter((node)=>node.type===type):values;}
function sample(screenshot:RenderedScreenshot){
  if(screenshot.pixelFormat!=="rgba"||screenshot.pixels.length<screenshot.width*screenshot.height*4)throw new Error(`RENDERED_SCREENSHOT_INVALID: ${screenshot.viewport}`);
  const step=Math.max(4,Math.floor((screenshot.width*screenshot.height)/18000)*4);const colors=new Set<number>();let luminance=0,luminanceSquare=0,edges=0,count=0,transparent=0,previous=-1;
  for(let index=0;index<screenshot.pixels.length;index+=step){const r=screenshot.pixels[index]??0,g=screenshot.pixels[index+1]??0,b=screenshot.pixels[index+2]??0,a=screenshot.pixels[index+3]??255;const light=.2126*r+.7152*g+.0722*b;luminance+=light;luminanceSquare+=light*light;if(previous>=0&&Math.abs(light-previous)>32)edges++;previous=light;if(a<230)transparent++;colors.add(((r>>4)<<8)|((g>>4)<<4)|(b>>4));count++;}
  const mean=luminance/Math.max(1,count),variance=Math.max(0,luminanceSquare/Math.max(1,count)-mean*mean);
  return{colorDiversity:Math.min(1,colors.size/180),contrast:Math.min(1,Math.sqrt(variance)/72),edgeDensity:edges/Math.max(1,count),transparentRatio:transparent/Math.max(1,count)};
}
function issue(id:string,category:RenderedVisualIssueCategory,severity:RenderedVisualIssue["severity"],message:string,nodeIds:readonly string[]=[],viewport?:RenderedViewport):RenderedVisualIssue{return Object.freeze({id,category,severity,message,viewport,affectedNodeIds:Object.freeze([...nodeIds])});}
function action(id:string,type:RenderedVisualRepairActionType,instruction:string,nodeIds:readonly string[]=[],sectionId?:string,gain=8):RenderedVisualRepairAction{return Object.freeze({id,type,instruction,nodeIds:Object.freeze([...nodeIds]),sectionId,expectedScoreGain:gain,deterministic:true});}
function sectionFor(blueprint:BuilderBlueprint,node?:BuilderNode){let current=node;while(current&&current.type!=="section")current=current.parentId?blueprint.nodes[current.parentId]:undefined;return current;}

export function evaluateRenderedVisualQuality(input:{blueprint:BuilderBlueprint;screenshots:readonly RenderedScreenshot[]}):RenderedVisualEvaluation{
  const required:RenderedViewport[]=["desktop","tablet","mobile"];const captures=new Map(input.screenshots.map((item)=>[item.viewport,item]));for(const viewport of required)if(!captures.has(viewport))throw new Error(`RENDERED_SCREENSHOT_MISSING: ${viewport}`);
  const signals=required.map((viewport)=>({viewport,...sample(captures.get(viewport)!)}));const sections=nodes(input.blueprint,"section"),headings=nodes(input.blueprint,"heading"),images=nodes(input.blueprint,"image"),containers=nodes(input.blueprint,"container");const issues:RenderedVisualIssue[]=[];
  const avg=(key:"colorDiversity"|"contrast"|"edgeDensity")=>signals.reduce((sum,item)=>sum+item[key],0)/signals.length;
  const sectionSpacing=sections.map((node)=>Number(typeof node.style.paddingTop==="object"?(node.style.paddingTop as Record<string,unknown>).desktop:node.style.paddingTop)||0);const spacingKinds=new Set(sectionSpacing.map((value)=>Math.round(value/16))).size;
  const gridSignatures=containers.map((node)=>JSON.stringify(node.style.gridTemplateColumns??"")).filter(Boolean);const dominantGrid=gridSignatures.length?Math.max(...[...new Set(gridSignatures)].map((value)=>gridSignatures.filter((item)=>item===value).length))/gridSignatures.length:0;
  const compositionScore=clamp(58+spacingKinds*7+(1-dominantGrid)*22+avg("edgeDensity")*18);if(compositionScore<75)issues.push(issue("rendered.composition.flat","composition","high","Rendered sections have repetitive geometry or insufficient rhythm.",containers.map((node)=>node.id)));
  const fontSizes=headings.map((node)=>Number(typeof node.style.fontSize==="object"?(node.style.fontSize as Record<string,unknown>).desktop:node.style.fontSize)||0);const scaleRange=fontSizes.length?Math.max(...fontSizes)-Math.min(...fontSizes):0;const typographyScore=clamp(58+Math.min(22,scaleRange*.45)+avg("contrast")*24);if(typographyScore<75)issues.push(issue("rendered.typography.flat","typography","medium","Rendered typography lacks sufficient scale or contrast hierarchy.",headings.map((node)=>node.id)));
  const completeImages=images.filter((node)=>String(node.props.src??"").trim()).length;const imageryScore=clamp(48+Math.min(24,completeImages*5)+avg("colorDiversity")*28);if(imageryScore<75)issues.push(issue("rendered.imagery.weak","imagery","medium","Imagery lacks dominance, completeness, or visual range.",images.map((node)=>node.id)));
  const heroSection=sections[0],heroHeadings=headings.filter((node)=>sectionFor(input.blueprint,node)?.id===heroSection?.id);const heroScale=Math.max(0,...heroHeadings.map((node)=>Number(typeof node.style.fontSize==="object"?(node.style.fontSize as Record<string,unknown>).desktop:node.style.fontSize)||0));const hierarchyScore=clamp(52+Math.min(24,heroScale*.32)+avg("contrast")*18+Math.min(10,sections.length));if(hierarchyScore<78)issues.push(issue("rendered.hierarchy.weak-hero","hierarchy","high","The rendered hero does not establish sufficient visual dominance.",heroHeadings.map((node)=>node.id)));
  const silhouettes=containers.map((node)=>`${node.style.display??"block"}:${JSON.stringify(node.style.gridTemplateColumns??node.style.flexDirection??"")}`);const originalityScore=clamp(48+(new Set(silhouettes).size/Math.max(1,silhouettes.length))*38+avg("colorDiversity")*16);if(originalityScore<72)issues.push(issue("rendered.originality.repetition","originality","high","The rendered page repeats too few visual silhouettes.",containers.map((node)=>node.id)));
  const aspectValidity=signals.every((item)=>item.viewport==="mobile"?captures.get(item.viewport)!.width<=600:item.viewport==="tablet"?captures.get(item.viewport)!.width<=1100:captures.get(item.viewport)!.width>=1100);const signalDrift=Math.max(...signals.map((item)=>item.edgeDensity))-Math.min(...signals.map((item)=>item.edgeDensity));const responsiveScore=clamp((aspectValidity?76:48)+Math.max(0,20-signalDrift*80));if(responsiveScore<80)issues.push(issue("rendered.responsive.drift","responsive","high","Viewport renders do not preserve a stable responsive hierarchy.",[],"mobile"));
  const repairActions:RenderedVisualRepairAction[]=[];if(hierarchyScore<78)repairActions.push(action("visual-repair.hero-scale","increase_hero_scale","Increase hero heading scale and tighten its line height.",heroHeadings.map((node)=>node.id),heroSection?.id,10));if(compositionScore<75){repairActions.push(action("visual-repair.whitespace","increase_whitespace","Increase section whitespace to restore open and dense beats.",sections.map((node)=>node.id),undefined,8));repairActions.push(action("visual-repair.grid","replace_repetitive_grid","Vary repeated grid tracks and promote one featured item.",containers.map((node)=>node.id),undefined,9));}if(originalityScore<72)repairActions.push(action("visual-repair.archetype","change_section_archetype","Change one repeated middle section to an asymmetric narrative archetype.",[],sections[Math.floor(sections.length/2)]?.id,12));if(imageryScore<75)repairActions.push(action("visual-repair.media","adjust_media_dominance","Increase the dominant media area and vary image aspect ratios.",images.map((node)=>node.id),undefined,9));if(typographyScore<75)repairActions.push(action("visual-repair.type","improve_typography_hierarchy","Increase heading scale contrast while preserving one H1.",headings.map((node)=>node.id),undefined,8));
  return Object.freeze({compositionScore,typographyScore,imageryScore,hierarchyScore,originalityScore,responsiveScore,issues:Object.freeze(issues),repairActions:Object.freeze(repairActions),passed:compositionScore>=75&&typographyScore>=75&&imageryScore>=75&&hierarchyScore>=78&&originalityScore>=72&&responsiveScore>=80,pixelInspected:true,viewports:Object.freeze(required)});
}

export const RenderedVisualQualityGate=Object.freeze({evaluate:evaluateRenderedVisualQuality});

