"use client";
/* eslint-disable @typescript-eslint/no-explicit-any, @typescript-eslint/no-unused-expressions */
import { useEffect, useState } from "react";
import { ArrowRight, CheckCircle2, ChevronLeft, Loader2, Minus, Package, Plus, Search, ShieldCheck, ShoppingBag, Trash2, X } from "lucide-react";
import { AnalyticsTracker, trackAnalyticsEvent } from "@/modules/analytics/AnalyticsTracker";
type Variant={id:string;title:string;price:string;compareAtPrice?:string;inventory:number;sku?:string};type Product={id:string;title:string;handle:string;description:string;storySections?:{title:string;body:string;imageUrl?:string}[];images:{url:string;alt?:string}[];variants:Variant[]};type Line={product:Product;variant:Variant;quantity:number};
export default function Storefront({lookup}:{lookup:{siteSlug?:string;domain?:string;path?:string[]}}){
 const [data,setData]=useState<any>(),[error,setError]=useState(""),[query,setQuery]=useState(""),[cart,setCart]=useState<Line[]>([]),[cartOpen,setCartOpen]=useState(false),[selected,setSelected]=useState<Product>(),[galleryIndex,setGalleryIndex]=useState(0),[variantId,setVariantId]=useState(""),[checkout,setCheckout]=useState(false),[complete,setComplete]=useState<number>();
 useEffect(()=>{const q=lookup.domain?`domain=${encodeURIComponent(lookup.domain)}`:`siteSlug=${encodeURIComponent(lookup.siteSlug||"")}`;fetch(`/api/public/shopez/store?${q}`).then(async r=>{const body=await r.json();if(!r.ok)throw new Error(body.error);setData(body)}).catch(reason=>setError(reason.message))},[lookup.domain,lookup.siteSlug]);
 useEffect(()=>{if(!data)return;const [kind,value]=lookup.path||[];if(kind==="products"){const product=data.shop.products.find((item:Product)=>item.handle===value);setSelected(product);setVariantId(product?.variants[0]?.id||"");setGalleryIndex(0)}if(kind==="cart")setCartOpen(true);if(kind==="checkout")setCheckout(true)},[data,lookup.path]);
 const count=cart.reduce((sum,item)=>sum+item.quantity,0),subtotal=cart.reduce((sum,item)=>sum+Number(item.variant.price)*item.quantity,0);
 function openProduct(product:Product){setSelected(product);setVariantId(product.variants[0]?.id||"");setGalleryIndex(0)}
 function add(product:Product,variant=product.variants.find(item=>item.id===variantId)||product.variants[0]){if(!variant)return;setCart(items=>{const found=items.find(item=>item.variant.id===variant.id);return found?items.map(item=>item.variant.id===variant.id?{...item,quantity:item.quantity+1}:item):[...items,{product,variant,quantity:1}]});setSelected(undefined);setCartOpen(true)}
 function quantity(id:string,value:number){setCart(items=>items.map(item=>item.variant.id===id?{...item,quantity:Math.max(1,value)}:item))}
 if(error)return <div className="grid min-h-screen place-items-center bg-stone-50 p-8 text-center"><div><Package className="mx-auto text-orange-500"/><h1 className="mt-4 text-2xl font-bold">Store unavailable</h1><p className="mt-2 text-stone-500">{error}</p></div></div>;
 if(!data)return <div className="grid min-h-screen place-items-center"><Loader2 className="animate-spin text-orange-500"/></div>;
 const category=lookup.path?.[0]==="category"?data.shop.collections.find((item:any)=>item.handle===lookup.path?.[1]):undefined;
 const categoryIds=new Set((category?.products||[]).map((item:any)=>item.productId));
 const products=(data.shop.products as Product[]).filter(product=>(!category||categoryIds.has(product.id))&&product.title.toLowerCase().includes(query.toLowerCase()));
 const selectedVariant=selected?.variants.find(item=>item.id===variantId)||selected?.variants[0];
 return <div className="min-h-screen bg-[#fffaf4] text-[#241a12]"><AnalyticsTracker siteId={data.site.id}/>
  <div className="bg-[#241a12] px-4 py-2 text-center text-xs text-white">Secure checkout · Live inventory · Easy order tracking</div>
  <header className="sticky top-0 z-20 border-b border-orange-950/10 bg-[#fffaf4]/90 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center gap-5 px-5 py-4"><a href={`/store/${data.site.slug}`} className="text-2xl font-black text-orange-500">{data.shop.name}</a><nav className="ml-6 hidden gap-5 text-sm md:flex"><a href={`/store/${data.site.slug}`}>Shop all</a>{data.shop.collections.slice(0,3).map((item:any)=><a key={item.id} href={`/store/${data.site.slug}/category/${item.handle}`}>{item.title}</a>)}</nav><label className="relative ml-auto hidden sm:block"><Search className="absolute left-3 top-2.5 text-stone-400" size={16}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search products" className="rounded-full border bg-white py-2 pl-9 pr-4 text-sm"/></label><button onClick={()=>setCartOpen(true)} className="relative rounded-full bg-[#241a12] p-3 text-white"><ShoppingBag size={18}/>{count>0&&<span className="absolute -right-1 -top-1 grid h-5 w-5 place-items-center rounded-full bg-orange-500 text-[10px]">{count}</span>}</button></div></header>
  <main><section className="mx-auto grid max-w-7xl items-center gap-10 px-5 py-16 md:grid-cols-2"><div><p className="font-semibold uppercase tracking-[.2em] text-orange-500">{category?.title||"ShopEZ collection"}</p><h1 className="mt-5 text-5xl font-black leading-[.95] tracking-[-.06em] md:text-7xl">{category?.title||"Products worth bringing home."}</h1><p className="mt-6 max-w-lg text-lg text-stone-600">{category?.description||"Live products, pricing, inventory, and collections powered by your ShopEZ catalog."}</p><a href="#products" className="mt-8 inline-flex items-center gap-2 rounded-full bg-orange-500 px-6 py-3 font-semibold text-white">Shop now <ArrowRight size={17}/></a></div><div className="aspect-[4/3] overflow-hidden rounded-[2.5rem] bg-orange-100">{products[0]?.images[0]?<img src={products[0].images[0].url} alt={products[0].title} className="h-full w-full object-cover"/>:<ShoppingBag className="m-auto h-full w-24 text-orange-300"/>}</div></section>
  <section id="products" className="mx-auto max-w-7xl px-5 py-16"><div className="flex items-end justify-between"><div><p className="text-sm font-semibold text-orange-500">{category?"CATEGORY":"SHOP ALL"}</p><h2 className="mt-2 text-3xl font-black">{category?.title||"The collection"}</h2></div><span className="text-sm text-stone-500">{products.length} products</span></div><div className="mt-8 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{products.map(product=><article key={product.id} className="group cursor-pointer" onClick={()=>openProduct(product)}><div className="relative aspect-[4/5] overflow-hidden rounded-3xl bg-orange-100">{product.images[0]?<img src={product.images[0].url} alt={product.images[0].alt||product.title} className="h-full w-full object-cover transition group-hover:scale-105"/>:<Package className="m-auto h-full text-orange-300"/>}<button onClick={event=>{event.stopPropagation();add(product,product.variants[0])}} className="absolute bottom-3 right-3 rounded-full bg-white p-3 shadow"><Plus size={18}/></button></div><h3 className="mt-4 font-bold">{product.title}</h3><p className="mt-1 font-semibold text-orange-600">{data.shop.currency} {Number(product.variants[0]?.price||0).toLocaleString()}</p></article>)}</div></section>
  <section className="bg-[#241a12] px-5 py-20 text-center text-white"><ShieldCheck className="mx-auto text-orange-400"/><h2 className="mt-4 text-3xl font-black">Checkout with confidence.</h2><p className="mx-auto mt-3 max-w-xl text-stone-300">Secure payments, live totals, discounts, tax, shipping and order tracking are built in.</p></section></main>
  {selected&&<div className="fixed inset-0 z-40 grid place-items-center overflow-y-auto bg-black/50 p-4" onMouseDown={event=>event.target===event.currentTarget&&setSelected(undefined)}><div className="grid max-h-[92vh] w-full max-w-5xl overflow-y-auto rounded-3xl bg-white md:grid-cols-2"><div className="p-4"><div className="aspect-square overflow-hidden rounded-2xl bg-orange-50">{selected.images[galleryIndex]&&<img src={selected.images[galleryIndex].url} alt={selected.images[galleryIndex].alt||selected.title} className="h-full w-full object-cover"/>}</div><div className="mt-3 grid grid-cols-5 gap-2">{selected.images.map((image,index)=><button key={`${image.url}-${index}`} onClick={()=>setGalleryIndex(index)} className={`aspect-square overflow-hidden rounded-xl border-2 ${galleryIndex===index?"border-orange-500":"border-transparent"}`}><img src={image.url} alt={`Preview ${index+1}`} className="h-full w-full object-cover"/></button>)}</div></div><div className="relative p-8"><button onClick={()=>setSelected(undefined)} className="absolute right-5 top-5"><X/></button><p className="text-xs font-bold text-orange-500">{selectedVariant?.inventory?"IN STOCK":"OUT OF STOCK"}</p><h2 className="mt-3 text-3xl font-black">{selected.title}</h2><p className="mt-4 whitespace-pre-wrap leading-7 text-stone-600">{selected.description}</p>{selected.variants.length>1&&<div className="mt-5"><p className="text-xs font-bold uppercase text-stone-500">Choose option</p><div className="mt-2 flex flex-wrap gap-2">{selected.variants.map(variant=><button key={variant.id} onClick={()=>setVariantId(variant.id)} className={`rounded-full border px-4 py-2 text-sm ${variantId===variant.id?"border-orange-500 bg-orange-50":"border-stone-200"}`}>{variant.title}</button>)}</div></div>}<div className="mt-6 flex items-baseline gap-3"><p className="text-2xl font-bold">{data.shop.currency} {Number(selectedVariant?.price||0).toLocaleString()}</p>{selectedVariant?.compareAtPrice&&<del className="text-stone-400">{data.shop.currency} {Number(selectedVariant.compareAtPrice).toLocaleString()}</del>}</div>{selectedVariant?.sku&&<p className="mt-1 text-xs text-stone-400">SKU {selectedVariant.sku}</p>}<button disabled={!selectedVariant?.inventory} onClick={()=>add(selected,selectedVariant)} className="mt-6 w-full rounded-full bg-orange-500 py-3 font-bold text-white disabled:bg-stone-300">Add to cart</button>{(selected.storySections||[]).map((section,index)=><article key={`${section.title}-${index}`} className="mt-7 border-t pt-6">{section.imageUrl&&<img src={section.imageUrl} alt="" className="mb-4 aspect-video w-full rounded-2xl object-cover"/>}<h3 className="text-xl font-black">{section.title}</h3><p className="mt-2 leading-7 text-stone-600">{section.body}</p></article>)}</div></div></div>}
  {cartOpen&&<div className="fixed inset-0 z-50 bg-black/40" onMouseDown={event=>event.target===event.currentTarget&&setCartOpen(false)}><aside className="ml-auto flex h-full w-full max-w-md flex-col bg-white p-6"><div className="flex items-center"><h2 className="text-xl font-black">Your cart ({count})</h2><button onClick={()=>setCartOpen(false)} className="ml-auto"><X/></button></div><div className="mt-6 flex-1 space-y-4 overflow-y-auto">{cart.map(item=><div key={item.variant.id} className="flex gap-3 border-b pb-4"><div className="h-20 w-16 overflow-hidden rounded-xl bg-orange-50">{item.product.images[0]&&<img src={item.product.images[0].url} alt="" className="h-full w-full object-cover"/>}</div><div className="flex-1"><p className="font-bold">{item.product.title}</p><p className="text-sm text-stone-500">{item.variant.title} · {data.shop.currency} {Number(item.variant.price).toLocaleString()}</p><div className="mt-2 flex items-center gap-2"><button onClick={()=>quantity(item.variant.id,item.quantity-1)}><Minus size={14}/></button><span>{item.quantity}</span><button onClick={()=>quantity(item.variant.id,item.quantity+1)}><Plus size={14}/></button></div></div><button onClick={()=>setCart(items=>items.filter(value=>value.variant.id!==item.variant.id))}><Trash2 size={16}/></button></div>)}{!cart.length&&<p className="py-20 text-center text-stone-500">Your cart is empty.</p>}</div>{cart.length>0&&<div className="border-t pt-5"><div className="flex text-lg font-bold"><span>Subtotal</span><span className="ml-auto">{data.shop.currency} {subtotal.toLocaleString()}</span></div><button onClick={()=>{setCartOpen(false);setCheckout(true)}} className="mt-5 w-full rounded-full bg-orange-500 py-3 font-bold text-white">Checkout</button></div>}</aside></div>}
  {checkout&&<Checkout data={data} cart={cart} close={()=>setCheckout(false)} complete={number=>{trackAnalyticsEvent(data.site.id,"conversion",{orderNumber:number});setComplete(number);setCart([]);setCheckout(false)}}/>}
  {complete&&<div className="fixed inset-0 z-[60] grid place-items-center bg-[#fffaf4] p-6 text-center"><div><CheckCircle2 className="mx-auto h-16 w-16 text-emerald-500"/><h2 className="mt-5 text-3xl font-black">Order confirmed!</h2><p className="mt-2 text-stone-500">Your order number is #{complete}.</p><button onClick={()=>setComplete(undefined)} className="mt-6 rounded-full bg-orange-500 px-6 py-3 font-bold text-white">Continue shopping</button></div></div>}
 </div>
}
function Checkout({data,cart,close,complete}:{data:any;cart:Line[];close:()=>void;complete:(n:number)=>void}){const [form,setForm]=useState<any>({email:"",firstName:"",lastName:"",phone:"",address1:"",city:"",state:"",postalCode:"",country:data.shop.country,discountCode:"",provider:data.shop.payments[0]?.provider||"COD"}),[busy,setBusy]=useState(false),[error,setError]=useState("");async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');const origin=location.origin+location.pathname;const r=await fetch('/api/public/shopez/checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,siteId:data.site.id,items:cart.map(x=>({variantId:x.variant.id,quantity:x.quantity})),shippingAddress:{firstName:form.firstName,lastName:form.lastName,address1:form.address1,city:form.city,state:form.state,postalCode:form.postalCode,country:form.country},returnUrl:origin,cancelUrl:origin})});const b=await r.json();setBusy(false);if(!r.ok)return setError(b.error||'Checkout failed');if(b.provider==='COD')return complete(b.orderNumber);if(b.provider==='PAYPAL'){localStorage.setItem('shopez-paypal-order',b.orderId);location.href=b.approvalUrl;return}const win=window as any;if(!win.Razorpay){const s=document.createElement('script');s.src='https://checkout.razorpay.com/v1/checkout.js';await new Promise((ok,no)=>{s.onload=ok;s.onerror=no;document.head.appendChild(s)})}new win.Razorpay({key:b.publicKey,amount:b.amount,currency:b.currency,order_id:b.paymentOrderId,name:data.shop.name,handler:async(p:any)=>{const v=await fetch('/api/public/shopez/payments/verify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({orderId:b.orderId,paymentOrderId:p.razorpay_order_id,paymentId:p.razorpay_payment_id,signature:p.razorpay_signature})});const result=await v.json();result.success?complete(result.orderNumber):setError(result.error)}}).open()}
 return <div className="fixed inset-0 z-50 overflow-y-auto bg-[#fffaf4]"><div className="mx-auto max-w-3xl p-5 py-10"><button onClick={close} className="flex items-center gap-2 text-sm"><ChevronLeft size={16}/>Back to cart</button><h2 className="mt-6 text-3xl font-black">Checkout</h2><form onSubmit={submit} className="mt-7 grid gap-5 md:grid-cols-2"><section className="space-y-3 rounded-3xl bg-white p-6 md:col-span-2"><h3 className="font-bold">Contact & delivery</h3><input required type="email" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} className="w-full rounded-xl border p-3"/><div className="grid gap-3 sm:grid-cols-2">{[['firstName','First name'],['lastName','Last name'],['phone','Phone'],['address1','Address'],['city','City'],['state','State'],['postalCode','PIN / postal code'],['country','Country']].map(([k,l])=><input required={k!=='phone'} key={k} placeholder={l} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})} className="rounded-xl border p-3"/>)}</div></section><section className="rounded-3xl bg-white p-6"><h3 className="font-bold">Discount</h3><input placeholder="Discount code" value={form.discountCode} onChange={e=>setForm({...form,discountCode:e.target.value})} className="mt-3 w-full rounded-xl border p-3 uppercase"/></section><section className="rounded-3xl bg-white p-6"><h3 className="font-bold">Payment</h3><div className="mt-3 space-y-2">{data.shop.payments.map((x:any)=><label key={x.provider} className="flex gap-2"><input type="radio" name="provider" checked={form.provider===x.provider} onChange={()=>setForm({...form,provider:x.provider})}/>{x.provider==='COD'?'Cash on delivery':x.provider}</label>)}</div></section>{error&&<p className="text-rose-500 md:col-span-2">{error}</p>}<button disabled={busy} className="rounded-full bg-orange-500 py-4 font-bold text-white md:col-span-2">{busy?'Preparing secure checkout…':'Place order securely'}</button></form></div></div>}
