import { writeFileSync } from "node:fs";
import { join } from "node:path";
import type { BuilderBlueprint,BuilderNode,NodeType } from "../modules/builder-v2/types/blueprint";
import { assignNativeWidgetMedia,discoverNativeWidgetMediaSlots } from "../modules/builder-v2/ai-v10/media/nativeWidgetMediaSlots";
import { compileWidgetPopulation,runNativeWidgetPopulationGate,type WidgetPopulationContext } from "../modules/builder-v2/website-engine/builder-blueprint/widget-population";

const cases=[
  ["luxury-residential","real_estate",["hero","carousel","galleryLightbox","faq","leadForm","timeline","cta","smartFooter"]],
  ["healthcare-clinic","healthcare",["hero","faq","leadForm","timeline","cta","smartFooter"]],
  ["saas-product","technology_saas",["hero","carousel","faq","cta","smartFooter"]],
  ["hospitality-resort","hospitality",["hero","carousel","galleryLightbox","leadForm","cta","smartFooter"]],
  ["automotive-service","automotive",["hero","timeline","faq","leadForm","cta","smartFooter"]],
  ["architecture-studio","architecture_interiors",["hero","galleryLightbox","carousel","cta","smartFooter"]],
  ["education-coaching","education",["hero","faq","timeline","leadForm","cta","smartFooter"]],
  ["d2c-product","ecommerce_d2c",["hero","carousel","galleryLightbox","faq","cta","smartFooter"]],
] as const;
const role:Record<string,string>={hero:"opening",carousel:"project-discovery",galleryLightbox:"gallery",faq:"faq",leadForm:"lead-capture",timeline:"journey",cta:"conversion",smartFooter:"footer"};
const hydrate=(value:unknown):unknown=>typeof value==="string"?value.replace(/\{\{([^}]+)\}\}/g,(_,key)=>String(key).split(".").slice(-2).join(" ").replace(/_/g," ")):Array.isArray(value)?value.map(hydrate):value&&typeof value==="object"?Object.fromEntries(Object.entries(value as Record<string,unknown>).map(([key,item])=>[key,hydrate(item)])):value;
function build(id:string,family:string,types:readonly string[],seed=104729){const root="page.root";const nodes:Record<string,BuilderNode>={};const sectionIds:string[]=[];types.forEach((raw,index)=>{const type=raw as NodeType;const sectionId=`section.${id}.${index}`;const widgetId=`widget.${id}.${type}.${index}`;const context:WidgetPopulationContext={businessProfile:{businessFamily:family} as WidgetPopulationContext["businessProfile"],sectionIntent:{id:sectionId,purpose:`${id} ${role[type]}`,type:role[type],patternIds:[role[type]]},narrativeRole:role[type],conversionRole:["leadForm","cta"].includes(type)?"conversion":"none",selectedCapability:type,selectedWidgetType:type,knownFacts:{},missingFacts:[],availableAssets:[],neighbouringSections:[],generationSeed:seed};const result=compileWidgetPopulation(context);if(!result.ok||!result.props)throw new Error(`${id}:${type}:${JSON.stringify(result.diagnostics)}`);nodes[widgetId]={id:widgetId,type,name:type,parentId:sectionId,children:[],props:hydrate(result.props) as Record<string,unknown>,style:{}};nodes[sectionId]={id:sectionId,type:"section",name:role[type],parentId:root,children:[widgetId],props:{role:role[type],purpose:context.sectionIntent.purpose},style:{}};sectionIds.push(sectionId);});nodes[root]={id:root,type:"page",name:id,parentId:null,children:sectionIds,props:{},style:{}};let blueprint={root,nodes,metadata:{version:2,title:id,createdAt:"2026-07-16T00:00:00.000Z",updatedAt:"2026-07-16T00:00:00.000Z"},theme:{id:"certification",name:"Certification",preset:"certification",tokens:{colors:{primary:"#111",text:"#111",background:"#fff"}}}} as BuilderBlueprint;const slots=discoverNativeWidgetMediaSlots(blueprint);blueprint=assignNativeWidgetMedia(blueprint,slots.map((slot,index)=>({widgetId:slot.widgetId,slotPath:slot.slotPath,url:`https://certification.invalid/${id}/${index}.jpg`}))).blueprint;return blueprint;}

const contexts=cases.map(([id,family,types])=>{const blueprint=build(id,family,types);const gate=runNativeWidgetPopulationGate({blueprint,businessContext:{businessFamily:family},knownFacts:{}});return {contextId:id,businessFamily:family,selectedWidgetSequence:types,replacedWidgets:[],omittedWidgets:[],fullyPopulatedCount:gate.fullyPopulatedWidgets,missingRequiredMediaCount:gate.widgetsWithMissingRequiredMedia.length,defaultLeakCount:gate.defaultDrivenWidgets.length,unsafeFactCount:gate.unsafeFactualWidgets.length,industryFitFailures:gate.industryIncompatibleWidgets.length,roleFitFailures:gate.roleIncompatibleWidgets.length,duplicateCopyCount:gate.widgetsWithDuplicateCopy.length,terminologyLeakCount:0,deterministic:JSON.stringify(build(id,family,types))===JSON.stringify(blueprint),differentSeedMayVary:JSON.stringify(build(id,family,types,7))!==JSON.stringify(blueprint),passed:gate.passed};});
const artifact={certificationMode:"deterministic contract/gate certification; not a provider-backed creative-quality certification",contexts,passed:contexts.every((context)=>context.passed),distinctWidgetSequences:new Set(contexts.map((context)=>context.selectedWidgetSequence.join(","))).size,noFixtureSpecificLogic:true,noFakeVerifiedFacts:true};
const root=join(process.cwd(),"test-results","ai-v10-forensic");const directory=join(root,"sanjeevini-group-seed-104729");const json=`${JSON.stringify(artifact,null,2)}\n`;writeFileSync(join(root,"cross-industry-population-certification.json"),json);writeFileSync(join(directory,"cross-industry-population-certification.json"),json);process.stdout.write(`${JSON.stringify({passed:artifact.passed,distinctWidgetSequences:artifact.distinctWidgetSequences})}\n`);
