import type { NodeType } from "../../types/blueprint";
import type { WidgetProperty } from "../../types/property";
import { WidgetDefinition } from "../../core/registry/WidgetRegistry";
import PremiumWidget from "./PremiumWidget";

type PremiumWidgetSeed = {
  type: NodeType;
  name: string;
  category: WidgetDefinition["category"];
  icon: string;
  eyebrow: string;
  title: string;
  body: string;
  primaryCta: string;
  secondaryCta?: string;
  items: string[];
  aiPrompt: string;
};

const sharedProperties: WidgetProperty[] = [
  {
    id: "eyebrow",
    label: "Eyebrow",
    type: "text",
    target: "props",
    category: "content",
    aiEditable: true,
  },
  {
    id: "title",
    label: "Title",
    type: "text",
    target: "props",
    category: "content",
    aiEditable: true,
  },
  {
    id: "body",
    label: "Body",
    type: "textarea",
    target: "props",
    category: "content",
    aiEditable: true,
  },
  {
    id: "primaryCta",
    label: "Primary CTA",
    type: "text",
    target: "props",
    category: "content",
    aiEditable: true,
  },
  {
    id: "secondaryCta",
    label: "Secondary CTA",
    type: "text",
    target: "props",
    category: "content",
    aiEditable: true,
  },
  {
    id: "items",
    label: "Items",
    type: "textarea",
    target: "props",
    category: "content",
    placeholder: "One item per line",
    aiEditable: true,
  },
  {
    id: "variant",
    label: "Variant",
    type: "select",
    target: "props",
    category: "content",
    defaultValue: "default",
    options: [
      { label: "Default", value: "default" },
      { label: "Compact", value: "compact" },
      { label: "Editorial", value: "editorial" },
      { label: "Conversion", value: "conversion" },
    ],
  },
  {
    id: "backgroundColor",
    label: "Background",
    type: "color",
    target: "style",
    category: "style",
    defaultValue: "#ffffff",
    themeTokenReady: true,
  },
  {
    id: "color",
    label: "Text Color",
    type: "color",
    target: "style",
    category: "style",
    defaultValue: "#0f172a",
    themeTokenReady: true,
  },
  {
    id: "borderRadius",
    label: "Radius",
    type: "slider",
    target: "style",
    category: "style",
    defaultValue: 16,
    min: 0,
    max: 40,
    step: 1,
    unit: "px",
    units: ["px", "rem"],
    themeTokenReady: true,
  },
  {
    id: "padding",
    label: "Padding",
    type: "spacing",
    target: "style",
    category: "layout",
    responsive: true,
    themeTokenReady: true,
  },
  {
    id: "gap",
    label: "Gap",
    type: "slider",
    target: "style",
    category: "layout",
    defaultValue: 16,
    min: 0,
    max: 80,
    step: 1,
    unit: "px",
    units: ["px", "rem", "vw"],
    responsive: true,
    themeTokenReady: true,
  },
  {
    id: "ariaLabel",
    label: "Accessibility Label",
    type: "text",
    target: "props",
    category: "advanced",
    aiEditable: true,
  },
  {
    id: "motionPreset",
    label: "Motion Preset",
    type: "select",
    target: "props",
    category: "animation",
    defaultValue: "none",
    options: [
      { label: "None", value: "none" },
      { label: "Fade", value: "fade" },
      { label: "Slide", value: "slide" },
      { label: "Scale", value: "scale" },
      { label: "Reveal", value: "reveal" },
      { label: "Parallax metadata", value: "parallax" },
    ],
    description: "Builder metadata only. No runtime animation execution in BSP-15.",
  },
  {
    id: "hideOnMobile",
    label: "Hide on Mobile",
    type: "switch",
    target: "props",
    category: "responsive",
    defaultValue: false,
  },
];

const premiumWidgetSeeds: PremiumWidgetSeed[] = [
  {
    type: "smartHeader",
    name: "Smart Header",
    category: "marketing",
    icon: "Menu",
    eyebrow: "Navigation",
    title: "Smart Header",
    body: "Responsive navigation with logo, menu links, CTA, and mobile drawer behavior.",
    primaryCta: "Book a call",
    secondaryCta: "View pages",
    items: ["Logo area", "Menu links", "Primary CTA", "Mobile drawer"],
    aiPrompt: "Use for production-ready navigation with brand, links, and conversion CTA.",
  },
  {
    type: "hero",
    name: "Conversion Hero",
    category: "marketing",
    icon: "Sparkles",
    eyebrow: "Project decision path",
    title: "A sharper first screen for serious buyers",
    body: "A cinematic hero with clear positioning, proof cues, real imagery, and a direct route to enquiry.",
    primaryCta: "Explore projects",
    secondaryCta: "Book a site visit",
    items: ["Location fit", "Construction proof", "Visit path", "Project clarity"],
    aiPrompt: "Use for landing page hero sections that need clear offer, trust, and action.",
  },
  {
    type: "leadForm",
    name: "Lead Capture Form",
    category: "forms",
    icon: "FileText",
    eyebrow: "Enquiry desk",
    title: "Route every visit into a useful conversation",
    body: "A clean enquiry flow for project interest, site-visit timing, budget fit, and callback requests.",
    primaryCta: "Send enquiry",
    items: ["Name", "Phone", "Preferred project", "Site visit timing"],
    aiPrompt: "Use when a page needs contact, quote, booking, appointment, or waitlist collection.",
  },
  {
    type: "cardGrid",
    name: "Feature Card Grid",
    category: "marketing",
    icon: "PanelsTopLeft",
    eyebrow: "Buyer checkpoints",
    title: "Make the important details easy to compare",
    body: "Structured cards for project fit, delivery confidence, amenities, approvals, and next steps.",
    primaryCta: "Compare details",
    items: ["Site-visit readiness", "Delivery context", "Project comparison", "Enquiry route"],
    aiPrompt: "Use for repeatable benefit, service, program, or product capability sections.",
  },
  {
    type: "galleryLightbox",
    name: "Gallery Lightbox",
    category: "media",
    icon: "Images",
    eyebrow: "Built proof",
    title: "Show the project environment before a visit",
    body: "A visual proof section for exterior massing, arrival spaces, amenities, finishes, and lifestyle context.",
    primaryCta: "View project gallery",
    items: ["Exterior approach", "Arrival court", "Interior finish", "Amenity view"],
    aiPrompt: "Use when images are central to trust, inspection, or conversion.",
  },
  {
    type: "faq",
    name: "FAQ Accordion",
    category: "marketing",
    icon: "CircleHelp",
    eyebrow: "FAQ",
    title: "Answer common questions",
    body: "Expandable answers for objections, support questions, and SEO coverage.",
    primaryCta: "Ask a question",
    items: ["Pricing", "Timeline", "Process", "Support"],
    aiPrompt: "Use near conversion points or on complex offer pages to answer objections.",
  },
  {
    type: "testimonials",
    name: "Testimonials",
    category: "marketing",
    icon: "Star",
    eyebrow: "Trust signals",
    title: "Confidence should be visible before the form",
    body: "A proof block for delivered work, buyer guidance, construction updates, and commitment clarity.",
    primaryCta: "See proof points",
    items: ["Delivered work", "Ongoing pipeline", "Buyer guidance", "Commitment clarity"],
    aiPrompt: "Use after offer sections to increase trust with quotes, ratings, and outcomes.",
  },
  {
    type: "pricing",
    name: "Pricing Table",
    category: "commerce",
    icon: "BadgeDollarSign",
    eyebrow: "Pricing",
    title: "Choose the right plan",
    body: "Plan comparison with features, highlights, and conversion routing.",
    primaryCta: "Choose plan",
    items: ["Starter", "Pro", "Business", "Custom"],
    aiPrompt: "Use when the business sells packages, plans, memberships, or subscription tiers.",
  },
  {
    type: "offerGrid",
    name: "Product or Offer Grid",
    category: "commerce",
    icon: "ShoppingBag",
    eyebrow: "Project choices",
    title: "Surface the right project path for each visitor",
    body: "A browsable grid for residential, commercial, mixed-use, and site-visit enquiry options.",
    primaryCta: "View projects",
    items: ["Residential project", "Commercial brief", "Mixed-use enquiry", "Site visit option"],
    aiPrompt: "Use when the prompt requires multiple sellable or browsable items.",
  },
  {
    type: "floatingWhatsApp",
    name: "Floating WhatsApp",
    category: "marketing",
    icon: "MessageCircle",
    eyebrow: "Chat",
    title: "Floating WhatsApp",
    body: "Persistent WhatsApp contact action with mobile-first placement controls.",
    primaryCta: "Chat on WhatsApp",
    items: ["Mobile-first", "Fast contact", "Floating action"],
    aiPrompt: "Use for service and local businesses where direct chat is a key conversion path.",
  },
  {
    type: "locationMap",
    name: "Location Map",
    category: "dynamic",
    icon: "MapPin",
    eyebrow: "Visit us",
    title: "Find our location",
    body: "Map section with address, opening hours, contact details, and route CTA.",
    primaryCta: "Get directions",
    items: ["Address", "Hours", "Directions", "Contact"],
    aiPrompt: "Use when a business has a physical location or service area.",
  },
  {
    type: "smartFooter",
    name: "Smart Footer",
    category: "layout",
    icon: "PanelBottom",
    eyebrow: "Footer",
    title: "Smart Footer",
    body: "Site-wide footer with navigation, legal links, social links, and contact details.",
    primaryCta: "Contact us",
    secondaryCta: "Subscribe",
    items: ["Link columns", "Legal links", "Social links", "Newsletter"],
    aiPrompt: "Use as the final site-wide section for navigation, contact, and compliance details.",
  },
  {
    type: "features",
    name: "Feature Story",
    category: "marketing",
    icon: "Sparkles",
    eyebrow: "Decision support",
    title: "Give buyers the context they need before calling",
    body: "An editorial feature section for location fit, construction approach, amenity relevance, and enquiry readiness.",
    primaryCta: "Explore details",
    secondaryCta: "Book a walkthrough",
    items: [
      "Built-area context",
      "Construction method",
      "Location decision",
      "Site visit path",
    ],
    aiPrompt: "Use for polished benefit, proof, process, or decision-support sections.",
  },
  {
    type: "gallery",
    name: "Editorial Gallery",
    category: "media",
    icon: "Images",
    eyebrow: "Visual proof",
    title: "Let the site carry the project atmosphere",
    body: "A composed gallery for exterior views, landscape edges, amenity areas, and finish details.",
    primaryCta: "View gallery",
    secondaryCta: "Book a visit",
    items: ["Wide exterior", "Landscape detail", "Amenity area", "Finish detail"],
    aiPrompt: "Use when the page needs visual proof but not a full lightbox interaction.",
  },
  {
    type: "cta",
    name: "Conversion CTA",
    category: "marketing",
    icon: "ArrowRight",
    eyebrow: "Next step",
    title: "Turn interest into a specific site-visit plan",
    body: "A focused conversion section with project details, callback support, and a low-friction visit path.",
    primaryCta: "Book a site visit",
    secondaryCta: "Download brochure",
    items: ["Project details", "Site visit timing", "Callback support"],
    aiPrompt: "Use near the end of a page when visitors need a clear conversion path.",
  },
  {
    type: "accordion",
    name: "Accordion / FAQ",
    category: "marketing",
    icon: "ListCollapse",
    eyebrow: "Answers",
    title: "Everything visitors need to know",
    body: "Native accordion content for FAQs, policies, comparisons, and objection handling.",
    primaryCta: "Ask another question",
    items: ["What is included?", "How long does it take?", "Can I customize it?", "What happens next?"],
    aiPrompt: "Use for editable FAQ and accordion sections with native question/answer items.",
  },
  {
    type: "tabs",
    name: "Tabs",
    category: "marketing",
    icon: "PanelTop",
    eyebrow: "Explore by topic",
    title: "Organize content without overwhelming the page",
    body: "Native tab metadata for grouped benefits, features, schedules, or service details.",
    primaryCta: "Compare options",
    items: ["Overview", "Details", "Process", "Results"],
    aiPrompt: "Use for grouped editable content that should stay compact and scannable.",
  },
  {
    type: "statsCounter",
    name: "Stats / Counter",
    category: "marketing",
    icon: "Gauge",
    eyebrow: "Proof in numbers",
    title: "Show measurable momentum",
    body: "Editable stats with labels, supporting copy, and animation metadata only.",
    primaryCta: "See results",
    items: ["120+ projects", "48 hr response", "97% satisfaction", "12 markets"],
    aiPrompt: "Use for KPI, traction, social proof, and performance summary sections.",
  },
  {
    type: "logoCloud",
    name: "Logo Cloud",
    category: "marketing",
    icon: "BadgeCheck",
    eyebrow: "Trusted by",
    title: "Credibility at a glance",
    body: "Editable logo/name cloud with accessible labels and theme-aware presentation.",
    primaryCta: "View partners",
    items: ["Northstar", "UrbanNest", "Apex", "Horizon", "Foundry", "Cobalt"],
    aiPrompt: "Use to show customers, partners, publications, integrations, or certifications.",
  },
  {
    type: "masonryGallery",
    name: "Gallery / Masonry",
    category: "media",
    icon: "LayoutGrid",
    eyebrow: "Visual library",
    title: "A flexible visual grid",
    body: "Native image-card gallery metadata with responsive masonry-style layout.",
    primaryCta: "Open gallery",
    items: ["Exterior", "Interior", "Amenity", "Detail", "Context", "Finish"],
    aiPrompt: "Use for image-rich pages that need editable visual storytelling.",
  },
  {
    type: "team",
    name: "Team",
    category: "marketing",
    icon: "UsersRound",
    eyebrow: "People",
    title: "Meet the team behind the work",
    body: "Editable people cards with names, roles, summaries, and accessible image metadata.",
    primaryCta: "Meet everyone",
    items: ["Asha - Design Lead", "Rohan - Project Manager", "Mira - Client Success", "Dev - Operations"],
    aiPrompt: "Use for founders, leadership, staff, agents, clinicians, advisors, or contributors.",
  },
  {
    type: "portfolio",
    name: "Portfolio Grid",
    category: "marketing",
    icon: "BriefcaseBusiness",
    eyebrow: "Selected work",
    title: "A portfolio people can evaluate quickly",
    body: "Editable case-study cards with categories, summaries, outcomes, and CTAs.",
    primaryCta: "View case studies",
    items: ["Launch redesign", "Retail fit-out", "Brand system", "Growth campaign"],
    aiPrompt: "Use for work samples, project grids, case studies, or collections.",
  },
  {
    type: "timeline",
    name: "Timeline / Process",
    category: "marketing",
    icon: "Milestone",
    eyebrow: "Process",
    title: "Make the path feel predictable",
    body: "Editable timeline steps for onboarding, delivery, milestones, launches, or roadmaps.",
    primaryCta: "Start step one",
    items: ["Discover", "Plan", "Build", "Launch", "Improve"],
    aiPrompt: "Use when users need to understand sequence, process, roadmap, or delivery stages.",
  },
  {
    type: "featureGrid",
    name: "Feature Grid",
    category: "marketing",
    icon: "Grid3X3",
    eyebrow: "Features",
    title: "A clean grid for what matters",
    body: "Editable feature cards with theme-ready styling and responsive grid metadata.",
    primaryCta: "Explore features",
    items: ["Fast setup", "Flexible design", "Native editing", "Reliable publishing"],
    aiPrompt: "Use for product benefits, service features, amenities, or capability groups.",
  },
  {
    type: "contactForm",
    name: "Contact Form",
    category: "forms",
    icon: "Mail",
    eyebrow: "Contact",
    title: "Start a useful conversation",
    body: "Editable contact form fields with validation metadata and no submission wiring changes.",
    primaryCta: "Send message",
    items: ["Name", "Email", "Phone", "Message"],
    aiPrompt: "Use for contact, support, quote, service inquiry, and callback sections.",
  },
  {
    type: "socialLinks",
    name: "Social Links",
    category: "marketing",
    icon: "Share2",
    eyebrow: "Social",
    title: "Connect across channels",
    body: "Editable social link list with accessible labels and safe external-link metadata.",
    primaryCta: "Follow us",
    items: ["Instagram", "LinkedIn", "YouTube", "X"],
    aiPrompt: "Use for social profile groups, footer social rows, or creator links.",
  },
  {
    type: "carousel",
    name: "Carousel",
    category: "media",
    icon: "GalleryHorizontal",
    eyebrow: "Highlights",
    title: "Show a sequence of featured moments",
    body: "Editable slide metadata with reduced-motion and runtime parity requirements.",
    primaryCta: "View slides",
    items: ["Slide one", "Slide two", "Slide three"],
    aiPrompt: "Use sparingly for featured collections, testimonials, campaigns, or product highlights.",
  },
  {
    type: "beforeAfter",
    name: "Before / After",
    category: "media",
    icon: "Columns2",
    eyebrow: "Transformation",
    title: "Make the change obvious",
    body: "Editable before/after comparison metadata with static Builder-safe rendering.",
    primaryCta: "See the project",
    items: ["Before state", "After state"],
    aiPrompt: "Use for renovations, makeovers, audits, optimization, or transformation stories.",
  },
  {
    type: "table",
    name: "Table",
    category: "basic",
    icon: "Table2",
    eyebrow: "Comparison",
    title: "Structured information people can scan",
    body: "Editable table-style data with accessible header and row metadata.",
    primaryCta: "Compare details",
    items: ["Feature | Starter | Pro", "Support | Email | Priority", "Setup | Guided | Managed"],
    aiPrompt: "Use for comparisons, specifications, schedules, packages, and structured data.",
  },
  {
    type: "countdown",
    name: "Countdown",
    category: "dynamic",
    icon: "Timer",
    eyebrow: "Limited time",
    title: "Create urgency without custom code",
    body: "Editable countdown metadata with static Builder-safe display and timezone requirements.",
    primaryCta: "Reserve now",
    items: ["Days", "Hours", "Minutes", "Seconds"],
    aiPrompt: "Use for launches, events, booking windows, sales, or registration deadlines.",
  },
  {
    type: "codeBlock",
    name: "Code Block",
    category: "basic",
    icon: "Code2",
    eyebrow: "Code",
    title: "Readable code example",
    body: "Native code block display. It never executes scripts in Builder or runtime.",
    primaryCta: "Copy snippet",
    items: ["const ready = true;", "renderNativeWidget();"],
    aiPrompt: "Use for documentation-style pages that need safe visible code snippets.",
  },
  {
    type: "embed",
    name: "Embed (Restricted)",
    category: "dynamic",
    icon: "Braces",
    eyebrow: "Restricted embed",
    title: "Safe embed placeholder",
    body: "Restricted embed metadata. Scripts, inline HTML execution, and opaque templates are blocked.",
    primaryCta: "Review embed policy",
    items: ["Provider", "URL", "Sandbox", "Fallback label"],
    aiPrompt: "Use only when a safe provider URL or embed placeholder is required. Never generate opaque executable HTML.",
  },
  {
    type: "blogGrid",
    name: "Blog Grid",
    category: "marketing",
    icon: "Newspaper",
    eyebrow: "Articles",
    title: "Latest thinking, clearly organized",
    body: "Editable article cards with category, excerpt, author, and CTA metadata.",
    primaryCta: "Read more",
    items: ["Guide", "Case study", "News", "Opinion"],
    aiPrompt: "Use for editorial landing pages, article collections, and content hubs.",
  },
  {
    type: "postList",
    name: "Post List",
    category: "marketing",
    icon: "List",
    eyebrow: "Posts",
    title: "A focused list of updates",
    body: "Editable post-list metadata for news, changelogs, resources, or announcements.",
    primaryCta: "View all posts",
    items: ["Announcement", "Resource", "Update", "Story"],
    aiPrompt: "Use for compact content lists and chronological updates.",
  },
  {
    type: "categoryList",
    name: "Category List",
    category: "marketing",
    icon: "Tags",
    eyebrow: "Browse",
    title: "Help visitors choose a path",
    body: "Editable category links for content, products, services, or resource hubs.",
    primaryCta: "Browse all",
    items: ["Guides", "Projects", "Resources", "Support"],
    aiPrompt: "Use for category navigation, topic lists, and collection landing pages.",
  },
  {
    type: "popupModal",
    name: "Popup (Metadata Only)",
    category: "dynamic",
    icon: "PanelsTopLeft",
    eyebrow: "Popup metadata",
    title: "Popup configuration placeholder",
    body: "Metadata-only popup policy surface. No runtime modal execution, focus trap, or triggers are enabled in BSP-15.",
    primaryCta: "Review policy",
    items: ["Trigger metadata", "Dismiss policy", "Focus requirements", "Accessibility gate"],
    aiPrompt: "Use only as metadata scaffold. Do not generate runtime popups until QA and accessibility gates pass.",
  },
];

function createPremiumDefinition(seed: PremiumWidgetSeed): WidgetDefinition {
  return {
    type: seed.type,
    name: seed.name,
    icon: seed.icon,
    category: seed.category,
    canHaveChildren: false,
    render: PremiumWidget,
    aiPrompt: seed.aiPrompt,
    defaultNode: {
      type: seed.type,
      children: [],
      props: {
        eyebrow: seed.eyebrow,
        title: seed.title,
        body: seed.body,
        primaryCta: seed.primaryCta,
        ...(seed.secondaryCta ? { secondaryCta: seed.secondaryCta } : {}),
        items: seed.items,
      },
      style: {
        width: "100%",
      },
    },
    properties: sharedProperties,
  };
}

export const PremiumWidgetDefinitions = premiumWidgetSeeds.map(
  createPremiumDefinition
);

function definitionByType(type: NodeType) {
  const definition = PremiumWidgetDefinitions.find((widget) => widget.type === type);
  if (!definition) throw new Error(`Missing premium widget definition: ${type}`);
  return definition;
}

export const SmartHeaderDefinition = definitionByType("smartHeader");
export const ConversionHeroDefinition = definitionByType("hero");
export const LeadFormDefinition = definitionByType("leadForm");
export const CardGridDefinition = definitionByType("cardGrid");
export const GalleryLightboxDefinition = definitionByType("galleryLightbox");
export const FaqAccordionDefinition = definitionByType("faq");
export const TestimonialsDefinition = definitionByType("testimonials");
export const PricingTableDefinition = definitionByType("pricing");
export const OfferGridDefinition = definitionByType("offerGrid");
export const FloatingWhatsAppDefinition = definitionByType("floatingWhatsApp");
export const LocationMapDefinition = definitionByType("locationMap");
export const SmartFooterDefinition = definitionByType("smartFooter");
export const FeaturesDefinition = definitionByType("features");
export const GalleryDefinition = definitionByType("gallery");
export const CtaDefinition = definitionByType("cta");
