"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { Building2, CreditCard, Globe2, Headphones, Inbox, MoreHorizontal, Plus, Search, Star, UserRoundSearch, Users, WalletCards, X } from "lucide-react";
import type { LucideIcon } from "lucide-react";

export type ResourceMode = "users" | "tenants" | "sites" | "plans" | "transactions" | "support" | "crm" | "requests" | "feedback";
type Item = {
  id: string; code?: string; name?: string | null; email?: string | null; role?: string; isActive?: boolean;
  lastLoginAt?: string | null; createdAt?: string; updatedAt?: string; domain?: string | null; aiSuspended?: boolean;
  status?: string; slug?: string; maxSites?: number; maxPages?: number; aiCredits?: number; isPublic?: boolean;
  owner?: { name?: string | null; email?: string | null } | null; subscription?: { planCode?: string | null } | null;
  tenant?: { id?: string; name: string; isActive?: boolean } | null; site?: { name: string; tenant: { name: string } };
  _count?: Record<string, number>; domains?: Array<{ domain: string; status: string }>;
  pricing?: Array<{ currency: string; amount: number; billingCycle: string }>; features?: Array<{ key: string }>;
  reference?: string; description?: string; party?: string; amount?: number; currency?: string; type?: string;
  company?: string | null; phone?: string | null; source?: string; score?: number; temperature?: string; message?: string | null; tags?: string[];
  customData?: { subject?: string; ticketNumber?: string; priority?: string } | null;
  communications?: Array<{ createdAt: string }>;
  subject?: string | null; severity?: string | null; pageUrl?: string | null;
  rating?: number; comment?: string | null;
};

const config: Record<ResourceMode, { title: string; subtitle: string; key: string; endpoint: string; detail: string; icon: LucideIcon; addLabel?: string }> = {
  users: { title: "Users & access", subtitle: "Control platform identities, roles and account access.", key: "users", endpoint: "users", detail: "users", icon: Users, addLabel: "Add user" },
  tenants: { title: "Tenant operations", subtitle: "Manage every workspace and suspend platform or AI access independently.", key: "tenants", endpoint: "tenants", detail: "tenants", icon: Building2, addLabel: "Add tenant" },
  sites: { title: "Website control", subtitle: "Inspect and control publishing across every tenant.", key: "sites", endpoint: "sites", detail: "websites", icon: Globe2, addLabel: "Add website" },
  plans: { title: "Plans & entitlements", subtitle: "Review limits, pricing, adoption and public availability.", key: "plans", endpoint: "plans", detail: "plans", icon: WalletCards, addLabel: "Add plan" },
  transactions: { title: "Transactions", subtitle: "A unified ledger of subscriptions and ShopEZ order payments.", key: "transactions", endpoint: "transactions", detail: "transactions", icon: CreditCard },
  support: { title: "Support desk", subtitle: "Triage, assign and resolve customer support tickets across BuildEZ.", key: "tickets", endpoint: "support", detail: "support", icon: Headphones, addLabel: "Add ticket" },
  crm: { title: "Platform CRM", subtitle: "See and manage leads generated by every BuildEZ website.", key: "leads", endpoint: "crm", detail: "crm", icon: UserRoundSearch, addLabel: "Add lead" },
  requests: { title: "Public inbox", subtitle: "Support, bug and abuse submissions from the public BuildEZ website.", key: "requests", endpoint: "requests", detail: "requests", icon: Inbox },
  feedback: { title: "Design feedback", subtitle: "Star ratings and comments left after AI website generations.", key: "feedback", endpoint: "feedback", detail: "feedback", icon: Star },
};

export default function ResourceManager({ mode }: { mode: ResourceMode }) {
  const cfg = config[mode];
  const Icon = cfg.icon;
  const [items, setItems] = useState<Item[]>([]);
  const [query, setQuery] = useState("");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [busy, setBusy] = useState("");
  const [addOpen, setAddOpen] = useState(false);
  const [form, setForm] = useState<Record<string, string>>({});

  const load = useCallback(async () => {
    setLoading(true); setError("");
    try {
      const response = await fetch(`/api/super/${cfg.endpoint}${query && mode !== "plans" ? `?q=${encodeURIComponent(query)}` : ""}`, { cache: "no-store" });
      const data = await response.json();
      if (!response.ok) throw new Error(data.error || "Request failed");
      setItems(data[cfg.key] || []);
    } catch (e) { setError(e instanceof Error ? e.message : "Request failed"); }
    finally { setLoading(false); }
  }, [cfg.endpoint, cfg.key, mode, query]);
  useEffect(() => { const timer = setTimeout(load, 180); return () => clearTimeout(timer); }, [load]);

  async function mutate(id: string, changes: Record<string, unknown>) {
    setBusy(id); setError("");
    try {
      const body = mode === "plans" ? { code: id, ...changes } : { id, ...changes };
      const response = await fetch(`/api/super/${cfg.endpoint}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
      const data = await response.json(); if (!response.ok) throw new Error(data.error || "Update failed"); await load();
    } catch (e) { setError(e instanceof Error ? e.message : "Update failed"); } finally { setBusy(""); }
  }

  async function remove(id: string) {
    setBusy(id); setError("");
    try {
      const body = mode === "plans" ? { code: id } : { id };
      const response = await fetch(`/api/super/${cfg.endpoint}`, { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
      const data = await response.json(); if (!response.ok) throw new Error(data.error || "Delete failed"); await load();
    } catch (e) { setError(e instanceof Error ? e.message : "Delete failed"); } finally { setBusy(""); }
  }

  async function createRecord(event: React.FormEvent) {
    event.preventDefault(); setBusy("create"); setError("");
    try {
      const response = await fetch(`/api/super/${cfg.endpoint}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) });
      const data = await response.json(); if (!response.ok) throw new Error(data.error || "Create failed"); setAddOpen(false); setForm({}); await load();
    } catch (e) { setError(e instanceof Error ? e.message : "Create failed"); } finally { setBusy(""); }
  }

  return <div>
    <div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="mb-2 flex items-center gap-2 text-xs font-semibold uppercase tracking-[.14em] dashboard-faint"><Icon size={15}/> Global administration</div><h1 className="text-3xl font-semibold tracking-[-.035em]">{cfg.title}</h1><p className="mt-2 text-sm dashboard-muted">{cfg.subtitle}</p></div><div className="flex flex-wrap gap-2">{mode === "plans" && <Link href="/app/plans" className="dashboard-card inline-flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-semibold"><CreditCard size={16}/>View plans</Link>}{cfg.addLabel && <button onClick={() => setAddOpen(true)} className="dashboard-primary-button inline-flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-semibold text-white"><Plus size={16}/>{cfg.addLabel}</button>}<span className="dashboard-card rounded-xl px-4 py-2.5 text-sm font-semibold">{items.length} records</span></div></div>
    <div className="relative mt-5 max-w-xl"><Search className="absolute left-3.5 top-1/2 -translate-y-1/2 dashboard-muted" size={18}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder={`Search ${mode}...`} className="dashboard-input h-12 w-full rounded-xl pl-11 pr-4 text-sm"/></div>
    {error && <div className="mt-4 rounded-xl border border-rose-500/20 bg-rose-500/10 px-4 py-3 text-sm text-rose-600 dark:text-rose-300">{error}</div>}
    <div className="dashboard-card mt-5 overflow-visible rounded-3xl">{loading ? <div className="p-12 text-center text-sm dashboard-muted">Loading live platform data…</div> : !items.length ? <div className="p-12 text-center text-sm dashboard-muted">No matching records found.</div> : <div className="overflow-x-auto rounded-3xl">{renderTable(mode, items, busy, mutate, cfg.detail, remove)}</div>}</div>
    {addOpen && <AddModal mode={mode} form={form} setForm={setForm} busy={busy === "create"} onClose={() => setAddOpen(false)} onSubmit={createRecord}/>} 
  </div>;
}

function renderTable(mode: ResourceMode, items: Item[], busy: string, mutate: TableProps["mutate"], detail: string, remove: (id: string) => void) {
  const props = { items, busy, mutate, detail, remove };
  if (mode === "users") return <UsersTable {...props}/>;
  if (mode === "tenants") return <TenantsTable {...props}/>;
  if (mode === "sites") return <SitesTable {...props}/>;
  if (mode === "plans") return <PlansTable {...props}/>;
  if (mode === "transactions") return <TransactionsTable {...props}/>;
  if (mode === "support") return <SupportTable {...props}/>;
  if (mode === "requests") return <RequestsTable {...props}/>;
  if (mode === "feedback") return <FeedbackTable {...props}/>;
  return <CrmTable {...props}/>;
}

type TableProps = { items: Item[]; busy: string; mutate: (id: string, changes: Record<string, unknown>) => void; detail: string; remove?: (id: string) => void };
function UsersTable({ items, busy, mutate, detail }: TableProps) { return <Table heads={["User", "Role", "Workspaces", "Last login", "Access", ""]}>{items.map(u => <Row key={u.id}><Cell><RecordLink href={`/${detail}/${u.id}`} title={u.name || "Unnamed user"} subtitle={u.email || "No email"}/></Cell><Cell>{u.role}</Cell><Cell>{(u._count?.ownedTenants || 0) + (u._count?.tenantUsers || 0)}</Cell><Cell>{date(u.lastLoginAt)}</Cell><Cell><Status active={Boolean(u.isActive)}>{u.isActive ? "Active" : "Disabled"}</Status></Cell><MenuCell href={`/${detail}/${u.id}`} actions={[{ label: u.isActive ? "Disable account" : "Enable account", run: () => mutate(u.id, { isActive: !u.isActive }) }, { label: "Make tenant admin", run: () => mutate(u.id, { role: "TENANT_ADMIN" }) }, { label: "Make superadmin", run: () => mutate(u.id, { role: "SUPER_ADMIN" }) }]} disabled={busy === u.id}/></Row>)}</Table>; }
function TenantsTable({ items, busy, mutate, detail }: TableProps) { return <Table heads={["Workspace", "Owner", "Usage", "Plan", "AI", "Platform", ""]}>{items.map(t => <Row key={t.id}><Cell><RecordLink href={`/${detail}/${t.id}`} title={t.name || "Tenant"} subtitle={t.domain || t.id}/></Cell><Cell>{t.owner?.name || t.owner?.email || "—"}</Cell><Cell>{t._count?.sites || 0} sites · {t._count?.users || 0} users</Cell><Cell>{t.subscription?.planCode || "No active plan"}</Cell><Cell><Status active={!t.aiSuspended}>{t.aiSuspended ? "Suspended" : "Enabled"}</Status></Cell><Cell><Status active={Boolean(t.isActive)}>{t.isActive ? "Active" : "Suspended"}</Status></Cell><MenuCell href={`/${detail}/${t.id}`} actions={[{ label: t.isActive ? "Suspend tenant" : "Restore tenant", run: () => mutate(t.id, { isActive: !t.isActive }) }, { label: t.aiSuspended ? "Enable AI" : "Suspend AI", run: () => mutate(t.id, { aiSuspended: !t.aiSuspended }) }]} disabled={busy === t.id}/></Row>)}</Table>; }
function SitesTable({ items, busy, mutate, detail }: TableProps) { return <Table heads={["Website", "Tenant", "Content", "Domain", "Updated", "Status", ""]}>{items.map(s => <Row key={s.id}><Cell><RecordLink href={`/${detail}/${s.id}`} title={s.name || "Website"} subtitle={`/${s.slug}`}/></Cell><Cell>{s.tenant?.name || "—"}</Cell><Cell>{s._count?.pages || 0} pages · {s._count?.mediaAssets || 0} assets</Cell><Cell>{s.domains?.[0]?.domain || "Default domain"}</Cell><Cell>{date(s.updatedAt)}</Cell><Cell><Status active={s.status === "PUBLISHED"}>{s.status}</Status></Cell><MenuCell href={`/${detail}/${s.id}`} actions={[{ label: s.status === "PUBLISHED" ? "Unpublish" : "Publish", run: () => mutate(s.id, { status: s.status === "PUBLISHED" ? "DRAFT" : "PUBLISHED" }) }]} disabled={busy === s.id}/></Row>)}</Table>; }
function PlansTable({ items, busy, mutate, remove, detail }: TableProps) { return <Table heads={["Plan", "Limits", "Pricing", "Features", "Adoption", "Availability", ""]}>{items.map(p => { const subscribers = (p._count?.subscriptions || 0) + (p._count?.siteSubscriptions || 0); return <Row key={p.code}><Cell><RecordLink href={`/${detail}/${p.code}`} title={p.name || "Plan"} subtitle={p.code}/></Cell><Cell>{p.maxSites} sites · {p.maxPages} pages<br/><span className="text-xs dashboard-muted">{p.aiCredits || 0} AI credits</span></Cell><Cell>{p.pricing?.map(x => `${x.currency} ${x.amount}/${x.billingCycle}`).join(", ") || "Custom"}</Cell><Cell>{p.features?.length || 0}</Cell><Cell>{subscribers}</Cell><Cell><Status active={Boolean(p.isPublic)}>{p.isPublic ? "Published" : "Unpublished"}</Status></Cell><td className="relative px-4 py-3 text-right"><PlanActions code={p.code || p.id} detail={detail} isPublic={Boolean(p.isPublic)} subscribers={subscribers} busy={busy === (p.code || p.id)} mutate={mutate} remove={remove}/></td></Row>; })}</Table>; }
function PlanActions({ code, detail, isPublic, subscribers, busy, mutate, remove }: { code: string; detail: string; isPublic: boolean; subscribers: number; busy: boolean; mutate: TableProps["mutate"]; remove?: TableProps["remove"] }) {
  const [open, setOpen] = useState(false);
  function handleDelete() {
    setOpen(false);
    if (subscribers > 0) { window.alert("This plan has active subscribers and can't be deleted. Unpublish it instead."); return; }
    if (window.confirm(`Delete the "${code}" plan? This can't be undone.`)) remove?.(code);
  }
  return <><button disabled={busy} onClick={() => setOpen(v => !v)} aria-label="Open actions" className="rounded-xl p-2 dashboard-hover disabled:opacity-40"><MoreHorizontal size={18}/></button>{open && <><button aria-label="Close actions" className="fixed inset-0 z-40" onClick={() => setOpen(false)}/><div className="dashboard-modal-surface absolute right-4 top-12 z-50 w-48 rounded-xl border dashboard-border p-1.5 text-left shadow-xl">
    <Link href={`/super/${detail}/${code}`} onClick={() => setOpen(false)} className="block rounded-lg px-3 py-2 text-xs font-semibold dashboard-hover">View plan</Link>
    <Link href={`/super/${detail}/${code}`} onClick={() => setOpen(false)} className="block rounded-lg px-3 py-2 text-xs font-semibold dashboard-hover">Edit plan</Link>
    <button onClick={() => { setOpen(false); mutate(code, { isPublic: !isPublic }); }} className="block w-full rounded-lg px-3 py-2 text-left text-xs font-semibold dashboard-hover">{isPublic ? "Unpublish" : "Publish"}</button>
    <button onClick={handleDelete} className="block w-full rounded-lg px-3 py-2 text-left text-xs font-semibold text-red-500 dashboard-hover">Delete plan</button>
  </div></>}</>;
}
function TransactionsTable({ items, detail }: TableProps) { return <Table heads={["Reference", "Type", "Customer", "Tenant", "Amount", "Status", "Date", ""]}>{items.map(t => { const key = `${t.type}:${t.id}`; return <Row key={key}><Cell><RecordLink href={`/${detail}/${key}`} title={t.reference || t.id} subtitle={t.description}/></Cell><Cell>{t.type}</Cell><Cell>{t.party}</Cell><Cell>{t.tenant?.name || "—"}</Cell><Cell><strong>{t.currency} {(t.amount || 0).toLocaleString()}</strong></Cell><Cell><Status active={/paid|active|authorized/i.test(t.status || "")}>{t.status}</Status></Cell><Cell>{date(t.createdAt)}</Cell><MenuCell href={`/${detail}/${key}`} actions={[]} disabled={false}/></Row>; })}</Table>; }
function SupportTable({ items, busy, mutate, detail }: TableProps) { return <Table heads={["Ticket", "Customer", "Website", "Priority", "Status", "Created", ""]}>{items.map(t => <Row key={t.id}><Cell><RecordLink href={`/${detail}/${t.id}`} title={t.customData?.subject || t.customData?.ticketNumber || "Support request"} subtitle={t.message}/></Cell><Cell>{t.name}<br/><span className="text-xs dashboard-muted">{t.email}</span></Cell><Cell>{t.site?.name}<br/><span className="text-xs dashboard-muted">{t.site?.tenant.name}</span></Cell><Cell>{t.customData?.priority || t.tags?.[2] || "normal"}</Cell><Cell><Status active={t.status === "RESOLVED" || t.status === "CLOSED"}>{t.status}</Status></Cell><Cell>{date(t.createdAt)}</Cell><MenuCell href={`/${detail}/${t.id}`} actions={[{ label: "Mark open", run: () => mutate(t.id, { status: "OPEN" }) }, { label: "Resolve ticket", run: () => mutate(t.id, { status: "RESOLVED" }) }, { label: "Close ticket", run: () => mutate(t.id, { status: "CLOSED" }) }]} disabled={busy === t.id}/></Row>)}</Table>; }
function CrmTable({ items, busy, mutate, detail }: TableProps) { return <Table heads={["Lead", "Company", "Website", "Source", "Score", "Status", ""]}>{items.map(l => <Row key={l.id}><Cell><RecordLink href={`/${detail}/${l.id}`} title={l.name || "Lead"} subtitle={l.email || l.phone || "No contact"}/></Cell><Cell>{l.company || "—"}</Cell><Cell>{l.site?.name}<br/><span className="text-xs dashboard-muted">{l.site?.tenant.name}</span></Cell><Cell>{l.source}</Cell><Cell>{l.score || 0} · {l.temperature}</Cell><Cell><Status active={l.status === "WON"}>{l.status}</Status></Cell><MenuCell href={`/${detail}/${l.id}`} actions={[{ label: "Mark contacted", run: () => mutate(l.id, { status: "CONTACTED" }) }, { label: "Qualify lead", run: () => mutate(l.id, { status: "QUALIFIED" }) }, { label: "Mark won", run: () => mutate(l.id, { status: "WON" }) }, { label: "Mark lost", run: () => mutate(l.id, { status: "LOST" }) }]} disabled={busy === l.id}/></Row>)}</Table>; }
function RequestsTable({ items, busy, mutate }: TableProps) { return <Table heads={["Submission", "From", "Type", "Severity", "Status", "Received", ""]}>{items.map(r => <Row key={r.id}><Cell><span className="block font-semibold text-[var(--dashboard-text)]">{r.subject || "No subject"}</span><span className="block max-w-[320px] truncate text-xs dashboard-muted">{r.message}</span></Cell><Cell>{r.name || "—"}<br/><span className="text-xs dashboard-muted">{r.email}</span></Cell><Cell>{r.type}</Cell><Cell>{r.severity || "—"}</Cell><Cell><Status active={r.status === "RESOLVED" || r.status === "CLOSED"}>{r.status}</Status></Cell><Cell>{date(r.createdAt)}</Cell><td className="relative px-4 py-3 text-right"><RequestActions id={r.id} busy={busy === r.id} mutate={mutate}/></td></Row>)}</Table>; }
function RequestActions({ id, busy, mutate }: { id: string; busy: boolean; mutate: TableProps["mutate"] }) {
  const [open, setOpen] = useState(false);
  return <><button disabled={busy} onClick={() => setOpen(v => !v)} aria-label="Open actions" className="rounded-xl p-2 dashboard-hover disabled:opacity-40"><MoreHorizontal size={18}/></button>{open && <><button aria-label="Close actions" className="fixed inset-0 z-40" onClick={() => setOpen(false)}/><div className="dashboard-modal-surface absolute right-4 top-12 z-50 w-48 rounded-xl border dashboard-border p-1.5 text-left shadow-xl">{["NEW","IN_PROGRESS","RESOLVED","CLOSED"].map(status => <button key={status} onClick={() => { setOpen(false); mutate(id, { status }); }} className="block w-full rounded-lg px-3 py-2 text-left text-xs font-semibold dashboard-hover">Mark {status.replace("_"," ").toLowerCase()}</button>)}</div></>}</>;
}
function FeedbackStars({ rating }: { rating?: number }) { return <span className="inline-flex gap-0.5">{[1,2,3,4,5].map(value => <Star key={value} size={13} className={(rating || 0) >= value ? "fill-amber-400 text-amber-400" : "text-slate-300 dark:text-white/15"}/>)}</span>; }
function FeedbackTable({ items, busy, mutate }: TableProps) { return <Table heads={["Rating", "Comment", "Website", "Status", "Received", ""]}>{items.map(f => <Row key={f.id}><Cell><FeedbackStars rating={f.rating}/></Cell><Cell><span className="block max-w-[320px] truncate">{f.comment || "—"}</span></Cell><Cell>{f.site?.name}<br/><span className="text-xs dashboard-muted">{f.site?.tenant.name}</span></Cell><Cell><Status active={f.status === "RESOLVED" || f.status === "CLOSED"}>{f.status}</Status></Cell><Cell>{date(f.createdAt)}</Cell><td className="relative px-4 py-3 text-right"><FeedbackActions id={f.id} busy={busy === f.id} mutate={mutate}/></td></Row>)}</Table>; }
function FeedbackActions({ id, busy, mutate }: { id: string; busy: boolean; mutate: TableProps["mutate"] }) {
  const [open, setOpen] = useState(false);
  return <><button disabled={busy} onClick={() => setOpen(v => !v)} aria-label="Open actions" className="rounded-xl p-2 dashboard-hover disabled:opacity-40"><MoreHorizontal size={18}/></button>{open && <><button aria-label="Close actions" className="fixed inset-0 z-40" onClick={() => setOpen(false)}/><div className="dashboard-modal-surface absolute right-4 top-12 z-50 w-48 rounded-xl border dashboard-border p-1.5 text-left shadow-xl">{["NEW","REVIEWED","RESOLVED"].map(status => <button key={status} onClick={() => { setOpen(false); mutate(id, { status }); }} className="block w-full rounded-lg px-3 py-2 text-left text-xs font-semibold dashboard-hover">Mark {status.toLowerCase()}</button>)}</div></>}</>;
}

function AddModal({ mode, form, setForm, busy, onClose, onSubmit }: { mode: ResourceMode; form: Record<string,string>; setForm: React.Dispatch<React.SetStateAction<Record<string,string>>>; busy: boolean; onClose: () => void; onSubmit: (e: React.FormEvent) => void }) {
  const fields: Record<Exclude<ResourceMode,"transactions"|"requests"|"feedback">, Array<{ key: string; label: string; type?: string; required?: boolean; placeholder?: string }>> = {
    users: [{ key:"name",label:"Full name" },{ key:"email",label:"Email",type:"email",required:true },{ key:"role",label:"Role",placeholder:"USER" }],
    tenants: [{ key:"name",label:"Tenant name",required:true },{ key:"domain",label:"Domain" },{ key:"ownerEmail",label:"Existing owner email",type:"email" }],
    sites: [{ key:"name",label:"Website name",required:true },{ key:"slug",label:"Slug",required:true },{ key:"tenantId",label:"Tenant ID",required:true }],
    plans: [{ key:"name",label:"Plan name",required:true },{ key:"code",label:"Plan code",required:true },{ key:"priceMonthly",label:"Monthly price",type:"number" },{ key:"priceYearly",label:"Yearly price",type:"number" },{ key:"currency",label:"Currency",placeholder:"INR" },{ key:"maxSites",label:"Maximum sites",type:"number" },{ key:"maxPages",label:"Maximum pages",type:"number" },{ key:"aiCredits",label:"AI credits",type:"number" },{ key:"teamMembers",label:"Team members",type:"number" }],
    support: [{ key:"siteId",label:"Website ID",required:true },{ key:"subject",label:"Subject",required:true },{ key:"name",label:"Customer name" },{ key:"email",label:"Customer email",type:"email" },{ key:"priority",label:"Priority",placeholder:"normal" },{ key:"message",label:"Details",required:true }],
    crm: [{ key:"siteId",label:"Website ID",required:true },{ key:"name",label:"Lead name",required:true },{ key:"email",label:"Email",type:"email" },{ key:"phone",label:"Phone" },{ key:"company",label:"Company" }],
  };
  if (mode === "transactions" || mode === "requests" || mode === "feedback") return null;
  return <div className="dashboard-modal-root flex items-center justify-center bg-black/45 p-4"><button aria-label="Close modal" className="absolute inset-0" onClick={onClose}/><form onSubmit={onSubmit} className="dashboard-modal-surface relative z-10 max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-3xl border p-6 shadow-2xl sm:p-7"><div className="flex items-start justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[.14em] dashboard-faint">Create record</p><h2 className="mt-1 text-xl font-semibold">{config[mode].addLabel}</h2></div><button type="button" onClick={onClose} className="rounded-xl p-2 dashboard-hover"><X size={18}/></button></div><div className="mt-6 grid gap-4">{fields[mode].map(field => <label key={field.key} className="grid gap-1.5 text-sm font-medium">{field.label}<input type={field.type || "text"} required={field.required} placeholder={field.placeholder} value={form[field.key] || ""} onChange={e => setForm(current => ({ ...current, [field.key]: e.target.value }))} className="dashboard-input rounded-xl px-4 py-3 text-sm"/></label>)}</div><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-xl px-4 py-2.5 text-sm font-semibold dashboard-hover">Cancel</button><button disabled={busy} className="dashboard-primary-button rounded-xl px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{busy ? "Creating…" : "Create"}</button></div></form></div>;
}

function MenuCell({ href, actions, disabled }: { href: string; actions: Array<{ label: string; run: () => void }>; disabled: boolean }) { const [open,setOpen]=useState(false); return <td className="relative px-4 py-3 text-right"><button disabled={disabled} onClick={() => setOpen(v=>!v)} aria-label="Open actions" className="rounded-xl p-2 dashboard-hover disabled:opacity-40"><MoreHorizontal size={18}/></button>{open && <><button aria-label="Close actions" className="fixed inset-0 z-40" onClick={()=>setOpen(false)}/><div className="dashboard-modal-surface absolute right-4 top-12 z-50 w-48 rounded-xl border dashboard-border p-1.5 text-left shadow-xl"><Link href={`/super${href}`} className="block rounded-lg px-3 py-2 text-xs font-semibold dashboard-hover">View details</Link>{actions.map(action => <button key={action.label} onClick={() => { setOpen(false); action.run(); }} className="block w-full rounded-lg px-3 py-2 text-left text-xs font-semibold dashboard-hover">{action.label}</button>)}</div></>}</td>; }
function Table({ heads, children }: { heads: string[]; children: React.ReactNode }) { return <table className="w-full min-w-[980px] text-left text-sm"><thead className="dashboard-subtle text-[10px] font-semibold uppercase tracking-[.14em] dashboard-faint"><tr>{heads.map((h,i)=><th key={`${h}-${i}`} className="px-5 py-4">{h}</th>)}</tr></thead><tbody>{children}</tbody></table>; }
function Row({ children }: { children: React.ReactNode }) { return <tr className="border-t dashboard-border transition dashboard-hover">{children}</tr>; }
function Cell({ children }: { children: React.ReactNode }) { return <td className="px-5 py-4 align-middle text-sm dashboard-muted">{children}</td>; }
function RecordLink({ href, title, subtitle }: { href: string; title: React.ReactNode; subtitle?: React.ReactNode }) { return <Link href={`/super${href}`} className="group block"><span className="font-semibold text-[var(--dashboard-text)] group-hover:text-blue-600">{title}</span>{subtitle && <span className="block max-w-[280px] truncate text-xs dashboard-muted">{subtitle}</span>}</Link>; }
function Status({ active, children }: { active: boolean; children: React.ReactNode }) { return <span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[10px] font-semibold uppercase tracking-wide ${active ? "bg-emerald-500/10 text-emerald-700 dark:text-emerald-300" : "bg-amber-500/10 text-amber-700 dark:text-amber-300"}`}><span className={`h-1.5 w-1.5 rounded-full ${active ? "bg-emerald-500" : "bg-amber-500"}`}/>{children || "—"}</span>; }
function date(value?: string | null) { return value ? new Date(value).toLocaleDateString() : "—"; }
