import type { DesignFamilyContext, DesignInput, DesignLanguageName, DesignLanguageProfile } from "./designIntent";

const profile = (input: DesignLanguageProfile): DesignLanguageProfile => Object.freeze(input);

export const DESIGN_LANGUAGE_PROFILES: readonly DesignLanguageProfile[] = Object.freeze([
  profile({ name: "Minimal", typographyBehavior: "quiet geometric sans", colorBehavior: "restrained neutrals", spacingBehavior: "airy", layoutBehavior: "simple hierarchy", imageBehavior: "controlled", motionBehavior: "low", ctaBehavior: "clear", cardBehavior: "flat", backgroundBehavior: "clean", accessibilityConstraints: ["high contrast"], suitableIndustries: ["architecture_interiors", "healthcare", "professional_services"], unsuitableIndustries: [] }),
  profile({ name: "Modern", typographyBehavior: "clean sans", colorBehavior: "balanced neutral with accent", spacingBehavior: "balanced", layoutBehavior: "modular", imageBehavior: "product/service clear", motionBehavior: "low-medium", ctaBehavior: "direct", cardBehavior: "subtle", backgroundBehavior: "light bands", accessibilityConstraints: ["contrast-safe accent"], suitableIndustries: ["education", "ecommerce_d2c", "technology_saas", "automotive"], unsuitableIndustries: [] }),
  profile({ name: "Luxury", typographyBehavior: "elegant display plus readable body", colorBehavior: "warm neutral premium", spacingBehavior: "spacious", layoutBehavior: "editorial", imageBehavior: "large immersive", motionBehavior: "low", ctaBehavior: "refined", cardBehavior: "minimal", backgroundBehavior: "layered neutrals", accessibilityConstraints: ["avoid low contrast gold text"], suitableIndustries: ["real_estate", "hospitality", "architecture_interiors", "fashion"], unsuitableIndustries: ["government"] }),
  profile({ name: "Premium", typographyBehavior: "polished sans/display mix", colorBehavior: "warm contrast", spacingBehavior: "generous", layoutBehavior: "trust-first editorial", imageBehavior: "high-quality imagery", motionBehavior: "low", ctaBehavior: "confident", cardBehavior: "elevated", backgroundBehavior: "sectional", accessibilityConstraints: ["large readable type"], suitableIndustries: ["real_estate", "hospitality", "education", "automotive"], unsuitableIndustries: [] }),
  profile({ name: "Editorial", typographyBehavior: "magazine-like hierarchy", colorBehavior: "neutral with rich accent", spacingBehavior: "spacious", layoutBehavior: "story-led", imageBehavior: "large narrative media", motionBehavior: "low", ctaBehavior: "contextual", cardBehavior: "minimal", backgroundBehavior: "white/neutral", accessibilityConstraints: ["preserve heading order"], suitableIndustries: ["real_estate", "architecture_interiors", "hospitality", "creative_portfolio", "education"], unsuitableIndustries: [] }),
  profile({ name: "Corporate", typographyBehavior: "formal sans", colorBehavior: "stable neutral with institutional accent", spacingBehavior: "balanced", layoutBehavior: "structured", imageBehavior: "professional", motionBehavior: "low", ctaBehavior: "explicit", cardBehavior: "structured", backgroundBehavior: "clean bands", accessibilityConstraints: ["high contrast"], suitableIndustries: ["education", "professional_services", "legal_finance", "manufacturing_industrial"], unsuitableIndustries: [] }),
  profile({ name: "Creative", typographyBehavior: "expressive but readable", colorBehavior: "distinct accent system", spacingBehavior: "varied", layoutBehavior: "portfolio-led", imageBehavior: "expressive", motionBehavior: "medium", ctaBehavior: "clear", cardBehavior: "custom-feeling", backgroundBehavior: "visual bands", accessibilityConstraints: ["avoid chaotic contrast"], suitableIndustries: ["creative_portfolio", "architecture_interiors", "entertainment_events"], unsuitableIndustries: ["healthcare", "government"] }),
  profile({ name: "Organic", typographyBehavior: "soft human sans/serif", colorBehavior: "earthy natural palette", spacingBehavior: "comfortable", layoutBehavior: "human", imageBehavior: "natural", motionBehavior: "low", ctaBehavior: "warm", cardBehavior: "soft", backgroundBehavior: "warm surfaces", accessibilityConstraints: ["avoid low-contrast earth tones"], suitableIndustries: ["food_and_beverage", "beauty_wellness", "ngo_community", "ecommerce_d2c"], unsuitableIndustries: [] }),
  profile({ name: "Clinical", typographyBehavior: "highly legible sans", colorBehavior: "clean high-contrast calm", spacingBehavior: "clear", layoutBehavior: "low-risk", imageBehavior: "calm/contextual", motionBehavior: "none-low", ctaBehavior: "reassuring", cardBehavior: "simple", backgroundBehavior: "light clean", accessibilityConstraints: ["high contrast", "no tiny text"], suitableIndustries: ["healthcare"], unsuitableIndustries: ["entertainment_events"] }),
  profile({ name: "Hospitality", typographyBehavior: "warm display plus legible body", colorBehavior: "warm inviting", spacingBehavior: "immersive", layoutBehavior: "experience-led", imageBehavior: "large sensory", motionBehavior: "medium", ctaBehavior: "booking-friendly", cardBehavior: "image-led", backgroundBehavior: "warm bands", accessibilityConstraints: ["CTA contrast"], suitableIndustries: ["hospitality", "food_and_beverage", "travel"], unsuitableIndustries: [] }),
  profile({ name: "Industrial", typographyBehavior: "precise sturdy sans", colorBehavior: "high contrast technical", spacingBehavior: "structured", layoutBehavior: "specification-led", imageBehavior: "technical/product", motionBehavior: "low", ctaBehavior: "direct", cardBehavior: "structured", backgroundBehavior: "solid", accessibilityConstraints: ["strong contrast"], suitableIndustries: ["automotive", "manufacturing_industrial", "construction"], unsuitableIndustries: [] }),
  profile({ name: "Fashion", typographyBehavior: "stylized display", colorBehavior: "bold editorial", spacingBehavior: "spacious", layoutBehavior: "image-led", imageBehavior: "campaign imagery", motionBehavior: "medium", ctaBehavior: "commerce-clear", cardBehavior: "minimal", backgroundBehavior: "editorial", accessibilityConstraints: ["avoid text over low-contrast imagery"], suitableIndustries: ["fashion", "ecommerce_d2c", "creative_portfolio"], unsuitableIndustries: ["healthcare", "government"] }),
  profile({ name: "Bold", typographyBehavior: "strong sans/display", colorBehavior: "high contrast accent", spacingBehavior: "confident", layoutBehavior: "direct", imageBehavior: "high impact", motionBehavior: "medium", ctaBehavior: "prominent", cardBehavior: "solid", backgroundBehavior: "contrast bands", accessibilityConstraints: ["avoid excessive saturation"], suitableIndustries: ["automotive", "fitness", "entertainment_events", "technology_saas"], unsuitableIndustries: ["healthcare"] }),
  profile({ name: "Playful", typographyBehavior: "friendly rounded", colorBehavior: "bright controlled", spacingBehavior: "comfortable", layoutBehavior: "approachable", imageBehavior: "illustrative/product", motionBehavior: "medium", ctaBehavior: "friendly", cardBehavior: "soft", backgroundBehavior: "light playful", accessibilityConstraints: ["contrast-safe bright colors"], suitableIndustries: ["education", "ngo_community", "ecommerce_d2c"], unsuitableIndustries: ["legal_finance", "healthcare"] }),
  profile({ name: "Brutalist", typographyBehavior: "raw bold type", colorBehavior: "stark", spacingBehavior: "tight", layoutBehavior: "unconventional", imageBehavior: "raw", motionBehavior: "low", ctaBehavior: "stark", cardBehavior: "hard edge", backgroundBehavior: "flat", accessibilityConstraints: ["maintain usability"], suitableIndustries: ["creative_portfolio", "entertainment_events"], unsuitableIndustries: ["healthcare", "government", "legal_finance"] }),
  profile({ name: "Technology", typographyBehavior: "precise modern sans", colorBehavior: "cool neutral with accent", spacingBehavior: "systematic", layoutBehavior: "product-led", imageBehavior: "interface/product", motionBehavior: "low-medium", ctaBehavior: "demo-focused", cardBehavior: "structured", backgroundBehavior: "clean gradient-free surfaces", accessibilityConstraints: ["avoid low contrast neon"], suitableIndustries: ["technology_saas", "automotive", "manufacturing_industrial"], unsuitableIndustries: [] }),
  profile({ name: "Warm", typographyBehavior: "human readable", colorBehavior: "warm approachable", spacingBehavior: "comfortable", layoutBehavior: "service-friendly", imageBehavior: "human/contextual", motionBehavior: "low", ctaBehavior: "inviting", cardBehavior: "soft", backgroundBehavior: "warm bands", accessibilityConstraints: ["warm contrast"], suitableIndustries: ["food_and_beverage", "education", "professional_services", "ngo_community"], unsuitableIndustries: [] }),
  profile({ name: "Heritage", typographyBehavior: "classic serif plus readable sans", colorBehavior: "deep classic palette", spacingBehavior: "measured", layoutBehavior: "traditional", imageBehavior: "crafted", motionBehavior: "low", ctaBehavior: "formal", cardBehavior: "framed", backgroundBehavior: "textured intent only", accessibilityConstraints: ["avoid ornate unreadability"], suitableIndustries: ["hospitality", "food_and_beverage", "education", "professional_services"], unsuitableIndustries: ["technology_saas"] }),
]);

const preferences: Record<string, DesignLanguageName[]> = {
  healthcare: ["Clinical", "Minimal", "Modern"],
  real_estate: ["Luxury", "Premium", "Editorial"],
  food_and_beverage: ["Hospitality", "Warm", "Organic"],
  automotive: ["Industrial", "Bold", "Technology"],
  education: ["Warm", "Corporate", "Modern"],
  ecommerce_d2c: ["Modern", "Fashion", "Organic"],
  hospitality: ["Hospitality", "Luxury", "Warm"],
  architecture_interiors: ["Editorial", "Minimal", "Luxury"],
  manufacturing_industrial: ["Industrial", "Corporate", "Technology"],
  technology_saas: ["Technology", "Modern", "Corporate"],
  ngo_community: ["Warm", "Organic", "Corporate"],
};

/**
 * Selects a deterministic design language profile.
 *
 * @example
 * const language = selectDesignLanguage(input, context);
 */
export function selectDesignLanguage(input: DesignInput, context: DesignFamilyContext): DesignLanguageProfile {
  const brandPremium = input.brandProfile?.premiumLevel;
  const preferred = brandPremium === "luxury" ? ["Luxury", "Editorial", "Premium"] : preferences[context.family] ?? ["Modern", "Minimal", "Corporate"];
  return DESIGN_LANGUAGE_PROFILES.find((language) => preferred.includes(language.name) && !language.unsuitableIndustries.includes(context.family)) ?? DESIGN_LANGUAGE_PROFILES[1];
}
