import type { PatternDefinition } from "./patternIntelligence";

const pattern = (definition: PatternDefinition): PatternDefinition => Object.freeze(definition);

/**
 * Builds the local semantic pattern catalog.
 *
 * @example
 * const catalog = buildPatternCatalog();
 */
export function buildPatternCatalog(): PatternDefinition[] {
  return [
    pattern({ id: "editorial_hero", name: "Editorial Hero", category: "hero", role: "orientation", reusable: true, compatibleFamilies: ["real_estate", "hospitality", "architecture_interiors", "ecommerce_d2c", "creative_portfolio", "education"], compatibleArchetypes: ["lead_generation", "brochure", "portfolio", "property_showcase", "hotel_resort", "product_launch"], tags: ["premium", "orientation"], requiredFacts: ["business category", "primary promise"], requiredAssets: ["hero media if available"], conversionImpact: ["establishes first-scroll intent"], trustImpact: ["sets confidence before proof"], seoImpact: ["supports primary category and locality"], accessibilityNotes: ["must preserve clear heading hierarchy"], mobileBehavior: ["headline and CTA remain visible without crowding"], risks: ["too vague without facts"], conflictsWith: [] }),
    pattern({ id: "product_value_hero", name: "Product Value Hero", category: "hero", role: "orientation", reusable: true, compatibleFamilies: ["ecommerce_d2c", "technology_saas", "manufacturing_industrial"], compatibleArchetypes: ["ecommerce", "product_launch", "saas", "catalogue"], tags: ["product", "commerce"], requiredFacts: ["product value proposition"], requiredAssets: ["product imagery if available"], conversionImpact: ["clarifies purchase or demo intent early"], trustImpact: ["requires proof before strong claims"], seoImpact: ["supports product category"], accessibilityNotes: ["avoid image-only value proposition"], mobileBehavior: ["product value and action appear early"], risks: ["can become generic SaaS if proof is missing"], conflictsWith: [] }),
    pattern({ id: "booking_hero", name: "Booking Hero", category: "booking", role: "conversion", reusable: true, compatibleFamilies: ["hospitality", "food_and_beverage", "travel", "automotive"], compatibleArchetypes: ["booking", "hotel_resort", "restaurant_menu", "lead_generation"], tags: ["booking", "conversion"], requiredFacts: ["booking method"], requiredAssets: [], conversionImpact: ["makes booking path obvious"], trustImpact: ["needs availability caution"], seoImpact: ["supports booking intent"], accessibilityNotes: ["forms/actions must be keyboard reachable later"], mobileBehavior: ["booking action visible early"], risks: ["must not imply availability without facts"], conflictsWith: ["pricing_table"] }),
    pattern({ id: "appointment_hero", name: "Appointment Hero", category: "appointment", role: "conversion", reusable: true, compatibleFamilies: ["healthcare", "beauty_wellness", "fitness", "professional_services", "legal_finance", "automotive"], compatibleArchetypes: ["appointment", "booking", "lead_generation"], tags: ["appointment", "service"], requiredFacts: ["appointment process"], requiredAssets: [], conversionImpact: ["clarifies appointment intent"], trustImpact: ["requires trust before pressure"], seoImpact: ["supports appointment intent"], accessibilityNotes: ["primary action label must be clear later"], mobileBehavior: ["appointment path reachable early"], risks: ["can over-ask before trust"], conflictsWith: ["pricing_table"] }),
    pattern({ id: "trust_band", name: "Trust Band", category: "trust", role: "trust-building", reusable: true, compatibleFamilies: ["healthcare", "real_estate", "education", "automotive", "professional_services", "technology_saas", "manufacturing_industrial"], compatibleArchetypes: ["lead_generation", "brochure", "appointment", "booking", "catalogue"], tags: ["trust"], requiredFacts: ["trust signals"], requiredAssets: [], conversionImpact: ["reduces hesitation before CTA"], trustImpact: ["surfaces verified proof requirements"], seoImpact: ["supports entity trust if factual"], accessibilityNotes: ["avoid tiny proof labels"], mobileBehavior: ["compact proof without crowding"], risks: ["must not invent certifications or awards"], conflictsWith: [] }),
    pattern({ id: "proof_stack", name: "Proof Stack", category: "proof", role: "proof", reusable: true, compatibleFamilies: ["healthcare", "education", "automotive", "technology_saas", "professional_services", "ngo_community"], compatibleArchetypes: ["lead_generation", "brochure", "appointment", "saas"], tags: ["proof"], requiredFacts: ["proof points"], requiredAssets: [], conversionImpact: ["supports high-commitment conversion"], trustImpact: ["requires evidence for claims"], seoImpact: ["supports expertise signals if factual"], accessibilityNotes: ["proof hierarchy must remain readable"], mobileBehavior: ["proof chunks should not become long walls"], risks: ["fake proof risk"], conflictsWith: [] }),
    pattern({ id: "locality_map_narrative", name: "Locality Map Narrative", category: "locality", role: "locality", reusable: true, compatibleFamilies: ["real_estate", "food_and_beverage", "healthcare", "hospitality", "automotive", "education"], compatibleArchetypes: ["lead_generation", "booking", "appointment", "property_showcase", "restaurant_menu", "hotel_resort"], tags: ["locality"], requiredFacts: ["location or service area"], requiredAssets: ["map or location media if available"], conversionImpact: ["reduces location friction"], trustImpact: ["grounds claims in place"], seoImpact: ["supports local search context"], accessibilityNotes: ["map must not be only location source later"], mobileBehavior: ["address/action reachable near map"], risks: ["must not invent nearby landmarks"], conflictsWith: [] }),
    pattern({ id: "lifestyle_gallery", name: "Lifestyle Gallery", category: "gallery", role: "exploration", reusable: true, compatibleFamilies: ["real_estate", "hospitality", "food_and_beverage", "architecture_interiors", "creative_portfolio"], compatibleArchetypes: ["portfolio", "property_showcase", "hotel_resort", "restaurant_menu", "brochure"], tags: ["gallery"], requiredFacts: [], requiredAssets: ["gallery images"], conversionImpact: ["builds desire before conversion"], trustImpact: ["needs authentic media"], seoImpact: ["supports visual subject matter if labeled later"], accessibilityNotes: ["images need meaningful alt later"], mobileBehavior: ["gallery must not bury CTA"], risks: ["placeholder image risk"], conflictsWith: [] }),
    pattern({ id: "service_matrix", name: "Service Matrix", category: "service", role: "exploration", reusable: true, compatibleFamilies: ["healthcare", "automotive", "professional_services", "beauty_wellness", "fitness", "construction"], compatibleArchetypes: ["brochure", "appointment", "lead_generation", "catalogue"], tags: ["service"], requiredFacts: ["service list"], requiredAssets: [], conversionImpact: ["helps visitors find fit"], trustImpact: ["reduces ambiguity"], seoImpact: ["supports service category coverage"], accessibilityNotes: ["avoid dense card grids later"], mobileBehavior: ["service scan remains concise"], risks: ["generic card-grid overuse"], conflictsWith: [] }),
    pattern({ id: "menu_preview", name: "Menu Preview", category: "menu", role: "exploration", reusable: true, compatibleFamilies: ["food_and_beverage", "hospitality"], compatibleArchetypes: ["restaurant_menu", "booking", "brochure"], tags: ["menu"], requiredFacts: ["menu items"], requiredAssets: ["food imagery if available"], conversionImpact: ["supports reservation/order decision"], trustImpact: ["must keep prices/hours factual"], seoImpact: ["supports menu/cuisine topics"], accessibilityNotes: ["menu text must not be image-only later"], mobileBehavior: ["menu preview appears early"], risks: ["must not invent prices"], conflictsWith: [] }),
    pattern({ id: "course_catalogue_preview", name: "Course Catalogue Preview", category: "catalogue", role: "exploration", reusable: true, compatibleFamilies: ["education"], compatibleArchetypes: ["catalogue", "brochure", "lead_generation"], tags: ["education", "catalogue"], requiredFacts: ["programs or courses"], requiredAssets: [], conversionImpact: ["supports admissions enquiry"], trustImpact: ["program facts before claims"], seoImpact: ["supports course category coverage"], accessibilityNotes: ["course cards must be scannable later"], mobileBehavior: ["course scan before enquiry"], risks: ["must not invent outcomes"], conflictsWith: [] }),
    pattern({ id: "vehicle_service_matrix", name: "Vehicle Service Matrix", category: "service", role: "exploration", reusable: true, compatibleFamilies: ["automotive"], compatibleArchetypes: ["catalogue", "booking", "lead_generation"], tags: ["automotive", "service"], requiredFacts: ["vehicle services or inventory"], requiredAssets: [], conversionImpact: ["supports booking/quote/test-drive"], trustImpact: ["terms and authorization must be factual"], seoImpact: ["supports service/inventory topics"], accessibilityNotes: ["avoid hidden terms"], mobileBehavior: ["quick service/inventory scan"], risks: ["must not invent inventory"], conflictsWith: [] }),
    pattern({ id: "project_showcase", name: "Project Showcase", category: "portfolio", role: "exploration", reusable: true, compatibleFamilies: ["real_estate", "architecture_interiors", "construction"], compatibleArchetypes: ["property_showcase", "portfolio", "lead_generation"], tags: ["showcase"], requiredFacts: ["project facts"], requiredAssets: ["project media"], conversionImpact: ["supports enquiry by showing fit"], trustImpact: ["requires authentic project details"], seoImpact: ["supports project/location topics"], accessibilityNotes: ["media needs captions later"], mobileBehavior: ["project highlights before CTA"], risks: ["must not invent availability"], conflictsWith: [] }),
    pattern({ id: "product_feature_stack", name: "Product Feature Stack", category: "product", role: "exploration", reusable: true, compatibleFamilies: ["ecommerce_d2c", "technology_saas", "manufacturing_industrial"], compatibleArchetypes: ["ecommerce", "product_launch", "saas", "catalogue"], tags: ["product"], requiredFacts: ["product features"], requiredAssets: [], conversionImpact: ["supports purchase/demo decision"], trustImpact: ["feature claims need facts"], seoImpact: ["supports product features"], accessibilityNotes: ["features should be text-readable"], mobileBehavior: ["short feature chunks"], risks: ["generic SaaS pattern risk"], conflictsWith: [] }),
    pattern({ id: "faq_objection_handling", name: "FAQ Objection Handling", category: "FAQ", role: "objection-handling", reusable: true, compatibleFamilies: ["healthcare", "real_estate", "food_and_beverage", "education", "automotive", "ecommerce_d2c", "hospitality", "architecture_interiors"], compatibleArchetypes: ["lead_generation", "booking", "appointment", "catalogue", "brochure"], tags: ["faq", "objection"], requiredFacts: ["objections"], requiredAssets: [], conversionImpact: ["reduces final friction"], trustImpact: ["keeps claims explicit"], seoImpact: ["supports long-tail questions"], accessibilityNotes: ["accordion must remain keyboard accessible later"], mobileBehavior: ["FAQ near conversion"], risks: ["must not invent answers"], conflictsWith: [] }),
    pattern({ id: "final_conversion_block", name: "Final Conversion Block", category: "conversion-block", role: "closure", reusable: true, compatibleFamilies: ["healthcare", "real_estate", "food_and_beverage", "education", "automotive", "ecommerce_d2c", "hospitality", "architecture_interiors", "professional_services"], compatibleArchetypes: ["lead_generation", "booking", "appointment", "ecommerce", "brochure"], tags: ["conversion"], requiredFacts: ["primary conversion goal"], requiredAssets: [], conversionImpact: ["closes journey with action"], trustImpact: ["should follow proof"], seoImpact: [], accessibilityNotes: ["CTA must be clear later"], mobileBehavior: ["final action not hidden"], risks: ["too aggressive without trust"], conflictsWith: [] }),
    pattern({ id: "sticky_mobile_cta", name: "Sticky Mobile CTA", category: "sticky-action", role: "conversion", reusable: true, compatibleFamilies: ["healthcare", "real_estate", "food_and_beverage", "automotive", "hospitality", "education", "ecommerce_d2c"], compatibleArchetypes: ["lead_generation", "booking", "appointment", "ecommerce", "restaurant_menu"], tags: ["mobile", "conversion"], requiredFacts: ["primary CTA"], requiredAssets: [], conversionImpact: ["keeps action reachable on mobile"], trustImpact: ["must not bypass trust"], seoImpact: [], accessibilityNotes: ["must not obscure content later"], mobileBehavior: ["persistent but unobtrusive"], risks: ["can feel pushy"], conflictsWith: [] }),
    pattern({ id: "founder_story", name: "Founder Story", category: "founder-story", role: "story", reusable: true, compatibleFamilies: ["architecture_interiors", "creative_portfolio", "ecommerce_d2c", "professional_services", "ngo_community", "education"], compatibleArchetypes: ["portfolio", "brochure", "lead_generation", "product_launch"], tags: ["story"], requiredFacts: ["founder or studio facts"], requiredAssets: ["portrait if provided"], conversionImpact: ["builds human trust"], trustImpact: ["must use provided biography"], seoImpact: ["supports entity story"], accessibilityNotes: ["avoid text over complex images later"], mobileBehavior: ["short story before CTA"], risks: ["must not invent biography"], conflictsWith: [] }),
    pattern({ id: "process_timeline", name: "Process Timeline", category: "process", role: "trust-building", reusable: true, compatibleFamilies: ["architecture_interiors", "professional_services", "education", "construction", "healthcare", "automotive"], compatibleArchetypes: ["brochure", "lead_generation", "appointment"], tags: ["process"], requiredFacts: ["process steps"], requiredAssets: [], conversionImpact: ["reduces process anxiety"], trustImpact: ["shows clarity"], seoImpact: ["supports process queries"], accessibilityNotes: ["timeline must be linear-readable later"], mobileBehavior: ["steps stack cleanly"], risks: ["must not invent process steps"], conflictsWith: [] }),
    pattern({ id: "portfolio_showcase", name: "Portfolio Showcase", category: "portfolio", role: "proof", reusable: true, compatibleFamilies: ["architecture_interiors", "creative_portfolio", "construction", "professional_services"], compatibleArchetypes: ["portfolio", "brochure", "lead_generation"], tags: ["portfolio"], requiredFacts: ["portfolio items"], requiredAssets: ["portfolio media"], conversionImpact: ["supports consultation"], trustImpact: ["authentic proof"], seoImpact: ["supports project category"], accessibilityNotes: ["captions required later"], mobileBehavior: ["short portfolio highlights"], risks: ["must not invent projects"], conflictsWith: [] }),
    pattern({ id: "comparison_section", name: "Comparison Section", category: "comparison", role: "exploration", reusable: true, compatibleFamilies: ["ecommerce_d2c", "automotive", "technology_saas", "education", "manufacturing_industrial"], compatibleArchetypes: ["catalogue", "ecommerce", "saas", "lead_generation"], tags: ["comparison"], requiredFacts: ["comparable options"], requiredAssets: [], conversionImpact: ["helps decide fit"], trustImpact: ["requires factual comparisons"], seoImpact: ["supports comparison intent"], accessibilityNotes: ["table semantics needed later"], mobileBehavior: ["comparison must remain readable"], risks: ["must not invent competitors or specs"], conflictsWith: [] }),
    pattern({ id: "review_proof_block", name: "Review Proof Block", category: "testimonial", role: "proof", reusable: true, compatibleFamilies: ["food_and_beverage", "hospitality", "ecommerce_d2c", "automotive", "professional_services"], compatibleArchetypes: ["booking", "ecommerce", "brochure", "lead_generation"], tags: ["review", "proof"], requiredFacts: ["reviews or testimonials"], requiredAssets: [], conversionImpact: ["supports trust near conversion"], trustImpact: ["only if provided"], seoImpact: ["supports reputation context if factual"], accessibilityNotes: ["quotes need attribution later"], mobileBehavior: ["short proof snippets"], risks: ["fake testimonial risk"], conflictsWith: [] }),
    pattern({ id: "contact_lead_capture", name: "Contact Lead Capture", category: "lead-capture", role: "conversion", reusable: true, compatibleFamilies: ["healthcare", "real_estate", "education", "automotive", "professional_services", "architecture_interiors"], compatibleArchetypes: ["lead_generation", "appointment", "booking"], tags: ["lead"], requiredFacts: ["contact path"], requiredAssets: [], conversionImpact: ["captures qualified intent"], trustImpact: ["must follow enough context"], seoImpact: [], accessibilityNotes: ["form labels required later"], mobileBehavior: ["short mobile form"], risks: ["too early without trust"], conflictsWith: [] }),
    pattern({ id: "footer_trust_closure", name: "Footer Trust Closure", category: "footer", role: "closure", reusable: true, compatibleFamilies: ["healthcare", "real_estate", "food_and_beverage", "education", "automotive", "ecommerce_d2c", "hospitality", "architecture_interiors", "technology_saas", "ngo_community"], compatibleArchetypes: ["lead_generation", "brochure", "booking", "appointment", "ecommerce", "portfolio"], tags: ["footer", "trust"], requiredFacts: ["contact or trust closure facts"], requiredAssets: [], conversionImpact: ["supports late-stage action"], trustImpact: ["reinforces identity and policies"], seoImpact: ["supports entity/contact consistency"], accessibilityNotes: ["navigation landmarks later"], mobileBehavior: ["compact closure"], risks: ["must not invent legal or policy facts"], conflictsWith: [] }),
  ];
}
