"use client";
import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { useCallback, useEffect, useState } from "react";
import { useWorkspace } from "../../../components/WorkspaceContext";
import { ArrowLeft, CalendarDays, CheckCircle2, Clock3, Flame, Mail, MessageCircle, Phone, Plus, Snowflake, StickyNote, Trash2, UserRoundCheck, Video, Zap } from "lucide-react";
type Communication={id:string;type:string;direction:string;subject?:string;content:string;createdBy?:string;createdAt:string};
type Lead={id:string;name:string;email?:string;phone?:string;company?:string;message?:string;source:string;status:string;score:number;temperature:string;assignedToId?:string;assignedToName?:string;notes?:string;createdAt:string;updatedAt:string;communications:Communication[]};
type Staff={id:string;name:string;email?:string};
async function json<T>(r:Response):Promise<T>{const raw=await r.text();let body:unknown={};if(raw)try{body=JSON.parse(raw)}catch{throw new Error("The server returned an invalid response")};if(!r.ok)throw new Error((body as {error?:string}).error||`Request failed (${r.status})`);return body as T}
const statusTone:Record<string,string>={NEW:"text-blue-600 bg-blue-500/10",CONTACTED:"text-cyan-600 bg-cyan-500/10",QUALIFIED:"text-violet-600 bg-violet-500/10",WON:"text-emerald-600 bg-emerald-500/10",LOST:"text-rose-600 bg-rose-500/10"};
export default function LeadDetails(){const {leadId,siteSlug}=useParams<{leadId:string;siteSlug:string}>(),{currentWebsite}=useWorkspace(),router=useRouter();const [lead,setLead]=useState<Lead|null>(null),[staff,setStaff]=useState<Staff[]>([]),[error,setError]=useState(""),[composer,setComposer]=useState(false),[type,setType]=useState("NOTE"),[content,setContent]=useState("");
 const load=useCallback(async()=>{if(!currentWebsite)return;try{const [a,b]=await Promise.all([fetch(`/api/crm/leads/${leadId}?siteId=${currentWebsite.id}`).then(r=>json<{lead:Lead}>(r)),fetch(`/api/crm/staff?siteId=${currentWebsite.id}`).then(r=>json<{staff:Staff[]}>(r))]);setLead(a.lead);setStaff(b.staff)}catch(e){setError(e instanceof Error?e.message:"Could not load lead")}},[currentWebsite,leadId]);useEffect(()=>{queueMicrotask(()=>void load())},[load]);
 async function update(data:Record<string,unknown>){if(!currentWebsite)return;try{await json(await fetch(`/api/crm/leads/${leadId}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({siteId:currentWebsite.id,...data})}));void load()}catch(e){setError(e instanceof Error?e.message:"Could not update lead")}}
 async function log(){if(!currentWebsite||!content.trim())return;try{await json(await fetch(`/api/crm/leads/${leadId}/communications`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({siteId:currentWebsite.id,type,content})}));setContent("");setComposer(false);void load()}catch(e){setError(e instanceof Error?e.message:"Could not save communication")}}
 async function remove(){if(!currentWebsite||!confirm("Delete this lead and its communication history?"))return;await fetch(`/api/crm/leads/${leadId}?siteId=${currentWebsite.id}`,{method:"DELETE"});router.push(`/app/${siteSlug}/crm`)}
 if(!lead)return <div className="mx-auto max-w-[1400px] py-20 text-center dashboard-muted">{error||"Loading lead workspace…"}</div>;
 const actions=[{label:"Email",icon:Mail,href:lead.email?`mailto:${lead.email}`:"#",type:"EMAIL"},{label:"Call",icon:Phone,href:lead.phone?`tel:${lead.phone}`:"#",type:"CALL"},{label:"WhatsApp",icon:MessageCircle,href:lead.phone?`https://wa.me/${lead.phone.replace(/\D/g,"")}`:"#",type:"WHATSAPP"}];
 return <div className="mx-auto max-w-[1450px] pb-12"><header className="flex flex-wrap items-center gap-4"><Link href={`/app/${siteSlug}/crm`} className="flex h-10 w-10 items-center justify-center rounded-xl border dashboard-border dashboard-hover"><ArrowLeft size={18}/></Link><div className="min-w-0 flex-1"><p className="text-xs dashboard-muted">CRM / Lead details</p><h1 className="truncate text-2xl font-semibold tracking-tight">{lead.name}</h1></div><button onClick={()=>void remove()} className="flex items-center gap-2 rounded-xl border border-rose-500/20 px-3 py-2 text-xs text-rose-500"><Trash2 size={14}/>Delete</button></header>{error&&<p className="mt-4 rounded-xl bg-rose-500/10 p-3 text-sm text-rose-500">{error}</p>}
 <section className="mt-6 grid gap-5 xl:grid-cols-[1fr_340px]"><main className="space-y-5"><article className="crm-ai rounded-2xl border border-blue-500/15 p-6"><div className="flex flex-wrap items-start gap-5"><span className="flex h-16 w-16 items-center justify-center rounded-2xl bg-gradient-to-br from-blue-600 to-cyan-400 text-xl font-bold text-white shadow-lg shadow-blue-500/20">{lead.name.slice(0,2).toUpperCase()}</span><div className="min-w-[200px] flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="text-xl font-semibold">{lead.name}</h2><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${statusTone[lead.status]}`}>{lead.status}</span></div><p className="mt-1 text-sm dashboard-muted">{lead.company||"Individual lead"} · {lead.source.replaceAll("-"," ")}</p><div className="mt-4 flex flex-wrap gap-2">{actions.map(a=><a key={a.label} href={a.href} target={a.label==="WhatsApp"?"_blank":undefined} onClick={()=>{setType(a.type);setComposer(true)}} className="flex items-center gap-2 rounded-xl border dashboard-border bg-white/60 px-3 py-2 text-xs font-semibold dark:bg-white/[.05]"><a.icon size={14}/>{a.label}</a>)}<button onClick={()=>{setType("MEETING");setComposer(true)}} className="flex items-center gap-2 rounded-xl border dashboard-border bg-white/60 px-3 py-2 text-xs font-semibold dark:bg-white/[.05]"><Video size={14}/>Meeting</button><button onClick={()=>{setType("NOTE");setComposer(true)}} className="flex items-center gap-2 rounded-xl bg-blue-600 px-3 py-2 text-xs font-semibold text-white"><Plus size={14}/>Log activity</button></div></div><div className="rounded-2xl bg-orange-500/10 p-4 text-center text-orange-600 dark:text-orange-300"><Flame className="mx-auto"/><strong className="mt-1 block text-2xl">{lead.score}</strong><span className="text-[10px]">INTENT SCORE</span></div></div></article>
 <article className="dashboard-card rounded-2xl p-6"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Communication history</h2><p className="mt-1 text-xs dashboard-muted">Calls, messages, meetings, emails, and notes</p></div><button onClick={()=>setComposer(true)} className="rounded-xl bg-blue-600 px-3 py-2 text-xs font-semibold text-white">Add activity</button></div>{composer&&<div className="mt-5 rounded-2xl border border-blue-500/20 bg-blue-500/[.06] p-4"><div className="flex flex-wrap gap-2">{["NOTE","CALL","EMAIL","WHATSAPP","MEETING"].map(x=><button key={x} onClick={()=>setType(x)} className={`rounded-lg px-3 py-1.5 text-xs ${type===x?'bg-blue-600 text-white':'dashboard-subtle'}`}>{x}</button>)}</div><textarea autoFocus value={content} onChange={e=>setContent(e.target.value)} rows={3} placeholder={`Add ${type.toLowerCase()} details…`} className="dashboard-input mt-3 w-full rounded-xl p-3"/><div className="mt-3 flex justify-end gap-2"><button onClick={()=>setComposer(false)} className="px-3 text-xs dashboard-muted">Cancel</button><button onClick={()=>void log()} className="rounded-lg bg-blue-600 px-4 py-2 text-xs font-semibold text-white">Save activity</button></div></div>}<div className="relative mt-6 space-y-1 before:absolute before:bottom-4 before:left-[17px] before:top-4 before:w-px before:bg-blue-500/20">{lead.communications.length?lead.communications.map(c=><div key={c.id} className="relative flex gap-4 rounded-xl p-3 dashboard-hover"><span className="z-10 flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-blue-500/10 text-blue-600 dark:text-blue-300">{c.type==="CALL"?<Phone size={15}/>:c.type==="EMAIL"?<Mail size={15}/>:c.type==="MEETING"?<Video size={15}/>:c.type==="WHATSAPP"?<MessageCircle size={15}/>:<StickyNote size={15}/>}</span><div><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-semibold">{c.type.toLowerCase()}</p><span className="text-[10px] dashboard-faint">{new Date(c.createdAt).toLocaleString()}</span></div><p className="mt-1 whitespace-pre-wrap text-sm leading-6 dashboard-muted">{c.content}</p></div></div>):<div className="py-12 text-center text-sm dashboard-muted"><Clock3 className="mx-auto mb-3"/>No communication logged yet.</div>}</div></article></main>
 <aside className="space-y-5"><article className="dashboard-card rounded-2xl p-5"><h2 className="flex items-center gap-2 font-semibold"><UserRoundCheck size={17} className="text-blue-500"/>Lead ownership</h2><label className="mt-5 block text-xs dashboard-muted">Allocated to<select value={lead.assignedToId||""} onChange={e=>{const person=staff.find(x=>x.id===e.target.value);void update({assignedToId:e.target.value,assignedToName:person?.name||""})}} className="dashboard-input mt-1.5 w-full rounded-xl px-3 py-2.5"><option value="">Unassigned</option>{staff.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="mt-4 block text-xs dashboard-muted">Pipeline stage<select value={lead.status} onChange={e=>void update({status:e.target.value})} className="dashboard-input mt-1.5 w-full rounded-xl px-3 py-2.5">{["NEW","CONTACTED","QUALIFIED","WON","LOST"].map(x=><option key={x}>{x}</option>)}</select></label></article>
 <article className="dashboard-card rounded-2xl p-5"><h2 className="font-semibold">Lead temperature</h2><p className="mt-1 text-xs dashboard-muted">Set urgency for your sales team.</p><div className="mt-4 grid grid-cols-3 gap-2">{[{id:"HOT",icon:Flame,tone:"text-orange-500 bg-orange-500/10 border-orange-500/25"},{id:"WARM",icon:Zap,tone:"text-amber-500 bg-amber-500/10 border-amber-500/25"},{id:"COLD",icon:Snowflake,tone:"text-blue-500 bg-blue-500/10 border-blue-500/25"}].map(x=><button key={x.id} onClick={()=>void update({temperature:x.id})} className={`rounded-xl border p-3 text-center ${lead.temperature===x.id?x.tone:'dashboard-border dashboard-muted'}`}><x.icon size={17} className="mx-auto"/><span className="mt-1 block text-[10px] font-bold">{x.id}</span></button>)}</div></article>
 <article className="dashboard-card rounded-2xl p-5"><h2 className="font-semibold">Contact details</h2><div className="mt-4 space-y-3 text-sm">{lead.email&&<a href={`mailto:${lead.email}`} className="flex items-center gap-3 dashboard-muted"><Mail size={15}/>{lead.email}</a>}{lead.phone&&<a href={`tel:${lead.phone}`} className="flex items-center gap-3 dashboard-muted"><Phone size={15}/>{lead.phone}</a>}<p className="flex items-center gap-3 dashboard-muted"><CalendarDays size={15}/>Added {new Date(lead.createdAt).toLocaleDateString()}</p></div>{lead.message&&<div className="mt-5 rounded-xl dashboard-subtle p-3 text-xs leading-5">{lead.message}</div>}</article><div className="rounded-2xl border border-emerald-500/20 bg-emerald-500/10 p-4 text-xs text-emerald-700 dark:text-emerald-300"><CheckCircle2 size={16}/><p className="mt-2 font-semibold">Next best action</p><p className="mt-1 opacity-80">Follow up personally and log the outcome to keep this lead’s context complete.</p></div></aside></section></div>}
