import type { InspirationSource } from "./inspirationProfile";

const source = (input: InspirationSource): InspirationSource => Object.freeze(input);

export function buildInspirationSources(): InspirationSource[] {
  return [
    source({ id: "apple_minimal_product", category: "Apple-like minimal product storytelling", themes: ["minimal", "product clarity", "restraint"], traits: [{ kind: "spacing", value: "airy" }, { kind: "typography", value: "large confident hierarchy" }, { kind: "composition", value: "single idea per beat" }, { kind: "motion", value: "subtle product reveal" }, { kind: "imagery", value: "product-first clarity" }, { kind: "cta", value: "simple direct action" }], suitableIndustries: ["ecommerce_d2c", "technology_saas", "manufacturing_industrial"], unsuitableIndustries: [], risks: ["can become sterile without brand warmth"] }),
    source({ id: "stripe_technical_clarity", category: "Stripe-like technical clarity", themes: ["technical clarity", "structured trust"], traits: [{ kind: "composition", value: "modular clarity" }, { kind: "typography", value: "precise readable sans" }, { kind: "background", value: "clean technical surfaces" }, { kind: "interaction", value: "clear state changes" }], suitableIndustries: ["technology_saas", "professional_services", "manufacturing_industrial"], unsuitableIndustries: ["food_and_beverage"], risks: ["generic SaaS risk"] }),
    source({ id: "linear_saas_precision", category: "Linear-like SaaS precision", themes: ["precision", "focus", "speed"], traits: [{ kind: "typography", value: "compact precision" }, { kind: "motion", value: "fast but controlled" }, { kind: "background", value: "quiet depth" }], suitableIndustries: ["technology_saas", "automotive"], unsuitableIndustries: ["healthcare"], risks: ["too cold for trust-sensitive service"] }),
    source({ id: "airbnb_trust_warmth", category: "Airbnb-like trust and warmth", themes: ["warmth", "human trust", "locality"], traits: [{ kind: "imagery", value: "human locality" }, { kind: "navigation", value: "simple discovery" }, { kind: "card", value: "soft trustworthy cards" }, { kind: "background", value: "warm clean surfaces" }], suitableIndustries: ["hospitality", "food_and_beverage", "travel", "education"], unsuitableIndustries: [], risks: ["must not imply reviews or availability"] }),
    source({ id: "awwwards_cinematic_editorial", category: "Awwwards-style cinematic editorial", themes: ["cinematic", "editorial", "immersive"], traits: [{ kind: "composition", value: "dramatic editorial beats" }, { kind: "motion", value: "cinematic but optional" }, { kind: "imagery", value: "large atmospheric media" }], suitableIndustries: ["real_estate", "hospitality", "architecture_interiors", "creative_portfolio"], unsuitableIndustries: ["healthcare", "government"], risks: ["can harm accessibility or editability if overused"] }),
    source({ id: "luxury_hospitality_editorial", category: "Luxury hospitality editorial", themes: ["luxury", "hospitality", "destination"], traits: [{ kind: "spacing", value: "spacious premium" }, { kind: "imagery", value: "immersive destination" }, { kind: "background", value: "warm layered neutrals" }, { kind: "cta", value: "refined booking action" }], suitableIndustries: ["hospitality", "real_estate", "architecture_interiors"], unsuitableIndustries: [], risks: ["avoid fake ratings or awards"] }),
    source({ id: "automotive_performance", category: "Automotive performance storytelling", themes: ["precision", "performance", "engineering"], traits: [{ kind: "composition", value: "high-contrast product/service beats" }, { kind: "motion", value: "controlled performance motion" }, { kind: "imagery", value: "reflective precision surfaces" }], suitableIndustries: ["automotive", "manufacturing_industrial"], unsuitableIndustries: ["healthcare"], risks: ["must not imply authorization, inventory, or discounts"] }),
    source({ id: "healthcare_reassurance", category: "Healthcare clarity and reassurance", themes: ["clinical", "reassuring", "legible"], traits: [{ kind: "typography", value: "high legibility" }, { kind: "spacing", value: "calm readable spacing" }, { kind: "motion", value: "minimal low-anxiety motion" }, { kind: "imagery", value: "privacy-safe care context" }], suitableIndustries: ["healthcare"], unsuitableIndustries: [], risks: ["no fake doctors, credentials, or certifications"] }),
    source({ id: "restaurant_sensory", category: "Restaurant sensory storytelling", themes: ["sensory", "warm", "ambience"], traits: [{ kind: "imagery", value: "food and ambience texture" }, { kind: "background", value: "warm hospitality surfaces" }, { kind: "cta", value: "reservation/order clarity" }], suitableIndustries: ["food_and_beverage", "hospitality"], unsuitableIndustries: [], risks: ["no fake hours, prices, or availability"] }),
    source({ id: "architecture_portfolio", category: "Architecture studio portfolio", themes: ["portfolio", "materials", "spatial calm"], traits: [{ kind: "composition", value: "portfolio-led editorial sequence" }, { kind: "imagery", value: "material and space detail" }, { kind: "spacing", value: "negative space" }], suitableIndustries: ["architecture_interiors", "creative_portfolio", "construction"], unsuitableIndustries: [], risks: ["no fake projects or awards"] }),
    source({ id: "premium_d2c_product", category: "Premium D2C product storytelling", themes: ["product-led", "commerce", "premium"], traits: [{ kind: "imagery", value: "product detail and lifestyle support" }, { kind: "cta", value: "purchase-oriented clarity" }, { kind: "card", value: "product cards only if facts exist" }], suitableIndustries: ["ecommerce_d2c", "fashion"], unsuitableIndustries: [], risks: ["no fake reviews or shipping promises"] }),
    source({ id: "education_trust_aspiration", category: "Education trust and aspiration", themes: ["trust", "aspiration", "accessibility"], traits: [{ kind: "typography", value: "accessible institutional clarity" }, { kind: "composition", value: "program-to-admissions narrative" }, { kind: "imagery", value: "campus/program media if provided" }], suitableIndustries: ["education"], unsuitableIndustries: [], risks: ["no fake outcomes, placements, or accreditation"] }),
  ];
}
