"use client";

import { FormEvent, useEffect, useState } from "react";
import { Bot, Building2, Check, Copy, Globe2, Loader2, ShieldCheck } from "lucide-react";

type SettingsData = { tenant: { id:string; name:string; domain:string|null; isActive:boolean; aiSuspended:boolean; createdAt:string }; owner:{name:string|null;email:string|null}|null; canManage:boolean };

export default function TenantSettingsPage() {
  const [data,setData]=useState<SettingsData|null>(null); const [form,setForm]=useState({name:"",domain:"",aiSuspended:false}); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState<{kind:"ok"|"error";text:string}|null>(null);
  useEffect(()=>{fetch("/api/tenant/settings",{cache:"no-store"}).then(async response=>{const payload=await response.json();if(!response.ok)throw new Error(payload.error);return payload}).then(payload=>{setData(payload);setForm({name:payload.tenant.name,domain:payload.tenant.domain||"",aiSuspended:payload.tenant.aiSuspended})}).catch(error=>setMessage({kind:"error",text:error instanceof Error?error.message:"Settings could not be loaded."})).finally(()=>setLoading(false))},[]);
  async function save(event:FormEvent){event.preventDefault();setSaving(true);setMessage(null);try{const response=await fetch("/api/tenant/settings",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(form)});const payload=await response.json();if(!response.ok)throw new Error(payload.error);setData(current=>current?{...current,tenant:payload.tenant}:current);setMessage({kind:"ok",text:"Workspace settings saved."})}catch(error){setMessage({kind:"error",text:error instanceof Error?error.message:"Settings could not be saved."})}finally{setSaving(false)}}
  if(loading)return <div className="grid min-h-[55vh] place-items-center"><Loader2 className="animate-spin dashboard-muted"/></div>;
  return <div className="mx-auto max-w-5xl pb-12"><header><p className="text-sm font-medium text-blue-600 dark:text-blue-400">Tenant administration</p><h1 className="mt-1 text-3xl font-semibold tracking-[-.04em]">Workspace settings</h1><p className="mt-2 text-sm dashboard-muted">Manage the identity and operating preferences for this tenant.</p></header>{message?<div role="status" className={`mt-5 rounded-xl border px-4 py-3 text-sm ${message.kind==="error"?"border-rose-500/20 bg-rose-500/10 text-rose-500":"border-emerald-500/20 bg-emerald-500/10 text-emerald-600 dark:text-emerald-400"}`}>{message.text}</div>:null}<form onSubmit={save} className="mt-6 space-y-6">
    <SettingsSection icon={<Building2/>} title="Workspace identity" description="Shown throughout dashboards, billing and team invitations."><Field label="Workspace name" value={form.name} onChange={name=>setForm({...form,name})} disabled={!data?.canManage}/><Field label="Workspace ID" value={data?.tenant.id||""} readOnly action={<button type="button" onClick={()=>navigator.clipboard.writeText(data?.tenant.id||"")} className="rounded-lg p-2 dashboard-hover" aria-label="Copy workspace ID"><Copy size={15}/></button>}/></SettingsSection>
    <SettingsSection icon={<Globe2/>} title="Workspace domain" description="The default domain associated with this tenant. Website-specific domains remain in website settings."><Field label="Primary domain" value={form.domain} onChange={domain=>setForm({...form,domain})} placeholder="example.com" disabled={!data?.canManage}/><Field label="Workspace status" value={data?.tenant.isActive?"Active":"Inactive"} readOnly/></SettingsSection>
    <SettingsSection icon={<Bot/>} title="AI availability" description="Pause new AI generation across every website in this workspace."><label className="sm:col-span-2 flex items-center justify-between gap-4 rounded-2xl border dashboard-border p-4"><div><p className="text-sm font-medium">Pause AI generation</p><p className="mt-1 text-xs leading-5 dashboard-muted">Existing content remains available. New AI jobs are blocked until resumed.</p></div><button type="button" role="switch" aria-checked={form.aiSuspended} disabled={!data?.canManage} onClick={()=>setForm({...form,aiSuspended:!form.aiSuspended})} className={`relative h-7 w-12 rounded-full transition ${form.aiSuspended?"bg-amber-500":"bg-slate-300 dark:bg-slate-700"}`}><span className={`absolute top-1 h-5 w-5 rounded-full bg-white shadow transition ${form.aiSuspended?"left-6":"left-1"}`}/></button></label></SettingsSection>
    <section className="dashboard-card rounded-3xl p-5 sm:p-7"><div className="flex gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-500/10 text-emerald-500"><ShieldCheck size={19}/></span><div><h2 className="font-semibold">Ownership</h2><p className="mt-1 text-sm dashboard-muted">Workspace owner: {data?.owner?.name||data?.owner?.email||"Not assigned"}</p><p className="mt-1 text-xs dashboard-faint">Created {data?.tenant.createdAt?new Date(data.tenant.createdAt).toLocaleDateString():"—"}</p></div></div></section>
    {data?.canManage?<div className="sticky bottom-3 flex justify-end rounded-2xl border dashboard-border dashboard-card-strong p-3"><button disabled={saving} className="dashboard-primary-button flex items-center gap-2 rounded-xl px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-60">{saving?<Loader2 size={16} className="animate-spin"/>:<Check size={16}/>} Save settings</button></div>:<p className="rounded-xl border dashboard-border p-4 text-sm dashboard-muted">You have read-only access to these workspace settings.</p>}
  </form></div>;
}
function SettingsSection({icon,title,description,children}:{icon:React.ReactNode;title:string;description:string;children:React.ReactNode}){return <section className="dashboard-card rounded-3xl p-5 sm:p-7"><div className="mb-6 flex gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-blue-500/10 text-blue-500 [&>svg]:h-5 [&>svg]:w-5">{icon}</span><div><h2 className="font-semibold">{title}</h2><p className="mt-1 text-sm dashboard-muted">{description}</p></div></div><div className="grid gap-5 sm:grid-cols-2">{children}</div></section>}
function Field({label,value,onChange,placeholder,disabled,readOnly,action}:{label:string;value:string;onChange?:(value:string)=>void;placeholder?:string;disabled?:boolean;readOnly?:boolean;action?:React.ReactNode}){return <label><span className="mb-2 block text-sm font-medium">{label}</span><div className="dashboard-input flex items-center rounded-xl pr-1"><input value={value} onChange={event=>onChange?.(event.target.value)} placeholder={placeholder} disabled={disabled} readOnly={readOnly} className="min-w-0 flex-1 bg-transparent px-3 py-2.5 text-sm outline-none disabled:opacity-60"/>{action}</div></label>}
