import type { ComponentVariant } from "../types";

export const componentVariants: ComponentVariant[] = [
  {
    id: "hero.architectural.luxury",
    role: "hero",
    label: "Architectural Luxury Hero",
    industries: ["real-estate", "architecture", "construction"],
    visualModes: ["luxury", "editorial", "image-led"],
    density: "balanced",
    mediaRequirement: "image",
    conversionStrength: 10,
    requiredProps: ["headline", "body", "primaryCta", "backgroundPrompt"],
  },
  {
    id: "project-card.editorial",
    role: "featured-projects",
    label: "Editorial Project Cards",
    industries: ["real-estate"],
    visualModes: ["editorial", "comparison"],
    density: "dense",
    mediaRequirement: "image",
    conversionStrength: 8,
    requiredProps: ["title", "location", "status", "details", "cta"],
  },
  {
    id: "about.split-editorial",
    role: "about-developer",
    label: "Split Editorial About",
    industries: ["real-estate", "architecture", "professional-services"],
    visualModes: ["editorial", "trust"],
    density: "balanced",
    mediaRequirement: "image",
    conversionStrength: 6,
    requiredProps: ["title", "body", "proofPoints"],
  },
  {
    id: "gallery.editorial-grid",
    role: "amenities-gallery",
    label: "Editorial Gallery Grid",
    industries: ["real-estate", "hospitality", "portfolio"],
    visualModes: ["gallery", "inspection"],
    density: "dense",
    mediaRequirement: "gallery",
    conversionStrength: 7,
    requiredProps: ["items", "captions"],
  },
  {
    id: "cta.concierge",
    role: "bottom-cta",
    label: "Concierge CTA",
    industries: ["real-estate", "healthcare", "hospitality"],
    visualModes: ["conversion", "trust"],
    density: "balanced",
    mediaRequirement: "none",
    conversionStrength: 10,
    requiredProps: ["title", "body", "primaryCta"],
  },
];
