import crypto from "node:crypto";
import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@buildez/db";
import { decryptSecret } from "@/lib/shopez";

export async function POST(req: NextRequest) {
  const b = await req.json().catch(() => null); const order = b?.orderId && await prisma.shopOrder.findUnique({ where: { id: b.orderId }, include: { items: true, shop: { include: { payments: true } } } });
  if (!order || !order.providerOrderId) return NextResponse.json({ error: "Order not found" }, { status: 404 });
  if (order.paymentStatus === "PAID") return NextResponse.json({ success: true, orderNumber: order.orderNumber });
  if (order.provider === "RAZORPAY") { const integration = order.shop.payments.find(x => x.provider === "RAZORPAY"); if (!integration?.encryptedSecret || b.paymentOrderId !== order.providerOrderId) return NextResponse.json({ error: "Invalid payment" }, { status: 400 }); const signature = crypto.createHmac("sha256", decryptSecret(integration.encryptedSecret)).update(`${b.paymentOrderId}|${b.paymentId}`).digest("hex"); if (!crypto.timingSafeEqual(Buffer.from(signature), Buffer.from(String(b.signature || "")))) return NextResponse.json({ error: "Invalid payment signature" }, { status: 400 }); await paid(order.id, b.paymentId, order.items); return NextResponse.json({ success: true, orderNumber: order.orderNumber }); }
  if (order.provider === "PAYPAL") { const integration = order.shop.payments.find(x => x.provider === "PAYPAL"); if (!integration?.encryptedSecret) return NextResponse.json({ error: "Invalid payment" }, { status: 400 }); const base = integration.mode === "live" ? "https://api-m.paypal.com" : "https://api-m.sandbox.paypal.com"; const auth = Buffer.from(`${integration.publicKey}:${decryptSecret(integration.encryptedSecret)}`).toString("base64"); const token = await (await fetch(`${base}/v1/oauth2/token`, { method: "POST", headers: { Authorization: `Basic ${auth}`, "Content-Type": "application/x-www-form-urlencoded" }, body: "grant_type=client_credentials" })).json(); const capture = await fetch(`${base}/v2/checkout/orders/${order.providerOrderId}/capture`, { method: "POST", headers: { Authorization: `Bearer ${token.access_token}`, "Content-Type": "application/json" } }); const result = await capture.json(); if (!capture.ok || result.status !== "COMPLETED") return NextResponse.json({ error: "PayPal capture failed" }, { status: 502 }); await paid(order.id, result.purchase_units?.[0]?.payments?.captures?.[0]?.id, order.items); return NextResponse.json({ success: true, orderNumber: order.orderNumber }); }
  return NextResponse.json({ error: "Unsupported payment" }, { status: 400 });
}
async function paid(orderId: string, paymentId: string, items: { variantId: string | null; quantity: number }[]) { await prisma.$transaction([prisma.shopOrder.update({ where: { id: orderId }, data: { paymentStatus: "PAID", status: "CONFIRMED", providerPaymentId: paymentId } }), ...items.filter(x => x.variantId).map(x => prisma.shopProductVariant.update({ where: { id: x.variantId! }, data: { inventory: { decrement: x.quantity } } }))]); }
