import type { LayoutArchetypeDefinition, LayoutArchetypeId } from "./LayoutArchetype";
import { compileArchitectural, compileAsymmetricStory, compileBento, compileCinematicFullBleedHero, compileEditorialSplitHero, compileFloatingProof, compileFramedCTA, compileGalleryJourney, compileImageStory, compileQuote } from "./archetypeCompilers";

const anatomy = ["section", "container", "column", "heading", "text", "button", "image", "divider"] as const;
const all = ["healthcare","real_estate","hospitality","food_and_beverage","education","beauty_wellness","fitness","automotive","construction","architecture_interiors","professional_services","legal_finance","ecommerce_d2c","manufacturing_industrial","logistics","travel","creative_portfolio","ngo_community","entertainment_events","technology_saas","personal_brand","unknown"] as const;
function define(value: LayoutArchetypeDefinition) { return Object.freeze({ ...value, allowedWidgetAnatomy: Object.freeze([...value.allowedWidgetAnatomy]), supportedIndustries: Object.freeze([...value.supportedIndustries]) }); }

export const ARCHETYPE_DEFINITIONS: Readonly<Record<LayoutArchetypeId, LayoutArchetypeDefinition>> = Object.freeze({
  editorialSplitHero: define({ id:"editorialSplitHero",semanticPurpose:"Establish a premium promise with balanced copy, actions, and portrait media.",allowedWidgetAnatomy:anatomy,layoutStructure:"Asymmetric two-column copy/media hero.",responsiveTransformation:"Two columns collapse to copy then media; actions stack on mobile.",spacingBehavior:"Open hero spacing scaled by art-direction density.",mediaRole:"Primary editorial portrait or product/place anchor.",typographyIntent:"Expressive single H1 with restrained supporting measure.",supportedIndustries:all,compile:compileEditorialSplitHero }),
  cinematicFullBleedHero: define({ id:"cinematicFullBleedHero",semanticPurpose:"Create an immersive opening moment led by brand imagery.",allowedWidgetAnatomy:anatomy,layoutStructure:"Full-bleed media and content share an overlapping grid plane.",responsiveTransformation:"Preserves overlay hierarchy with reduced padding and vertical action flow.",spacingBehavior:"Viewport-like open frame with edge-to-edge media.",mediaRole:"Atmospheric dominant image behind the promise.",typographyIntent:"Dramatic display H1 with high-contrast overlay copy.",supportedIndustries:["real_estate","hospitality","food_and_beverage","travel","creative_portfolio","entertainment_events","architecture_interiors","ecommerce_d2c"],compile:compileCinematicFullBleedHero }),
  asymmetricStorySection: define({ id:"asymmetricStorySection",semanticPurpose:"Tell a brand, founder, or practice story without a conventional split.",allowedWidgetAnatomy:anatomy,layoutStructure:"Three unequal columns for thesis, narrative, and offset media.",responsiveTransformation:"Three columns become two, then a linear semantic story.",spacingBehavior:"Open top offsets create editorial tension.",mediaRole:"Supporting portrait or contextual detail.",typographyIntent:"Editorial H2 paired with a larger lead paragraph.",supportedIndustries:["architecture_interiors","creative_portfolio","professional_services","personal_brand","education","ngo_community","ecommerce_d2c","real_estate","hospitality"],compile:compileAsymmetricStory }),
  bentoShowcase: define({ id:"bentoShowcase",semanticPurpose:"Present varied offers or features with unequal visual emphasis.",allowedWidgetAnatomy:anatomy,layoutStructure:"Twelve-track bento grid with 7/5 and 6/6 spans.",responsiveTransformation:"Twelve tracks reduce to two columns and then one.",spacingBehavior:"Balanced outer rhythm with dense internal cards.",mediaRole:"Each tile receives a distinct supporting media slot.",typographyIntent:"Compact H3 hierarchy under one editorial H2.",supportedIndustries:all,compile:compileBento }),
  imageStoryNarrative: define({ id:"imageStoryNarrative",semanticPurpose:"Advance a process or value narrative through alternating media beats.",allowedWidgetAnatomy:anatomy,layoutStructure:"Three alternating media/copy story beats.",responsiveTransformation:"Every beat becomes media then copy in a single column.",spacingBehavior:"Large gaps distinguish narrative beats.",mediaRole:"Sequential evidence that advances the story.",typographyIntent:"One H2 and concise beat-level H3s.",supportedIndustries:all,compile:compileImageStory }),
  floatingProofSection: define({ id:"floatingProofSection",semanticPurpose:"Integrate proof and metrics as a designed confidence moment.",allowedWidgetAnatomy:anatomy,layoutStructure:"Proof narrative paired with a floating metric cluster.",responsiveTransformation:"Metric cluster moves below proof and becomes a vertical stack on mobile.",spacingBehavior:"Framed open section with compact proof cards.",mediaRole:"No required image; evidence is the visual anchor.",typographyIntent:"Authoritative H2 with oversized metric typography.",supportedIndustries:all,compile:compileFloatingProof }),
  galleryJourney: define({ id:"galleryJourney",semanticPurpose:"Create a visual journey rather than a uniform image grid.",allowedWidgetAnatomy:anatomy,layoutStructure:"Lead image spans two rows beside varied supporting crops.",responsiveTransformation:"Mosaic becomes two columns and then an ordered single-column gallery.",spacingBehavior:"Open introduction with tightly curated image gaps.",mediaRole:"Primary storytelling system with five differentiated crops.",typographyIntent:"Quiet framing copy lets imagery dominate.",supportedIndustries:["real_estate","hospitality","food_and_beverage","travel","creative_portfolio","architecture_interiors","ecommerce_d2c","entertainment_events"],compile:compileGalleryJourney }),
  quoteInterlude: define({ id:"quoteInterlude",semanticPurpose:"Interrupt dense content with a human proof or point-of-view beat.",allowedWidgetAnatomy:anatomy,layoutStructure:"Centered high-contrast quote canvas.",responsiveTransformation:"Type scales down while keeping a narrow centered measure.",spacingBehavior:"Generous isolated whitespace.",mediaRole:"Typography replaces media as the emotional anchor.",typographyIntent:"Large quotation H2 and minimal attribution.",supportedIndustries:all,compile:compileQuote }),
  framedCTA: define({ id:"framedCTA",semanticPurpose:"Resolve the page into one premium conversion moment.",allowedWidgetAnatomy:anatomy,layoutStructure:"Centered content inside a framed canvas with paired actions.",responsiveTransformation:"Actions stack while content remains centered.",spacingBehavior:"Open outer space and concentrated inner padding.",mediaRole:"No required media; contrast and framing carry focus.",typographyIntent:"Concise decisive H2 with short supporting copy.",supportedIndustries:all,compile:compileFramedCTA }),
  architecturalProjectShowcase: define({ id:"architecturalProjectShowcase",semanticPurpose:"Showcase projects through a lead work and varied supporting studies.",allowedWidgetAnatomy:anatomy,layoutStructure:"Twelve-track lead project and three-study gallery.",responsiveTransformation:"Lead becomes full width; studies move to two columns then one.",spacingBehavior:"Measured gallery rhythm with varied crop heights.",mediaRole:"Architecture/project photography is primary evidence.",typographyIntent:"Editorial project names with restrained descriptions.",supportedIndustries:["real_estate","architecture_interiors","construction","creative_portfolio","professional_services"],compile:compileArchitectural }),
});
